### ISSUE TITLE
usage: streamlink [OPTIONS] <URL> [STREAM] streamlink: error: unrecognized arguments: --rtmp-rtmpdump=rtmpdump.exe

### ISSUE THREAD

**Issue by Skeletroller** [streamlink/streamlink-twitch-gui#842] opened 2021-11-18 22:35 UTC
### Checklist

- [X] I understand that **Streamlink Twitch GUI** is just a launcher for **Streamlink**
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink-twitch-gui/blob/master/CONTRIBUTING.md)
- [X] [I have checked the list of open and recently closed issues](https://github.com/streamlink/streamlink-twitch-gui/issues?q=is%3Aissue+sort%3Aupdated-desc)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink-twitch-gui/commits/master)

### Streamlink Twitch GUI version

v1.13.0

### Streamlink version

3.0.1

### Operating system, environment and configuration details

Windows 10, version 1903

### Description

In the Streamlink settings, i have set the streamlink executable to "C:\Users\Username\AppData\Local\Streamlink\bin\streamlinkw.exe" and set my player to VLC "C:\Program Files (x86)\VideoLAN\VLC\vlc.exe" but when i try opening any stream i get the error mentioned in the title.
I'v even tried looking for a solution in a [similar bug report](https://github.com/streamlink/streamlink-twitch-gui/issues/620) but it did not work for me. This is my first post on Github, im just a very confused casual user.

### Debug log

```text
[2021-11-18T22:02:20.660Z][debug][Application]
Parameters
{
    "_": [],
    "tray": false,
    "hide": false,
    "hidden": false,
    "max": false,
    "maximize": false,
    "maximized": false,
    "min": false,
    "minimize": false,
    "minimized": false,
    "reset-window": false,
    "versioncheck": true,
    "version-check": true,
    "logfile": true,
    "loglevel": "debug",
    "l": "debug",
    "launch": "",
    "goto": ""
}

[2021-11-18T22:02:22.621Z][debug][StreamingService]
Preparing to launch stream
{
    "id": "girlfriendreviews",
    "quality": "source",
    "low_latency": false,
    "disable_ads": false,
    "chat_open": false,
    "started": "2021-11-18T22:02:22.566Z",
    "stream": "405028866",
    "channel": "405028866"
}

[2021-11-18T22:02:22.639Z][debug][StreamingService]
Resolving streaming provider
{
    "provider": "streamlink",
    "providerUserData": {
        "exec": "C:\\Users\\Agnel\\AppData\\Local\\Streamlink\\bin\\streamlinkw.exe",
        "params": null,
        "pythonscript": null
    }
}

[2021-11-18T22:02:22.650Z][debug][StreamingService]
Found streaming provider
{
    "exec": "C:\\Users\\Agnel\\AppData\\Local\\Streamlink\\bin\\streamlinkw.exe",
    "params": null,
    "env": null
}

[2021-11-18T22:02:22.746Z][debug][StreamingService]
Spawning process
{
    "exec": "C:\\Users\\Agnel\\AppData\\Local\\Streamlink\\bin\\streamlinkw.exe",
    "params": [
        "--version"
    ],
    "env": null
}

[2021-11-18T22:02:24.125Z][debug][StreamingService]
Validated streaming provider
{
    "version": "3.0.1"
}

[2021-11-18T22:02:24.131Z][debug][StreamingService]
Resolving player
{
    "player": "vlc",
    "playerUserData": {
        "instance": true,
        "close": true,
        "title": true,
        "minimal": false,
        "exec": "C:\\Program Files (x86)\\VideoLAN\\VLC\\vlc.exe",
        "args": null,
        "type": "settings-streaming-player-vlc"
    }
}

[2021-11-18T22:02:24.138Z][debug][StreamingService]
Resolved player
{
    "exec": "C:\\Program Files (x86)\\VideoLAN\\VLC\\vlc.exe",
    "params": "--no-one-instance --play-and-exit --input-title-format \"{name} - {game} - {status}\"",
    "env": null
}

[2021-11-18T22:02:24.242Z][debug][StreamingService]
Spawning process
{
    "exec": "C:\\Users\\Agnel\\AppData\\Local\\Streamlink\\bin\\streamlinkw.exe",
    "params": [
        "--twitch-disable-hosting",
        "--player",
        "C:\\Program Files (x86)\\VideoLAN\\VLC\\vlc.exe",
        "--player-args",
        "--no-one-instance --play-and-exit --input-title-format \"GirlfriendReviews - Halo Infinite - Teabag Infinite - Epic MLG Pro Level Esports #1\"",
        "--retry-open",
        "1",
        "--retry-streams",
        "1",
        "twitch.tv/girlfriendreviews",
        "best"
    ],
    "env": null
}

[2021-11-18T22:02:26.278Z][error][StreamingService]
Error: usage: streamlink [OPTIONS] <URL> [STREAM]
{
    "id": "girlfriendreviews",
    "quality": "source",
    "low_latency": false,
    "disable_ads": false,
    "chat_open": false,
    "started": "2021-11-18T22:02:22.566Z",
    "stream": "405028866",
    "channel": "405028866"
}

[2021-11-18T22:05:24.607Z][debug][NotificationService]
Showing notification
{
    "provider": "auto",
    "current": "snoretoast",
    "data": {
        "title": "RevScarecrow has started streaming",
        "message": "Rev || Super Auto Pets Then Potion Craft twitch.tv/revscarecrow #vinesauce",
        "icon": "C:\\Users\\Agnel\\AppData\\Local\\Temp\\streamlink-twitch-gui\\cache\\icons\\revscarecrow-profile_image-cc78767b3cbb3a1d-300x300.png",
        "settings": 1
    }
}

[2021-11-18T22:08:15.912Z][debug][StreamingService]
Preparing to launch stream
{
    "id": "saltybet",
    "quality": "source",
    "low_latency": false,
    "disable_ads": false,
    "chat_open": false,
    "started": "2021-11-18T22:08:15.885Z",
    "stream": "43201452",
    "channel": "43201452"
}

[2021-11-18T22:08:15.919Z][debug][StreamingService]
Resolving streaming provider
{
    "provider": "streamlink-python",
    "providerUserData": {
        "exec": "C:\\Python38\\python.exe",
        "params": null,
        "pythonscript": "C:\\Users\\Agnel\\AppData\\Local\\Streamlink\\Python\\pythonw.exe"
    }
}

[2021-11-18T22:08:15.950Z][error][Application]
uncaughtException: Error: Buffer size limit exceeded

[2021-11-18T22:08:18.951Z][debug][StreamingService]
Found streaming provider
{
    "exec": "C:\\Python38\\python.exe",
    "params": [
        "C:\\Users\\Agnel\\AppData\\Local\\Streamlink\\Python\\pythonw.exe"
    ],
    "env": null
}

[2021-11-18T22:08:18.962Z][debug][StreamingService]
Spawning process
{
    "exec": "C:\\Python38\\python.exe",
    "params": [
        "C:\\Users\\Agnel\\AppData\\Local\\Streamlink\\Python\\pythonw.exe",
        "--version"
    ],
    "env": null
}

[2021-11-18T22:08:19.390Z][error][StreamingService]
Error: Unexpected version check output
{
    "id": "saltybet",
    "quality": "source",
    "low_latency": false,
    "disable_ads": false,
    "chat_open": false,
    "started": "2021-11-18T22:08:15.885Z",
    "stream": "43201452",
    "channel": "43201452"
}

[2021-11-18T22:08:24.843Z][debug][StreamingService]
Preparing to launch stream
{
    "id": "saltybet",
    "quality": "source",
    "low_latency": false,
    "disable_ads": false,
    "chat_open": false,
    "started": "2021-11-18T22:08:15.885Z",
    "stream": "43201452",
    "channel": "43201452"
}

[2021-11-18T22:08:24.848Z][debug][StreamingService]
Resolving streaming provider
{
    "provider": "streamlink-python",
    "providerUserData": {
        "exec": "C:\\Python38\\python.exe",
        "params": null,
        "pythonscript": "C:\\Users\\Agnel\\AppData\\Local\\Streamlink\\Python\\pythonw.exe"
    }
}

[2021-11-18T22:08:24.851Z][error][Application]
uncaughtException: Error: Buffer size limit exceeded

[2021-11-18T22:08:27.850Z][debug][StreamingService]
Found streaming provider
{
    "exec": "C:\\Python38\\python.exe",
    "params": [
        "C:\\Users\\Agnel\\AppData\\Local\\Streamlink\\Python\\pythonw.exe"
    ],
    "env": null
}

[2021-11-18T22:08:27.864Z][debug][StreamingService]
Spawning process
{
    "exec": "C:\\Python38\\python.exe",
    "params": [
        "C:\\Users\\Agnel\\AppData\\Local\\Streamlink\\Python\\pythonw.exe",
        "--version"
    ],
    "env": null
}

[2021-11-18T22:08:28.057Z][error][StreamingService]
Error: Unexpected version check output
{
    "id": "saltybet",
    "quality": null,
    "low_latency": null,
    "disable_ads": null,
    "chat_open": null,
    "started": null,
    "stream": null,
    "channel": null
}

[2021-11-18T22:08:37.253Z][debug][StreamingService]
Preparing to launch stream
{
    "id": "saltybet",
    "quality": "source",
    "low_latency": false,
    "disable_ads": false,
    "chat_open": false,
    "started": "2021-11-18T22:08:37.229Z",
    "stream": "43201452",
    "channel": "43201452"
}

[2021-11-18T22:08:37.257Z][debug][StreamingService]
Resolving streaming provider
{
    "provider": "streamlink",
    "providerUserData": {
        "exec": "C:\\Users\\Agnel\\AppData\\Local\\Streamlink\\bin\\streamlinkw.exe",
        "params": null,
        "pythonscript": null
    }
}

[2021-11-18T22:08:37.259Z][debug][StreamingService]
Found streaming provider
{
    "exec": "C:\\Users\\Agnel\\AppData\\Local\\Streamlink\\bin\\streamlinkw.exe",
    "params": null,
    "env": null
}

[2021-11-18T22:08:37.268Z][debug][StreamingService]
Spawning process
{
    "exec": "C:\\Users\\Agnel\\AppData\\Local\\Streamlink\\bin\\streamlinkw.exe",
    "params": [
        "--version"
    ],
    "env": null
}

[2021-11-18T22:08:38.587Z][debug][StreamingService]
Validated streaming provider
{
    "version": "3.0.1"
}

[2021-11-18T22:08:38.592Z][debug][StreamingService]
Resolving player
{
    "player": "vlc",
    "playerUserData": {
        "instance": true,
        "close": true,
        "title": true,
        "minimal": false,
        "exec": "C:\\Program Files (x86)\\VideoLAN\\VLC\\vlc.exe",
        "args": null,
        "type": "settings-streaming-player-vlc"
    }
}

[2021-11-18T22:08:38.597Z][debug][StreamingService]
Resolved player
{
    "exec": "C:\\Program Files (x86)\\VideoLAN\\VLC\\vlc.exe",
    "params": "--no-one-instance --play-and-exit --input-title-format \"{name} - {game} - {status}\"",
    "env": null
}

[2021-11-18T22:08:38.655Z][debug][StreamingService]
Spawning process
{
    "exec": "C:\\Users\\Agnel\\AppData\\Local\\Streamlink\\bin\\streamlinkw.exe",
    "params": [
        "--twitch-disable-hosting",
        "--player",
        "C:\\Program Files (x86)\\VideoLAN\\VLC\\vlc.exe",
        "--player-args",
        "--no-one-instance --play-and-exit --input-title-format \"SaltyBet - Retro - Salty's Dream Cast Casino! Place your bets at www.saltybet.com\"",
        "--retry-open",
        "1",
        "--retry-streams",
        "1",
        "twitch.tv/saltybet",
        "best"
    ],
    "env": null
}

[2021-11-18T22:08:40.446Z][error][StreamingService]
Error: usage: streamlink [OPTIONS] <URL> [STREAM]
{
    "id": "saltybet",
    "quality": "source",
    "low_latency": false,
    "disable_ads": false,
    "chat_open": false,
    "started": "2021-11-18T22:08:37.229Z",
    "stream": "43201452",
    "channel": "43201452"
}

[2021-11-18T22:18:46.344Z][debug][ChatService]
Preparing to launch chat
{
    "channel": "saltybet",
    "user": "skeletroller"
}

[2021-11-18T22:18:46.347Z][debug][ChatService]
Resolving chat provider
{
    "provider": "browser",
    "providerUserData": {
        "url": "default",
        "type": "settings-chat-provider-browser"
    }
}
```

**Comment by bastimeyer** [comment] 2021-11-18 22:57
Duplicate of https://github.com/streamlink/streamlink-twitch-gui/issues/841#issuecomment-973163352

Once again, not a Streamlink Twitch GUI problem.

**You have not read the changelog of the Streamlink 3.0.0 release**, which has introduced breaking changes, hence the major version bump from 2.4.0 to 3.0.0:
https://github.com/streamlink/streamlink/blame/3.0.1/CHANGELOG.md#L27-L29
https://streamlink.github.io/changelog.html#streamlink-3-0-0-2021-11-17

> - BREAKING: removed the following CLI arguments (and respective session options):
>   - `--rtmp-rtmpdump`, `--rtmpdump`, `--rtmp-proxy`, `--rtmp-timeout`  
>    Users of Streamlink's Windows installer will need to update their [config file](https://streamlink.github.io/cli.html#configuration-file).

**If you have `rtmp-rtmpdump` in your default streamlink config file, which is the case for all users on Windows who have previously installed a version of Streamlink lower than 3.0.0 via the Windows installer, then you have to remove the `rtmp-rtmpdump` line from the config file.**

Streamlink's Windows installer has to create a config file because of the custom ffmpeg dependency path and the lack of proper PATH resolution for third-party binaries on that operating system. If a config file already exists, eg. when upgrading Streamlink, then the installer won't touch the config file, because that would mess with user's configs, which it's not supposed to. So if a parameter gets removed in a major version change and becomes unsupported, then you have to fix your old config file yourself.

----

I'm going to lock this thread now and keep it open because I don't want to deal with countless of duplicates.

**Closed** 2022-01-05 17:21 UTC
Labels: invalid
