### ISSUE TITLE
computer freezing for 10 seconds when opening from system tray

### ISSUE THREAD

**Issue by shamoke** [streamlink/streamlink-twitch-gui#390] opened 2017-01-04 22:28 UTC
When I set it to minimize to the system tray and then click the icon in the system tray to reopen it my computer freezes for about 10 seconds every time. If I don't minimize it I can switch back and forth to it with no problems. This wasn't happening with the old version of the livestreamer gui I was using. I'm on windows 7, i5-2500k, 8gb ram,  gtx 560.

edit: After further testing it's not just the system tray. Minimizing it in general and then opening it again causes the freezing. If I don't minimize I can switch between windows with no problems.

**Comment by bastimeyer** [comment] 2017-01-05 06:45
During the `1.0.0` release the application upgraded from NW.js `0.12.3` to `0.19.0` (Chromium `0.41.x` to `0.55.x`), so quite some new stuff has been added. I can't tell you why you're seeing these freezes, but this is very unlikely caused by the app code here and could instead be caused by either NW.js/Chromium or your own system. Can you provide any system stats like memory consumption or CPU usage?
You could try deleting the cache folder or disabling Chromium's GPU acceleration:
http://docs.nwjs.io/en/latest/References/Command%20Line%20Options/

You should also try to reproduce this with other NW.js applications that are using the same version.

**Comment by bastimeyer** [comment] 2017-01-05 11:26
There's a GamePad API bug in NW.js right now that has also been reported here: #367
The issue has also been reported on the NW.js repo: nwjs/nw.js#5547
Maybe this is related, I'm not sure...

**Comment by bastimeyer** [comment] 2017-03-31 19:20
@shamoke Does this issue still exist in the [latest release](https://github.com/streamlink/streamlink-twitch-gui/releases/latest)? The `1.2.1` release now comes with NW.js `0.21.3` and Chromium `57.x`.

**Comment by adamhab15** [comment] 2017-04-01 18:05
I have the same problem as shamoke. It still freezes the computer for up to 10 seconds even on 1.2.1.

**Comment by bastimeyer** [comment] 2017-04-02 06:39
@adamhab15 I would appreciate it if you could provide at least a couple of details, so the common denominator of this issue can be found.

As I've already said in my previous posts, this is a NW.js/Chromium issue which may be caused by other applications running in the background. There's nothing which I can do here and the issue needs to be fixed upstream in NW.js/Chromium.

Btw, I'm still curious if setting the [`--disable-gpu`](http://docs.nwjs.io/en/latest/References/Command%20Line%20Options/) launch parameter fixes the issue and also if this issue exists in other NW.js based applications that use the same NW.js version. A even better idea is testing a blank NW.js app... See [nwjs.io](https://nwjs.io).

**Comment by adamhab15** [comment] 2017-04-02 07:02
I'm on W7 64-bit. 
16GB ram
i5 2500k
AMD 7870

I tried testing the blank app, it also freezes everything. Disabling GPU changes nothing.
I'm using WiinUSoft which maps a Wii U controller to a virtual Xbox 360 controller.
It uses the SCP driver package which ds4windows (that shamoke is using) also needs to function.

**Comment by bastimeyer** [comment] 2017-04-02 07:06
Thanks.

> blank app, it also freezes everything
> WiinUSoft which maps a Wii U controller to a virtual Xbox 360 controller

You should report this on the NW.js repo. See nwjs/nw.js#5547 or open a new issue, not sure.

**Comment by bastimeyer** [comment] 2017-11-23 06:48
Closing, since it's a NW.js issue and unrelated to Streamlink Twitch GUI.
The latest release uses the latest NW.js version, which is all that can be done here in order to prevent platform related issues.

**Closed by bastimeyer** 2017-11-23 06:48 UTC
Labels: platform issue, Windows
