### ISSUE TITLE
Panels API gone

### ISSUE THREAD

**Issue by WasserEsser** [streamlink/streamlink-twitch-gui#681] opened 2019-11-13 19:23 UTC
Just a heads up, the panels API is now gone.

![image](https://user-images.githubusercontent.com/14238527/68797109-3dad2b80-0654-11ea-9c17-45288f0e4c82.png)

**Comment by bastimeyer** [comment] 2019-11-13 19:37
Yes, I know, it's related to streamlink/streamlink#2680

**Comment by WasserEsser** [comment] 2019-11-13 19:47
@bastimeyer How about switching to /gql with "operationName": "ChannelPanels" instead?

**Comment by bastimeyer** [comment] 2019-11-13 19:55
GQL is not an option right now due to how the app's TwitchAdapter for EmberData works.
Making the channel panels work again via the old private API is also not a problem, as it simply means using Twitch's client-id and not using the Authorization header. The big problem however are private API endpoints which require auth data, like followed/following games, hosted streams, subscriptions, etc. The GQL API doesn't solve this, as it pretty much has the same restrictions.

I've been working on making the necessary changes in the Twitch GUI. Unfortunately though, this ultimately means removing those parts of the app which have been making API calls which are not working anymore now. But since this API issue is unstable and apparently getting fixed after several hours, it makes it really difficult to make a final decision here.

**Comment by WasserEsser** [comment] 2019-11-13 20:29
I was not aware of the fact that this situation has been ongoing and that there are issues for it already. I was looking for "panels" in the issues but didn't find any open issues.

**Comment by bastimeyer** [comment] 2019-11-13 20:39
Let's keep this open, so it can be properly tracked and closed with a code change, in case this API issue doesn't get fixed by Twitch (which it looks like).

**Comment by rasberryrabbit** [comment] 2019-11-14 10:18
Is there twitch oauth option on Twitch GUI?

**Comment by bastimeyer** [comment] 2019-11-14 10:43
Not exactly sure what you mean, but if you're asking whether you can use an OAuth token from the Twitch website in Streamlink Twitch GUI to make it work again, similar to Streamlink, then no, you can't, because Twitch's OAuth token doesn't grant the permissions which the Twitch GUI is asking for, at least in the current release. You can sign in with any OAuth token though that grants the required permissions. https://github.com/streamlink/streamlink-twitch-gui/wiki/Twitch.tv-login#oauth-token-login

I don't want to support features though which only work with Twitch's OAuth token which the user has to read from their web browser's dev tools. This is an anti-feature. So if this API doesn't get fixed by Twitch any time soon, I will have to remove these features from the Twitch GUI, unfortunately. You can blame Twitch's decisioning here for unnecessarily blocking APIs which have been working for the whole time, even though they weren't officially supported for 3rd party apps.

**Comment by bastimeyer** [comment] 2019-11-18 00:47
Did some further testing and it looks like some of the API endpoints on the private API are also available on kraken, but not documented and in an unfinished/broken state. It looks like there was an attempt of making the endpoints available to third parties, but it was somehow cancelled, probably because helix was being worked on. Helix however doesn't provide any of those endpoints.

----

- Getting the subscriptions is not possible anymore
- Getting the hosted streams by followed channels is not possible anymore
- I've already said earlier that channel panels are only available on the private API with Twitch's client-id and no auth data. This is still true and I couldn't find anything hidden on the public APIs. If I want to keep this feature, Twitch's client-id has to be used, but I don't want to make a decision yet. It's also unlikely that the endpoint on the private API will stay, since the website is completely using the GQL API. 
- The followed games endpoints however still seem to be hidden on kraken (all games, live games unfortunately are not), but only partially. Instead of user names and game names, you have to provide the record IDs, which is consistent with (un)following channels on kraken and makes sense. It's also possible to create a new followed games record, but deleting a followed games record doesn't seem to be possible, which is weird. I've tried all possible combinations based on the related endpoints and ones which have been used in the past, but without any success. The followed games list also doesn't return proper game records and a bit of data is missing.
   
  Last year, the followed/following games endpoints had also been changed, which doesn't make any sense considering that the new website had already switched to the GQL API and the old API endpoints - which were never publicly available - were not used anymore. See my comment in this issue:
https://github.com/streamlink/streamlink-twitch-gui/issues/549#issuecomment-377330076
  ```
  GET https://api.twitch.tv/api/users/:username/follows/games/:gamename
  PUT https://api.twitch.tv/api/users/:username/follows/games/:gamename
  DELETE https://api.twitch.tv/api/users/:username/follows/games/:gamename
  ===>
  GET https://api.twitch.tv/kraken/users/:userid/follows/games/:gameid
  PUT https://api.twitch.tv/kraken/users/:userid/follows/games/:gameid
  DELETE https://api.twitch.tv/api/users/:userid/follows/games/:gameid (doesn't work)
  ```

----

And to talk about kraken as a whole, we still don't have any date when it will be shut down. It was supposed to be shut down on 2018-12-31, but due to heavy backlash of the community, Twitch kept it alive, because helix was and is still missing many features. There aren't even endpoints available for (un)following channels (new merged with users) or listing streams of followed users without having to do extremely silly queries. If this doesn't change and kraken gets killed eventually without having any improvements on helix, then this would probably mean the death of the Twitch GUI. To me, it looks like helix was designed with the intention to limit third party applications to the very basic stuff.

**Comment by iliketodev** [comment] 2019-11-20 11:13
i have no idea how this all works, but i find it weird that the one line not working (DELETE) is the one starting with "api.twitch.tv/api/" where the working ones (GET and PUT) start with "api.twitch.tv/kraken/"...
i'm sure its just a typo in your post, and not in your actual testing, but just in case :)

**Comment by bastimeyer** [comment] 2019-11-20 13:25
Just a typo here. Thanks though :sweat_smile:

**Comment by bastimeyer** [comment] 2019-11-21 04:48
Reopening until the next release...

**Comment by bastimeyer** [comment] 2019-11-23 08:11
[`v1.9.0`](https://github.com/streamlink/streamlink-twitch-gui/releases/latest) has been released now with all the API endpoints causing issues removed.

**Closed by bastimeyer** 2019-11-23 08:11 UTC
Labels: Twitch API
