### ISSUE TITLE
Why not make the streamlink gui universal, and support twitch,youtube & beam? instead of only twitch.

### ISSUE THREAD

**Issue by wazerstar** [streamlink/streamlink-twitch-gui#415] opened 2017-02-22 19:57 UTC
Since big contenders are moving to youtube from twitch, will we see this in the near future?

**Comment by bastimeyer** [comment] 2017-02-22 21:08
Duplicate of #192 / #309.
Please read my detailed answer regarding a hitbox.tv implementation [here](https://github.com/streamlink/streamlink-twitch-gui/issues/192#issuecomment-170332865), which can be applied for all other streaming platforms.

**[Youtube](https://www.youtube.com/live)**
I don't see any real structure behind youtube live. Just take a sec and compare it to Twitch. There's not much besides searching for a specific channel or browsing a list of streams grouped by a couple of topics and ordered by viewer count. The list of streams is extremely random, which is unexpected when browsing and to a certain degree also kind of awkward. There's basically just one single category for all "[gaming](https://www.youtube.com/playlist?list=PLiCvVJzBupKmEehQ3hnNbbfBjLUyvGlqx)" related streams.

**[Beam](https://beam.pro/browse/all)**
It looks like there are two channels which have 300 viewers at the time I am writing this (monstercat music streaming is one of them, where I expect users having it running in the background) and a couple of channels with around or below 50 viewers.

Since I'm the only dev on this project and since I'm working on it in my free time for fun, I don't want to spend even more time thinking about adding other services. People are requesting more and more stuff and don't even think about the implications when doing so without contributing to the project in any kind. Even if I had the time and motivation implementing multiple streaming services, I don't think that those two are worth spending time on. I also don't understand where people get the impression from that this is THE "Streamlink GUI". The application is called "Streamlink Twitch GUI" (formerly Livestreamer Twitch GUI), and is just one of many GUIs / front ends for Streamlink or Livestreamer, but dedicated to Twitch. If your favorite broadcaster wants to ditch Twitch and starts streaming somewhere else instead, then you should be using a different GUI or the Streamlink CLI.

**Closed** 2017-03-05 22:04 UTC
Labels: duplicate, question
