### ISSUE TITLE
White Squares, Graphical Artifacts when Browsing Streams Directory

### ISSUE THREAD

**Issue by jorgeluiscarrillo** [streamlink/streamlink-twitch-gui#819] opened 2021-08-16 19:40 UTC
### Checklist

- [X] I understand that **Streamlink Twitch GUI** is just a launcher for **Streamlink**
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink-twitch-gui/blob/master/CONTRIBUTING.md)
- [X] [I have checked the list of open and recently closed issues](https://github.com/streamlink/streamlink-twitch-gui/issues?q=is%3Aissue+sort%3Aupdated-desc)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink-twitch-gui/commits/master)

### Streamlink Twitch GUI version

v1.12.0

### Streamlink version

2.3.0

### Operating system, environment and configuration details

Fedora 34 (AppImage), Xorg, Intel HD Graphics 3000

### Description

https://user-images.githubusercontent.com/33134232/129619790-bc0352f4-c31d-4d9e-bc23-3f6f18444335.mp4

When opening the Top Streams directory or a game directory, there are graphical artifacts (white squares) once it is loaded. The artifacts eventually go away as you scroll or move mouse. I can reproduce this issue about 90% of the time usually by going from my followed streams to the Top Streams directory. There are errors in the debug log when it happens. This issue seems to have been introduced in the latest version as I have tested v1.11.0 and can't reproduce.

### Debug log

```text
failed to open /usr/lib64/dri/hybrid_drv_video.so
Not using hybrid_drv_video.so
[7987:8032:0816/120920.597800:ERROR:object_proxy.cc(621)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
[7987:8032:0816/120920.597959:ERROR:object_proxy.cc(621)] Failed to call method: org.freedesktop.UPower.GetDisplayDevice: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
[7987:8032:0816/120920.598079:ERROR:object_proxy.cc(621)] Failed to call method: org.freedesktop.UPower.EnumerateDevices: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
[8012:8012:0816/120920.639706:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.
[debug][Application]
Parameters
{
    "_": [],
    "tray": false,
    "hide": false,
    "hidden": false,
    "max": false,
    "maximize": false,
    "maximized": false,
    "min": false,
    "minimize": false,
    "minimized": false,
    "reset-window": false,
    "versioncheck": true,
    "version-check": true,
    "logfile": true,
    "loglevel": "debug",
    "l": "debug",
    "launch": "",
    "goto": ""
}
[8016:8021:0816/120922.771778:ERROR:cert_verify_proc_builtin.cc(559)] No net_fetcher for performing AIA chasing.
[8016:8021:0816/120923.265617:ERROR:cert_verify_proc_builtin.cc(559)] No net_fetcher for performing AIA chasing.
[8012:8012:0816/120954.693831:ERROR:shared_image_representation.cc(203)] Attempt to read from an uninitialized SharedImage
[8012:8012:0816/120954.695440:ERROR:shared_image_representation.cc(203)] Attempt to read from an uninitialized SharedImage
[8012:8012:0816/120954.696472:ERROR:shared_image_representation.cc(203)] Attempt to read from an uninitialized SharedImage
[8012:8012:0816/120954.926683:ERROR:shared_image_representation.cc(203)] Attempt to read from an uninitialized SharedImage
[8012:8012:0816/120954.927240:ERROR:shared_image_representation.cc(203)] Attempt to read from an uninitialized SharedImage
[8012:8012:0816/120955.076192:ERROR:shared_image_representation.cc(203)] Attempt to read from an uninitialized SharedImage
[8012:8012:0816/120955.559846:ERROR:shared_image_representation.cc(203)] Attempt to read from an uninitialized SharedImage
[8012:8012:0816/120955.846961:ERROR:shared_image_representation.cc(203)] Attempt to read from an uninitialized SharedImage
[8012:8012:0816/120955.889677:ERROR:shared_image_representation.cc(203)] Attempt to read from an uninitialized SharedImage
[8012:8012:0816/120956.712704:ERROR:shared_image_representation.cc(203)] Attempt to read from an uninitialized SharedImage
[8012:8012:0816/120956.800793:ERROR:shared_image_representation.cc(203)] Attempt to read from an uninitialized SharedImage
[8012:8012:0816/120956.843881:ERROR:shared_image_representation.cc(203)] Attempt to read from an uninitialized SharedImage
[8012:8012:0816/120957.032535:ERROR:shared_image_representation.cc(203)] Attempt to read from an uninitialized SharedImage
[8012:8012:0816/120957.317760:ERROR:shared_image_representation.cc(203)] Attempt to read from an uninitialized SharedImage
[8012:8012:0816/120957.861453:ERROR:raster_decoder.cc(2167)] [.RenderWorker-0x55f277e55c90]GL ERROR :GL_INVALID_VALUE : glCopySubTexture: Cannot clear non-combineable rects.
[8012:8012:0816/120957.877261:ERROR:shared_image_representation.cc(203)] Attempt to read from an uninitialized SharedImage
[8012:8012:0816/120958.207054:ERROR:shared_image_representation.cc(203)] Attempt to read from an uninitialized SharedImage
[8012:8012:0816/121039.307373:ERROR:shared_image_representation.cc(203)] Attempt to read from an uninitialized SharedImage
[8012:8012:0816/121039.573436:ERROR:raster_decoder.cc(2167)] [.RenderWorker-0x55f277e55c90]GL ERROR :GL_INVALID_VALUE : glCopySubTexture: Cannot clear non-combineable rects.
[8012:8012:0816/121039.606600:ERROR:shared_image_representation.cc(203)] Attempt to read from an uninitialized SharedImage
[8012:8012:0816/121039.741789:ERROR:shared_image_representation.cc(203)] Attempt to read from an uninitialized SharedImage
```

**Comment by bastimeyer** [comment] 2021-08-16 19:52
Duplicate of #814.
As already said over there, this is an NW.js/Chromium rendering issue. I can't reproduce this on my system and have never seen anything similar to this.

NW.js was bumped from 0.45 to 0.52 in v1.12.0 and it just got bumped again from 0.52 to 0.55 on the master branch. Please check the debug build from the latest build artifacts and also please check whether `--disable-gpu` helps.
https://github.com/streamlink/streamlink-twitch-gui#development-version

Other than that there's not much I can do. This is [already the latest NW.js version](https://nwjs.io/blog/) and if there's a bug upstream related to rendering and/or GPU acceleration, then this needs to be reproduced in an isolated test case / demo app and then reported upstream.

Let's keep this thread open, as it contains more information than the other one.

**Comment by bastimeyer** [comment] 2021-08-16 19:58
https://bugs.chromium.org/p/chromium/issues/detail?id=1185889

**Comment by jorgeluiscarrillo** [comment] 2021-08-16 20:04
> Duplicate of #814.
> As already said over there, this is an NW.js/Chromium rendering issue. I can't reproduce this on my system and have never seen anything similar to this.
> 
> NW.js was bumped from 0.45 to 0.52 in v1.12.0 and it just got bumped again from 0.52 to 0.55 on the master branch. Please check the debug build from the latest build artifacts and also please check whether `--disable-gpu` helps.
> https://github.com/streamlink/streamlink-twitch-gui#development-version
> 
> Other than that there's not much I can do. This is [already the latest NW.js version](https://nwjs.io/blog/) and if there's a bug upstream related to rendering and/or GPU acceleration, then this needs to be reproduced in an isolated test case / demo app and then reported upstream.
> 
> Let's keep this thread open, as it contains more information than the other one.

Thanks, I haven't tested the dev builds, but `--disable-gpu` seems to have fixed it for me on latest stable. In fact, I'm noticing much smoother performance!

**Comment by Mayurifag** [comment] 2021-09-26 21:19
Im also having this issue on garuda linux mate with nvidia latest dkms drivers. But still didnt have this issue on same system via windows 10

**Comment by bastimeyer** [comment] 2021-09-26 21:26
> May we have the setting in graphical interface when «enable hidden settings» mark is active?

`--disable-gpu` is a Chromium launch parameter, not something that can be set during runtime. You'll have to add this to your launcher. Packaged applications store launchers in `/usr/share/applications` and you can copy those to `~/.local/share/applications` and modify them. There you can add `--disable-gpu` to the `Exec` field.

----

NW.js 0.57.0 has been released yesterday with the latest Chromium 94 version:
https://nwjs.io/blog/v0.57.0/

I had already tried updating to NW.js 0.56.0, but the Windows builds were broken and there hadn't been a bugfix release for some reason.
cab9e21488f3d7069dc3e2eaee18dcb3fa51c7ff

I will check 0.57.0 tomorrow when I have the time. If you want to try it for yourself, change the NW.js version string in `src/config/main.json` and build the application according to the section described in CONTRIBUTING.md.

**Comment by Mayurifag** [comment] 2021-09-26 21:27
oopsy, sorry, didnt thought you'll answer so fast, already made it working via update on my post

**Comment by bastimeyer** [comment] 2021-09-29 16:38
I've pushed the nwjs-57 branch to the repo which you can use to try building the app.
https://github.com/streamlink/streamlink-twitch-gui/compare/nwjs-57

I haven't merged it into master yet because of another NW.js issue in regards to nonsense stderr log messages which I'd like to see resolved first.

**Comment by jorgeluiscarrillo** [comment] 2021-09-29 23:36
Tested nwjs-57 and same error: `ERROR:shared_image_representation.cc(214)] Attempt to read from an uninitialized SharedImage`.

Not sure if coincidence, but seems to happen less often.

**Comment by bastimeyer** [comment] 2022-01-08 22:17
NW.js 0.60 has just been pushed to master:
977b4b106aaea8fc7e63faf52587bf38b21d179a

**Comment by jorgeluiscarrillo** [comment] 2022-02-03 19:57
Apologies for the late update. I've updated to the latest version and played around with it for a couple days now. I am no longer experiencing this issue.

**Closed** 2022-02-03 20:05 UTC
Labels: os: Linux, platform issue
