### ISSUE TITLE
Sign function not working

### ISSUE THREAD

**Issue by LabAviator** [streamlink/streamlink-twitch-gui#500] opened 2017-08-31 02:26 UTC
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] I tried solving my issue by reading the project's wiki first.
- [x] I have read the contribution guidelines und used the search function to find already existing threads.

### Description

So the issue is pretty easily explained. When I try to sign in by hitting the "Sign in"-button, a site is opened in my browser. The Twitch site which asks me to authorize access to my Twitch accounts opens. I authorize it and then it redirects me to a site which says "This window or tab can be closed now!". However after that I'm not being signed in. In Streamlink GUI I now instead of the "Sign in"-button have an Abort-button. Checking my Twitch account, Streamlink Twitch GUI does have authorization to access my account.

Repeating the process does not resolve the issue. Installing Streamlink GUI to my C-Drive did not resolve it either. A re-installation didn't help either.

### Expected / Actual behavior

After authorizing access to the Twitch account, you should be logged in in the Streamlink Twitch GUI.

### Reproduction steps

1. Open up the newest version of Streamlink Twitch GUI installed via the Windows 64-bit installer. (Logout if necessary)
2. Login and authorize access to your Twitch account if asked.
3. Check the Streamlink Twitch GUI.

### Environment details

Operating system and version: Windows 10 (1703)
Streamlink Twitch GUI version: 
Streamlink version: 1.3.1
Configuration details: Absolute path to pythonw.exe and streamlink-script.py saved.

**Comment by PZSOI** [comment] 2017-09-02 20:43
Hi. I had the same issue, but it disappeared after I updated from streamlink 0.6.0 to 0.7.0. Could your problem be the same as mine was?

**Comment by LabAviator** [comment] 2017-09-03 15:07
I don't think that's the issue. I've only downloaded Streamlink a few days ago. It is the newest version.

**Comment by Mayurifag** [comment] 2017-09-08 16:15
I cant login sometimes as well (even if I was logged in before). Maybe its twitch related problems due to many people of using service.

**Comment by bastimeyer** [comment] 2017-09-09 04:00
Sorry for the late response, I have been busy with other stuff and didn't have to to respond yet.

> it redirects me to a site which says "This window or tab can be closed now!". However after that I'm not being signed in. In Streamlink GUI I now instead of the "Sign in"-button have an Abort-button

This looks like your browser doesn't send the returned oauth token to the Twitch GUI app after being redirected from the Twitch login form.

The [OAuth2 implicit code flow](https://dev.twitch.tv/docs/v5/guides/authentication#oauth-implicit-code-flow-user-access-tokens) looks like this:

1. [Start a local http server](https://github.com/streamlink/streamlink-twitch-gui/blob/v1.3.1/src/app/services/AuthService.js#L91) with the static port [65432](https://github.com/streamlink/streamlink-twitch-gui/blob/v1.3.1/src/config/twitch.json#L11).
2. [Open the Twitch.tv auth request form in the user's default web browser](https://github.com/streamlink/streamlink-twitch-gui/blob/v1.3.1/src/app/services/AuthService.js#L119). Twitch will redirect to the local webserver on success or failure.
3. [Wait for the redirect on the local webserver](https://github.com/streamlink/streamlink-twitch-gui/blob/v1.3.1/src/app/services/AuthService.js#L94-L97), [send the user this HTML document](https://github.com/streamlink/streamlink-twitch-gui/blob/v1.3.1/src/oauth-redirect.html) and [read the returned oauth token from the URL hash](https://github.com/streamlink/streamlink-twitch-gui/blob/v1.3.1/src/oauth-redirect.html#L29).
4. [Send a request to the local webserver with the returned oauth token](https://github.com/streamlink/streamlink-twitch-gui/blob/v1.3.1/src/oauth-redirect.html#L37-L47) (or tell the user to manually insert the oauth token if javascript has been disabled and skip step 5).
5. [Validate the submitted oauth token](https://github.com/streamlink/streamlink-twitch-gui/blob/v1.3.1/src/app/services/AuthService.js#L99-L115).

Since you're on Windows, could it be possible that you're also using an Antivirus software, which is interfering with the local webserver and the oauth token is never being read by the Twitch GUI?

**Comment by LabAviator** [comment] 2017-09-10 14:58
> Since you're on Windows, could it be possible that you're also using an Antivirus software, which is interfering with the local webserver and the oauth token is never being read by the Twitch GUI?

I am running Avast as an antivirus. I just tried disabling it, however that does not resolve the issue. I also already did try disabling adblockers and scriptblockers and using a whole different browser. The issue remains the same.

**Comment by bastimeyer** [comment] 2017-09-10 16:35
I don't have any issues with HTTPS-everywhere in Chrome. And I don't think that this is the source of the issue, since adding rules for "localhost" would be bad and I don't think they are doing this. Please disable all browser addons/extensions and try it again.

You can also check the Chrome dev tools. Just press F12 on the Twitch sign in / auth form, open the "Network" tab in the dev tools so that it starts recording all requests, submit the auth form and see if your browser correctly sends another HTTP request to `http://localhost:65432/token` once you've been redirected by Twitch to `http://localhost:65432/redirect` (step 4).

The main issue here is that the script that does the HTTP request doesn't know if it's been intercepted. It just waits for a response and checks the HTTP status code returned by the token validation: 200 or 500.

If you disable Javascript, the redirection page will give you instructions for manually copying the oauth token. Maybe I should add these instructions to the javascript-enabled page as well, so that the user does know that something went wrong and they can manually finish the procedure. I deliberately designed it like this, because it's usually a bad idea to show the user these tokens. That's why the script also replaces the URL with `/redirect#success` or `/redirect#failure`, so that it doesn't get added to the browsing history.

**Comment by bastimeyer** [comment] 2017-10-26 20:02
Closing the thread, since the auth flow is working as intended.
Please make sure that the web browser doesn't have any addons/extensions enabled or the system any http sniffing/modifying tools installed that could interfere with the auth redirection.

**Closed by bastimeyer** 2017-10-26 20:02 UTC
Labels: unconfirmed, Windows
