### ISSUE TITLE
Language filter appears to not work at all

### ISSUE THREAD

**Issue by chrisheib** [streamlink/streamlink-twitch-gui#724] opened 2020-05-21 10:20 UTC
## Bug report

- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] This is a bug report and I have read the contribution guidelines.

### Environment details

**Operating system and version:**  
Windows 10

**Streamlink Twitch GUI version:**  
1.9.1 (Set to German)

**Streamlink version:**  
1.3.1

### Description

The language filter is not being applied to streams. (Language fading is working correctly.)
Streams with languages that are not selected are being shown. 

### Expected / Actual behavior

Streams with languages that are not selected don't get shown in the streamlist.

### Reproduction steps

1. Go to Options.
2. Set Language Filter to 'Filter'
3. Select 'German' and 'English' only.
4. Apply Settings
5. Go to Streams
6. Spanish and Korean streams appear in the list.

### Additional comments, screenshots, etc.

![grafik](https://user-images.githubusercontent.com/6112968/82549397-2b5cfe80-9b5d-11ea-8502-7cd2e56ce371.png)

![grafik](https://user-images.githubusercontent.com/6112968/82549556-665f3200-9b5d-11ea-8e2c-02ca2c9b9c8b.png)

**Comment by bastimeyer** [comment] 2020-05-21 10:28
Duplicate of #706

See the changelog:
https://github.com/streamlink/streamlink-twitch-gui/blame/master/CHANGELOG.md#L14

**Closed by bastimeyer** 2020-05-21 10:28 UTC

**Comment by chrisheib** [comment] 2020-05-21 10:34
Can't the filtering be clientside theoretically tho?

**Comment by bastimeyer** [comment] 2020-05-21 10:38
No.

If you search for "client side filtering" on the issue tracker, you will find plenty of comments:
#564, #421

**Comment by chrisheib** [comment] 2020-05-21 10:47
Thanks alot for the replies, I understand now. Guess some multithreaded querying with multiple languages in parrallel wouldn't work either, I don't know enough about the API limitations.

Do you have plans for a new release, or should I rather build the current Version myself for now?

Also thank you very much for maintaining this project, it's a really nice tool <3

**Comment by bastimeyer** [comment] 2020-05-21 11:11
> multithreaded querying with multiple languages in parrallel

Those massive API requests are not possible since Twitch is already rate limiting the new API (which btw is a total disaster) and has recently tried to also introduce it to the old one which is currently used here. They've backpedaled though after receiving a shitstorm on their forums. Still, filtering features and the likes can only be implemented here if they are supported on their API and doing multiple network requests to achieve just one goal is always bad. See my comment here regarding a recent temporary change on the followed streams API endpoint:
https://discuss.dev.twitch.tv/t/kraken-streams-followed-not-ordered-by-viewers/23772/8

> Do you have plans for a new release

Probably this weekend. I need to check a couple more things first, and I don't have the time today.

> or should I rather build the current Version myself for now

You can always build from the master branch. The more people who are running the latest dev version, the better the chances for finding bugs/issues which I've missed.

> it's a really nice tool

thanks
