### ISSUE TITLE
Add a command line option for switching themes

### ISSUE THREAD

**Issue by sahinakkaya** [streamlink/streamlink-twitch-gui#918] opened 2022-10-31 21:11 UTC
### Checklist

- [X] I understand that **Streamlink Twitch GUI** is just a launcher for **Streamlink**
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink-twitch-gui/blob/master/CONTRIBUTING.md)
- [X] [I have checked the list of open and recently closed issues](https://github.com/streamlink/streamlink-twitch-gui/issues?q=is%3Aissue+sort%3Aupdated-desc)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink-twitch-gui/commits/master)

### Description

Setting the gui theme to "System settings" doesn't work for me (Qtile on Arch). So I wonder if it is possible to add a new command line option to control the theme outside of the program so that I can automate it via scripting
```
$ streamlink-twitch-gui --theme Light
$ streamlink-twitch-gui --theme Dark
```

**Comment by bastimeyer** [comment] 2022-10-31 22:58
If you have selected the system settings color theme, then NW.js/Chromium chooses the color scheme automatically for you via the [`prefers-color-scheme` CSS media query](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme), whose supported values are [`no-preference`, `light` and `dark`](https://github.com/streamlink/streamlink-twitch-gui/blob/v2.2.0/src/config/themes.json). Streamlink Twitch GUI's [`ThemeService`](https://github.com/streamlink/streamlink-twitch-gui/blob/v2.2.0/src/app/services/theme.js) checks whether any of those values match the media query, and the matching value gets a [`change`](https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList/change_event) event listener attached to the `MediaQueryList` object [that reacts to changes made to your system settings](https://github.com/streamlink/streamlink-twitch-gui/blob/v2.2.0/src/test/tests/services/theme.js#L93-L167), as long as it's supported by Chromium which needs to have support implemented for various OSes, DEs and WMs.

Adding a command line parameter for choosing/changing the theme is fairly simple. The main issue I have with this though is that it'd be a feature just for the lack of support in Chromium. But considering that
https://bugs.chromium.org/p/chromium/issues/detail?id=998903
is still not resolved by the Chromium devs, adding a `--theme=value` parameter sounds reasonable.

**Comment by sahinakkayadev** [comment] 2022-11-01 10:38
@bastimeyer  Thank you for the detailed response! You can't imagine how much your comment helped me. Because I do understand now why *some of* my apps does not follow system theme. I hope Chromium devs fix this so everybody can be happy.

**Comment by bastimeyer** [comment] 2022-11-01 17:03
I've just noticed after locally implementing this feature that there's a regression in NW.js which prevents this from being merged into master.

Apparently, recent NW.js versions don't fire the app's `open` event more than once anymore, which means that the theme could only be changed once during runtime.

Another big issue is that NW.js messes with the argument order when passing the argument string to the running process, and this breaks the argument parser. [I had already applied some custom fixes for that a long time ago](https://github.com/streamlink/streamlink-twitch-gui/blame/v2.2.0/src/app/nwjs/argv.js#L82-L130), but it looks like this workaround needs another update. I would much more prefer a real bugfix in NW.js.

So until at least the first issue gets fixed in NW.js, it doesn't make sense merging the `--theme` parameter feature. Let's leave this issue open, though.

I've opened a bug report on the NW.js repo here:
nwjs/nw.js#7991

**Comment by sahinakkayadev** [comment] 2022-11-01 17:13
>Another big issue is that NW.js messes with the argument order when passing the argument string to the running process, and this breaks the argument parser. [I had already applied some custom fixes for that a long time ago](https://github.com/streamlink/streamlink-twitch-gui/blame/v2.2.0/src/app/nwjs/argv.js#L82-L130)

@bastimeyer I actually examined those lines yesterday to find out if I can do something myself. I am aware that the argument order is not preserved. And the solution was to accept only one parameter at a time. Doesn't this work now? 

I don't know much JS, so don't get me wrong. I am asking this just out of curiousity :slightly_smiling_face:

**Comment by bastimeyer** [comment] 2022-11-01 17:21
> Doesn't this work now?

The workaround just needs a small update. As said, I would much rather prefer a real fix in NW.js instead of having to deal with this mess.

You can build from the [`feature/theme-parameter`](https://github.com/streamlink/streamlink-twitch-gui/compare/master...feature/theme-parameter) branch if you want, but as said, it won't be useful because of the `open` event which only triggers once.

**Comment by sahinakkaya** [comment] 2023-04-10 18:39
> But considering that https://bugs.chromium.org/p/chromium/issues/detail?id=998903 is still not resolved by the Chromium devs, adding a `--theme=value` parameter sounds reasonable.

Looks like it is fixed now. 🥳

When the patch comes, will theme switch work properly?

**Comment by bastimeyer** [comment] 2023-04-10 18:50
Yes, I'm already aware. Finally fixed in Chromium and all Chromium-based applications... :tada: 

CRBUG#998903 will be fixed in Chromium 114 though, which hasn't been released yet. Its stable release is 2023-05-30.
https://chromiumdash.appspot.com/schedule

After that, NW.js needs to be updated and a new version be release. Once that's out, I'll have to test that release before I'm able to bump the version here.
https://nwjs.io/blog/

And once that's done, I can merge the branch and close this issue.

I was thinking about publishing a new release in the coming days, since it's been a while, despite not many new features and bugfixes, but with this annoying issue finally being fixed in Chromium in the coming weeks, I will probably delay the release until that's done.

**Comment by bastimeyer** [comment] 2023-06-11 19:32
`master` now uses NW.js 0.77.0 (Chromium 114) with support for proper `prefers-color-scheme` CSS media query results on Linux.

I've also updated what I had pushed on the `feature/theme-parameter` branch. The command line string which gets passed to the running NW.js instance is still a total mess though, but I was able to apply a new workaround, so the theme can be overridden via the `--theme value` or `--theme=value` CLI argument. The branch is now merged into master and has been deleted.
https://github.com/streamlink/streamlink-twitch-gui/compare/d7619e7a4481630344215f2770197506e62b0a3d...984b8f591be4a6e5fe355b04b57143a18fbb09fa

Closing...

New Streamlink Twitch GUI release once the recent Streamlink issues around the integrity token have been resolved, which I've been working on the past couple of days.

**Closed by bastimeyer** 2023-06-11 19:32 UTC
Labels: feature request
