### ISSUE TITLE
Application randomly does not fully shut down, tray icon stays visible

### ISSUE THREAD

**Issue by Robby-** [streamlink/streamlink-twitch-gui#404] opened 2017-01-28 17:00 UTC
### Checklist
- [x] This is a bug report.
- [x] Streamlink is working correctly on my system without using the Twitch GUI.
- [x] I tried solving my issue by reading the project's wiki first.
- [x] I used the search function to find already opened/closed issues or pull requests.

### Description
When clicking the X to close the application, the main window disappears but the tray icon stays, the application doesn't actually fully shut down. `streamlink-twitch-gui.exe` is still in the task manager list and I have to manually end the process. Right clicking the tray icon while in this state still brings up the menu to pause notifications, toggle the window or close the app, but nothing actually works.

### Expected / Actual behavior
Expected behavior: The process should shut down cleanly.
Actual behavior: `streamlink-twitch-gui.exe` is still running in the background, also making it impossible to start a new instance again until it is forcefully shut down.

### Reproduction steps
1. Click the X to close the application.
2. Watch to see what it does, either it shuts down or it doesn't.

### Environment details (operating system, etc.)
OS: Windows 7 x64 SP1.
Application version: 1.1.1

### Comments, logs, screenshots, etc.
This bug is very random and not 100% reproducible, or at least I haven't figured out the sequence of events to force this to happen at will. It does happen frequently, however. This didn't used to happen with the 0.x versions, though I can't say for sure with what exact version this issue started popping up.

**Comment by bastimeyer** [comment] 2017-01-29 07:23
Duplicate of #396... Let me reopen this thread.
If you have more infos, please comment over there, thanks.

**Closed by bastimeyer** 2017-01-29 07:23 UTC
