### ISSUE TITLE
Missing git repositories on "npm install" and libudev update

### ISSUE THREAD

**Issue by Maliuta** [streamlink/streamlink-twitch-gui#486] opened 2017-07-07 10:04 UTC
When attempting to build streamlink-twitch-gui as per instructions there are two problems,

1) When checking out the "packages branch" an issue about [the now deprecated] libudev.so.0 file (should probably be able to deal with both libudev.so.1 and libudev.so.0):
`nikolai@donetsk:~/src/Streamlink/streamlink-twitch-gui$ git checkout origin/packages
Note: checking out 'origin/packages'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

  HEAD is now at be096c37... Add missing libudev.so.0 fix to deb/rpm postinst
  
`

2) When running 'npm install' there are several issues with missing github repositories:

`nikolai@donetsk:~/src/Streamlink/streamlink-twitch-gui$ npm install
npm ERR! git clone git@github.com:github:bastimeyer/grunt-webpack Cloning into bare repository '/home/nikolai/.npm/_git-remotes/git-github-com-github-bastimeyer-grunt-webpack-32d341a0'...
npm ERR! git clone git@github.com:github:bastimeyer/grunt-webpack X11 forwarding request failed on channel 1
npm ERR! git clone git@github.com:github:bastimeyer/grunt-webpack fatal: remote error: 
npm ERR! git clone git@github.com:github:bastimeyer/grunt-webpack    is not a valid repository name
npm ERR! git clone git@github.com:github:bastimeyer/grunt-webpack   Email support@github.com for help
npm ERR! notarget No compatible version found: grunt-webpack@'github:bastimeyer/grunt-webpack#plugins-grunt-template-fix'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.1.0","0.1.1","0.2.0","0.2.1","0.2.2","0.3.0","0.3.1","0.4.0","0.9.0","0.9.1","0.9.3","0.9.4","0.9.5","0.9.6","0.10.0","0.10.1","0.10.2","0.10.3","0.10.4","0.10.5","0.11.0","0.11.1","1.0.0","1.0.1","1.0.2","1.0.3","1.0.4","1.0.5","1.0.6","1.0.7","1.0.8","1.0.10","1.0.11","1.0.12","1.0.13","1.0.14","1.0.15","1.0.16","1.0.17","1.0.18","2.0.0-beta.1","2.0.0-beta.2","2.0.0-beta.3","2.0.0-beta.4","2.0.0-beta.5","2.0.0-beta.6","2.0.0","2.0.1","3.0.0-beta.1","3.0.0-beta.2","3.0.0"]
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! System Linux 4.11.8-donetsk
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/nikolai/src/Streamlink/streamlink-twitch-gui
npm ERR! node -v v4.8.3
npm ERR! npm -v 1.4.21
npm ERR! code ETARGET
npm ERR! git clone git@github.com:github:bastimeyer/snoretoast Cloning into bare repository '/home/nikolai/.npm/_git-remotes/git-github-com-github-bastimeyer-snoretoast-889ad094'...
npm ERR! git clone git@github.com:github:bastimeyer/snoretoast ControlSocket /run/user/1000/.ssh-nikolai-master-git@github.com:22 already exists, disabling multiplexing
npm ERR! git clone git@github.com:github:bastimeyer/snoretoast X11 forwarding request failed on channel 0
npm ERR! git clone git@github.com:github:bastimeyer/snoretoast fatal: remote error: 
npm ERR! git clone git@github.com:github:bastimeyer/snoretoast    is not a valid repository name
npm ERR! git clone git@github.com:github:bastimeyer/snoretoast   Email support@github.com for help
npm ERR! git clone git@github.com:github:bastimeyer/css-loader Cloning into bare repository '/home/nikolai/.npm/_git-remotes/git-github-com-github-bastimeyer-css-loader-1dbd6751'...
npm ERR! git clone git@github.com:github:bastimeyer/css-loader X11 forwarding request failed on channel 1
npm ERR! git clone git@github.com:github:bastimeyer/css-loader fatal: remote error: 
npm ERR! git clone git@github.com:github:bastimeyer/css-loader    is not a valid repository name
npm ERR! git clone git@github.com:github:bastimeyer/css-loader   Email support@github.com for help
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/nikolai/src/Streamlink/streamlink-twitch-gui/npm-debug.log
npm ERR! not ok code 0
`

O/S:             GNU/Linux
Distribution: Debian
Release:      Unstable/Sid

I was able to install streamlink from the Ubuntu ppa (using the xenial distribution name) after some messing around getting proper gpg keys for it.

I am attaching the full log produced by npm.

Tnanks

[npm-debug.log.txt](https://github.com/streamlink/streamlink-twitch-gui/files/1130667/npm-debug.log.txt)

**Comment by bastimeyer** [comment] 2017-07-07 12:04
The packages branch hasn't been updated since 2016-10-14, was rebased to the master branch again on 2017-03-16 and is still 123 commits behind. If you have any issues with this branch, you should comment in its dedicated pull request #319, although I should add that this branch is not intended for general use, since it's just meant for creating and testing both deb and rpm packages and setting up custom deb and rpm package repositories on bintray.com. See the PR for more infos...

If you want to build Streamlink Twitch GUI by yourself, you should build it off the master branch and follow the instructions of the [wiki](https://github.com/streamlink/streamlink-twitch-gui/wiki/Installation#linux-1).

Btw, the branch still builds perfectly fine. What's causing your issue is the ancient npm version you're using.
And regarding the libudev.so.0 fix, you're seeing the commit log of be096c3707547a66a4fa0f9d5c3ee3ae37db8a32 (HEAD of the packages branch), which just copies the libudev.so.0 fix from the regular start script to the postinst hooks of both packages (see [here](https://github.com/streamlink/streamlink-twitch-gui/blob/v1.3.1/build/resources/linux/start.sh#L25-L54)). This fix is needed because of NW.js on older Ubuntu versions. The newer NW.js builds (>=0.13.0) might not need this fix anymore, but I'm not sure about this and including it doesn't hurt.

**Comment by bastimeyer** [comment] 2017-07-12 17:31
Closing the thread now, since there hasn't been a response in a couple of days and the issue is caused by an old version of the used package manager (npm).

**Closed by bastimeyer** 2017-07-12 17:31 UTC
