### ISSUE TITLE
Livestreamer TLSv1 handshake error when launching streams

### ISSUE THREAD

**Issue by x1tko0** [streamlink/streamlink-twitch-gui#667] opened 2019-10-12 16:09 UTC
Hello, i have error since yesterday, here it is.

Found matching plugin twitch for URL twitch.tv/sypherpk
Attempting to authenticate using OAuth token
Unable to open URL: https://api.twitch.tv/kraken/user.json ([Errno 1] _ssl.c:504: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version)
Waiting for streams, retrying every 1.0 second(s)
Unable to open URL: https://api.twitch.tv/api/channels/sypherpk/access_token.json ([Errno 1] _ssl.c:504: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version)
Unable to open URL: https://api.twitch.tv/api/channels/sypherpk/access_token.json ([Errno 1] _ssl.c:504: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version)
Unable to open URL: https://api.twitch.tv/api/channels/sypherpk/access_token.json ([Errno 1] _ssl.c:504: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version)

What i need to do? (it's being with all streams, not only with this one)

**Comment by bastimeyer** [comment] 2019-10-12 16:36
You are using Livestreamer instead of Streamlink. This is not clear from the logs you've posted, but I know this since you're not the first one reporting this.

Livestreamer is dead since several years, hence the Streamlink fork in 2016 and the renaming of the Twitch GUI from Livestreamer Twitch GUI to Streamlink Twitch GUI.
https://github.com/streamlink/streamlink-twitch-gui#livestreamer-twitch-gui-has-been-renamed

**Install Streamlink** and change the streaming provider in the Twitch GUI's streaming settings menu back to `Streamlink` (or `Streamlink (Windows)` if you're using Windows).

The project's wiki has all the necessary informations regarding installation and configuration:
https://github.com/streamlink/streamlink-twitch-gui/wiki

Looks like it's time to finally remove Livestreamer support from the Twitch GUI.

**Comment by x1tko0** [comment] 2019-10-12 16:47
Installed last version and got this now https://service.crazypanda.ru/v/monosnap/2019-10-12-19-44-32-5ccpj.png

**Comment by bastimeyer** [comment] 2019-10-12 17:01
Did you set any custom settings in the Twitch GUI?

The "Unexpected version check output" error message means that the Twitch GUI did not receive a version string from Streamlink when validating its version. This is usually caused when there are Python error message being returned by the child process instead. And that is usually caused when the user has applied invalid settings like for example a wrong Python executable path for running the Streamlink entry script. This shouldn't be a problem at all though if you're a Windows user (which I guess you are) and are using Streamlink's Windows installer, because it is a standalone install with an integrated Python environment and standalone executable (called `streamlinkw`).

Since you didn't provide any further useful information, all I can tell you is to reset your configuration and do what is described in the wiki (which is usually not applying any custom settings at all, because the Twitch GUI is usually able to properly resolve Streamlink and use the right configuration out of the box).

If the error message keeps popping up, please use the search function on the issue tracker, as there will be enough threads with informations on how to resolve this. This shouldn't be necessary though. And yes, as I've explained it several times in these other threads, I'm aware that the error message is not particularly user-friendly and that it needs to be changed. If everything else fails, please provide the error log from the most recent log file:
https://github.com/streamlink/streamlink-twitch-gui/wiki/Parameters#--loglevel--l

**Comment by x1tko0** [comment] 2019-10-12 17:04
Yes, im windows user, yes, i didnt customize any custom settings, i just downloaded latest version of twitch gui, and yes, i just did streamlink (Windows) in settings.

**Comment by bastimeyer** [comment] 2019-10-12 17:11
> i just downloaded latest version of twitch gui

You are supposed to download and install the latest **Streamlink** version, not **Streamlink Twitch GUI** (you should be using the latest version anyway).

**Streamlink** (command line interface application) is a dependency of **Streamlink Twitch GUI** (graphical user interface frontend).
https://github.com/streamlink/streamlink-twitch-gui#description
https://github.com/streamlink/streamlink-twitch-gui#download

**Comment by x1tko0** [comment] 2019-10-12 17:26
I did, installed both of it..

**Comment by x1tko0** [comment] 2019-10-12 17:51
What i need to change, when those settings are simple, and nothing helps me to play streams.. i dont understand what i should even change..

**Comment by melloman33** [comment] 2019-10-12 19:08
I've installed the latest streamlink. And pathed it to streamlinkw.exe, which for me is "C:\Users\Admin\AppData\Local\Streamlink\bin\streamlinkw.exe". 

And now I get this in the launch popup when launching now: 

"spawn C:\Users\Admin\AppData\Local\Streamlink\bin\streamlinkw.exe EACCESS "

Suggestions?

**Comment by bastimeyer** [comment] 2019-10-12 19:36
> spawn EACCESS

Streamlink Twitch GUI doesn't seem to have read or execution access for running the `streamlinkw.exe` executable on your system. You need to fix the file permissions. The Windows installer of Streamlink offers you two installation methods, a user-specific one and system-wide one. I am not a Windows user and am not very well acquainted with its permission system, but it looks like you've installed it with your system's administrator account, at least if I'm interpreting it correctly from the path of the executable you've posted (`C:\Users\Admin`), and now the Twitch GUI is unable to access it.

**Comment by melloman33** [comment] 2019-10-12 20:52
Confirmed that installing "for all users" resolved that error. 

Hey bastimeyer, if you dont mind me sharing. I came up with a little guide for the technically inept trying to transition from livestreamer. I'm sure there's a whole lot, because I used livestreamer for many years since after the transition period. 

** Why aren't my streams launching anymore? Easy Instructions for going from using livestreamer for Twitch GUI to using Streamlink for Twitch GUI!**!


1. Install latest Streamlink-GUI according to your system (32 or 64 depending, you can find this in system in control panel)

2. Download _**Streamlink itself,**_ which connects to the GUI and enables you to connect, by searching for it on Github. 

It will be version "1.2.0". 

3. Installing Streamlink: 

After downloading Streamlink, you will get a little blue file which is your installation file you'll need to install streamlink with. It is not an exe file! It is of no use with Streamlink GUI by itself!

STEP BY STEP AFTER DOUBLE CLICKING THE INSTALLATION FILE: 

Make sure it is set to "install for all users". 

Make sure to install to the DEFAULT path (dont change the installation path!)

Then just let it install, and close out. 

And with that you're done on the download/installation for streamlink+ S-GUI.

4. Now go into streamlinkGUI and get into the settings (to the gear top right). 

Click Streaming, third tab on the top. 

Go to streamlink/livestreamer, and select the streamlink (Windows) option from the arrow drop down selection. 

5. Right under there, in "streamlink executable"

It will have "streamlinkw.exe" in grey text. 

Click it to change it, and copy and paste the following verbatim into that bar:

----------

C:\Program Files (x86)\Streamlink\bin\streamlinkw.exe

----------

Now go to the bottom of the page, and hit the green save button. 

You can now launch streams!

Note: If this fails you may have a different path to find on your PC to put into the bar. NO PROBLEM!  

It's always going to be in the installed streamlink folder, and within that folder it will be inside the **bin** folder and it will be called "streamlinkw.exe". So when you're in that folder, to create your path, just end it with streamlinkw.exe. And then backtracking, put "\" for each folder step backwards all the way to C:. And whatever that is for you, paste it and it will work! 

6. Enjoy streamlink with Twitch Gui!

**Comment by x1tko0** [comment] 2019-10-12 21:11
> Confirmed that installing "for all users" resolved that error.
> 
> Hey bastimeyer, if you dont mind me sharing. I came up with a little guide for the technically inept trying to transition from livestreamer. I'm sure there's a whole lot, because I used livestreamer for many years since after the transition period.
> 
> ** Why aren't my streams launching anymore? Easy Instructions for going from using livestreamer for Twitch GUI to using Streamlink for Twitch GUI!**!
> 
> 1. Install latest Streamlink-GUI according to your system (32 or 64 depending, you can find this in system in control panel)
> 2. Download _**Streamlink itself,**_ which connects to the GUI and enables you to connect, by searching for it on Github.
> 
> It will be version "1.2.0".
> 
> 1. Installing Streamlink:
> 
> After downloading Streamlink, you will get a little blue file which is your installation file you'll need to install streamlink with. It is not an exe file! It is of no use with Streamlink GUI by itself!
> 
> STEP BY STEP AFTER DOUBLE CLICKING THE INSTALLATION FILE:
> 
> Make sure it is set to "install for all users".
> 
> Make sure to install to the DEFAULT path (dont change the installation path!)
> 
> Then just let it install, and close out.
> 
> And with that you're done on the download/installation for streamlink+ S-GUI.
> 
> 1. Now go into streamlinkGUI and get into the settings (to the gear top right).
> 
> Click Streaming, third tab on the top.
> 
> Go to streamlink/livestreamer, and select the streamlink (Windows) option from the arrow drop down selection.
> 
> 1. Right under there, in "streamlink executable"
> 
> It will have "streamlinkw.exe" in grey text.
> 
> Click it to change it, and copy and paste the following verbatim into that bar:
> 
> C:\Program Files (x86)\Streamlink\bin\streamlinkw.exe
> 
> Now go to the bottom of the page, and hit the green save button.
> 
> You can now launch streams!
> 
> Note: If this fails you may have a different path to find on your PC to put into the bar. NO PROBLEM!
> 
> It's always going to be in the installed streamlink folder, and within that folder it will be inside the **bin** folder and it will be called "streamlinkw.exe". So when you're in that folder, to create your path, just end it with streamlinkw.exe. And then backtracking, put \ for each folder step backwards all the way to C: And whatever that is for you, paste it and it will work!
> 
> 1. Enjoy streamlink with Twitch Gui!

TY SO MUCH! C:\Program Files (x86)\Streamlink\bin\streamlinkw.exe - this link helps me, coz it was diffrent path! Good luck, bro!

**Comment by bastimeyer** [comment] 2019-10-12 21:23
Glar to hear you both were able to resolve your problems.
Let's keep this thread open though for a couple of days, so we don't get more unnecessary duplicates.

**Comment by exradioactivetoy** [comment] 2019-10-13 16:07
Hello guys
i have the same problem like a x1tko0, but, when iam installing a new version its not running, in application window displayed just a black square, like this -
[https://ibb.co/L1kM1pM](url)

**Comment by bastimeyer** [comment] 2019-10-14 00:52
@exradioactivetoy 
This is an entirely different issue. Probably related to https://github.com/streamlink/streamlink-twitch-gui/issues/663#issuecomment-535221850.
Please clear the application's config/cache folder in `%LOCALAPPDATA%\streamlink-twitch-gui` and try again. If the problem persists, please open a new issue and fill in the necessary details into the template. Please also provide an error log if possible by launching Streamlink Twitch GUI with the `--enable-logging --v=1` parameters (after clearing the config/cache folder). A log file will then be placed into that cleared and rebuilt config/cache folder. Thanks!

----

I will also remove support for Livestreamer from the app once I get the time, as Livestreamer's last Windows-standalone release is non-functional now with the disabling of TLSv1 on Twitch's end. I don't expect anyone on other OSes to be reliant on Livestreamer, since packages of Streamlink exist (almost) everywhere where Livestreamer has been.

Btw, the reason why many people were still using Livestreamer while using the Twitch GUI is the existence of 3rd party guides on Youtube and the likes, which are either outdated or have been wrong in the first place by pointing users to Livestreamer instead of Streamlink. As a reminder for people blindly following 3rd party (video) guides (for any kind of software): don't do that and instead follow the official guides/documentation, so you don't have to run into unnecessary issues.

----

I'm going to lock this thread now, as it's all off-topic discussion now and the original issue has already been solved by the first comment.

**Comment by bastimeyer** [comment] 2019-11-13 16:08
Closing the thread now since the removal of livestreamer has been merged in c341133.
The documentation and other stuff will be changed before the next release gets published.

**Closed by bastimeyer** 2019-11-13 16:08 UTC
Labels: livestreamer
