### ISSUE TITLE
Streams randomly breaking down without the GUI noticing

### ISSUE THREAD

**Issue by sfkpmr** [streamlink/streamlink-twitch-gui#425] opened 2017-03-20 20:09 UTC
### Checklist

- [x] This is a bug report.
- [ ] Streamlink is working correctly on my system without using the Twitch GUI.
- [x] I tried solving my issue by reading the project's wiki first.
- [x] I used the search function to find already opened/closed issues or pull requests.

### Description

For the past month or so I've noticed that streams are randomly stopping. VLC just goes black. 

It happens daily, with all kinds of streams.

I never had the issue with the Livestreamer version, but I can't say if this started immediately after the switch. I've also updated this edition a few times since the switch.

Recently I also noticed that if the stream dies, and I go to restart it, the GUI seems to think that the stream is still going, and instead of launching the stream again, lists the channel info.

### Reproduction steps

Start stream, wait. There is no obvious pattern to how soon it will happen, and streams mostly run for hours without issues.

### Environment details (operating system, etc.)

Win 7 SP1 x64, VLC 2.2.4, Streamlink-Twitch-GUI 1.2.0.

### Comments, logs, screenshots, etc.

Found another issue which mentioned logging with --enable-logging --v=1, but I couldn't get that to work.

With the logs I might at least be able to eliminate the error source being Twitch or Streamlink.

**Comment by bastimeyer** [comment] 2017-03-20 20:24
> the GUI seems to think that the stream is still going

Is the streamlink child process still running? As long as the child process is still running, streams are being marked as being watched. Closing the player window or closing the stream via the popup in the GUI will kill the process.

> VLC just goes black

What do you mean exactly? Is there still a stream input or has the playback stopped?
You are not using the VLC player preset, are you? What I mean is the `--play-and-exit` VLC param that allows Streamlink to close VLC, so that no empty player window is left behind when a stream stops.
https://github.com/streamlink/streamlink-twitch-gui/wiki/Player-configuration

The issue you're describing sounds more like a Streamlink related issue rather than Streamlink Twitch GUI. The GUI is just a launcher, nothing more. You should try to isolate the issue by just using the Streamlink CLI.

**Comment by sfkpmr** [comment] 2017-03-20 20:47
>streamlink child process

If you're referring to the streamlink-twitch-gui.exe processes, then I believe so, I'll double check next time it happens. Seeing 4 with now streams running, is that expected?

>black

Black as in it looks exactly like it does when you launch VLC directly and don't play anything.

I can't even find the --play-and-exit parameter in the config file, should I just add it on a new line?

>CLI

You mean streaming manually through CMD?

Does the GUI generate any logs, or should I be looking for Streamlink's logs?

**Comment by bastimeyer** [comment] 2017-03-20 21:00
> streamlink-twitch-gui.exe

No, these are all NW.js/Chromium processes. I'm talking about the python child processes when launching streams via streamlink.

> Does the GUI generate any logs

No, and it wasn't necessary until recently when NW.js builds were split up between SDK and normal (with and without dev tools). I'll see if I can add a logging system in one of the next releases.

You can get detailed log infos by using this cmd line:
```sh
streamlink -v -l debug -p /path/to/vlc --player-passthrough http twitch.tv/CHANNEL QUALITY
```
As soon as a stream randomly drops, you should be able to know why.

**Comment by sfkpmr** [comment] 2017-03-20 21:10
You mean pythonw.exe? Running, and will check next time.

Thanks!

**Comment by sfkpmr** [comment] 2017-03-22 18:46
Looks like a Streamlink or Twitch issue.

[cli][info] Opening stream: 720p60 (hls)
[cli][info] Starting player: "C:\Program Files (x86)\VideoLAN\VLC\vlc.exe"
[stream.hls][warning] Failed to reload playlist: Unable to open URL: https://vid
eo-edge-c2a548.arn03.hls.ttvnw.net/v0/CtcBnxSlJG9nFL9SKomIY5PJf6XumqhviK9tGbA15J
gpPgQKMJKk-o4CcHCHdpgGssHthacZEsDtRy1quKjjWc9L-uRdnjhh7DtiRzcdB1HO88VPomMI5huRFp
uCRzHgszX20aZC6U31Z7c_2KuctmWPv4mRNuMV7eXgmmL4W8r0yn9UzlFrDIntje4TxyLuqLE4Vt8t4o
AxStecnZ-MqwYLVU-SusxBG0oUPrCmyJeTAETDiyec9bYW9oFc35MJD2_yLJ85JeaFSyyE1W-dCLC_04
mFTYVsTwMSEAN5GEo3SJoP0HsYEm_CVhwaDHXn26JQ6HG_TDNnOA/index-live.m3u8 (('Connecti
on aborted.', ConnectionResetError(10054, 'An existing connection was forcibly c
losed by the remote host', None, 10054, None)))
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Streamlink\pkgs\requests\packages\urllib3\respons
e.py", line 298, in _error_catcher
    yield
  File "C:\Program Files (x86)\Streamlink\pkgs\requests\packages\urllib3\respons
e.py", line 380, in read
    data = self._fp.read(amt)
  File "http\client.py", line 448, in read
  File "http\client.py", line 488, in readinto
  File "socket.py", line 575, in readinto
  File "ssl.py", line 929, in recv_into
  File "ssl.py", line 791, in read
  File "ssl.py", line 575, in read
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Streamlink\pkgs\requests\models.py", line 703, in
 generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "C:\Program Files (x86)\Streamlink\pkgs\requests\packages\urllib3\respons
e.py", line 432, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "C:\Program Files (x86)\Streamlink\pkgs\requests\packages\urllib3\respons
e.py", line 397, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "contextlib.py", line 77, in __exit__
  File "C:\Program Files (x86)\Streamlink\pkgs\requests\packages\urllib3\respons
e.py", line 303, in _error_catcher
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host=
'video-edge-c2a548.arn03.hls.ttvnw.net', port=443): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 914, in _bootstrap_inner
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\stream\segmented.py",
line 160, in run
    self.write(segment, result)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\stream\hls.py", line 1
11, in write
    for chunk in res.iter_content(chunk_size):
  File "C:\Program Files (x86)\Streamlink\pkgs\requests\models.py", line 710, in
 generate
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='video-edge-c2a548
.arn03.hls.ttvnw.net', port=443): Read timed out.

[cli][error] Error when reading from stream: Read timeout
[cli][info] Stream ended

**Comment by bastimeyer** [comment] 2017-03-22 19:53
As you can see in the log, Streamlink was unable to reload the hls stream playlist, which is either caused by your connection to the Twitch servers or by the servers themselves. Streamlink shouldn't be throwing an exception, though. You should open another issue on the Streamlink repo with this log.

Please close the issue if you don't have anything more to add, otherwise I'll close it later on.

**Closed** 2017-03-22 21:49 UTC
Labels: streamlink, unrelated
