### ISSUE TITLE
Can't install while VLC ist installed

### ISSUE THREAD

**Issue by anga83** [streamlink/streamlink-twitch-gui#419] opened 2017-03-05 12:16 UTC
Hi there!
I've tried multiple times to install streamlink-twich-gui. Every time it ends up with
`Error: It seems there is already an App at '/Applications/VLC.app'.
Error: nothing to install`

I mean, I could uninstall VLC in first place, than install the package but why is there this "error" message? Since it will need VLC it could easily check if it is already installed and than skip this part, instead of returning an error.

Homebrew and cask are installed and up to date.
I'm running on macOS 10.12.3

----
- [x] This is a bug report.
- [x] Streamlink is working correctly on my system without using the Twitch GUI.

**Comment by bastimeyer** [comment] 2017-03-05 13:01
I'm not the maintainer/initiator of the streamlink-twitch-gui homebrew cask, but somehow VLC is set as a non-optional cask dependency:
https://github.com/caskroom/homebrew-cask/blob/master/Casks/streamlink-twitch-gui.rb

I'm not sure why you're getting this error, though. You can use the `--ignore-dependencies` parameter to install casks without their installing dependencies. Since VLC is listed as the only dependency, there will be no issues when doing so.

Maybe the cask should be updated when the next release gets published. Unfortunately, I don't know how to set the dependencies as optional.
https://github.com/caskroom/homebrew-cask/blame/master/Casks/streamlink-twitch-gui.rb

Pinging @miccal (renamed the old Livestreamer Twitch GUI cask) and @victorpopkov (committed the last upgrade), maybe one of them can help. Thanks.

**Comment by bastimeyer** [comment] 2017-03-28 16:23
Closing the thread since it's unrelated to Streamlink Twitch GUI itself and may be caused by a homebrew bug or system misconfiguration. If the issue persists, please open an issue on the homebrew issue tracker.

**Closed by bastimeyer** 2017-03-28 16:23 UTC
Labels: MacOS, packaging / updates
