### ISSUE TITLE
Followed channel list is empty despite having follow channels

### ISSUE THREAD

**Issue by bobvargas** [streamlink/streamlink-twitch-gui#769] opened 2020-12-27 12:15 UTC
## Bug report

- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] This is a bug report and I have read the contribution guidelines.

### Environment details

**Operating system and version:**  

**Streamlink Twitch GUI version:**  
 v1.11.0

**Streamlink version:**  

**Configuration details:**  

Windows 7 SP1

### Expected / Actual behavior

When I clicked on followed channel list sometimes when you unfollowed channels if would have are less channels to show up
### Reproduction steps

1. ...
2. ...
3. ...

### Log output

```
[2020-12-14T16:42:20.682Z][error][StreamingService]
Error: usage: streamlink [OPTIONS] <URL> [STREAM]
```

**Comment by bastimeyer** [comment] 2020-12-27 12:27
> Followed channel list is empty despite having follow channels

Nope, the followed channels list is not empty (unless you've got a bad response from the Twitch API, which can happen from time to time). I definitely can't confirm this and everything's working as intended.

> When I clicked on followed channel list sometimes when you unfollowed channels if would have are less channels to show up

Following and unfollowing channels is working correctly as well. Check if you have unknowingly changed the sort method and/or order of the followed channels list on the top-right menu. If it's not sorted by following date in descending order, then the followed channel list won't of course include any recent changes at the top.

----

I'm going to close this thread. You can try the latest debug release (see the readme) and check the API responses when browsing the followed channels. If you can show me that there's definitely an issue, you can reopen the thread.

**Closed by bastimeyer** 2020-12-27 12:27 UTC
