### ISSUE TITLE
Request: Additional hotkey for history navigation

### ISSUE THREAD

**Issue by Dgc2002** [streamlink/streamlink-twitch-gui#492] opened 2017-07-25 18:53 UTC
Currently in order to go forwards/backwards in the navigation history we need to use the arrows in the top bar of the GUI:  
  

![image](https://user-images.githubusercontent.com/3957791/28588484-5ac094a6-7140-11e7-9a70-5b6a415e223b.png)
  
In previous versions it was possible to use backspace to navigate backwards, but this is no longer the case. Using the forward/backward buttons found on many mice would be desirable as well.

**Comment by bastimeyer** [comment] 2017-07-26 16:47
Sorry for the late response, I haven't had time yesterday to answer.

To go back and forth in the browsing history, you can use the [`Alt+Left` / `Alt+Right`](https://github.com/streamlink/streamlink-twitch-gui/blob/v1.3.1/src/app/components/MainMenuComponent.js#L58-L73) hotkeys.

The forward and backward mouse buttons can't be used, because they are officially not part of the [DOM mouse events specification](https://w3c.github.io/uievents/#dom-mouseevent-buttons) and Chromium (and NW.js) doesn't use them, which means that they can't be used here. See #382 or the other linked threads...
Btw, the Spotify desktop client also has the same problem, because it is based on Chromium as well.

The backspace button has been changed in one of the recent Chromium versions and it doesn't have its go-back action anymore:
https://www.independent.co.uk/life-style/gadgets-and-tech/news/google-chrome-stop-backspace-being-as-back-button-saving-people-from-accidentally-deleting-a7038281.html
This could be re-added here, but I don't think that it would be a wise decision. Going one step back by pressing backspace is an unexpected behavior IMO.

**Comment by Dgc2002** [comment] 2017-07-26 17:10
Whoops, sorry I searched the issues for all the wrong keywords apparently.  
  
I remember backspace being removed in Chromium but I'd forgotten that I added an extension to re-add the functionality. The alt combinations are useful but I think the real strength of the backspace behavior was just the one handed, one key interface. Alt + arrow keys either requires two hands(left alt) or one hand in a really awkward position(right alt).  
  
This also requires moving your hand off the mouse which is used for most other interactions in the GUI at the moment. While it's obviously a small inconvenience in the grand scheme of things, it's a general interface annoyance IMO.  
  
Regarding the mouse events you linked. It notes that additional buttons are represented as a bit mask. 4 represents what most people call mouse 3(middle button.) Wouldn't 8 and 16 be mouse 4 and 5, which are the standard forward/backward navigation buttons? Otherwise it seems kind of strange to even mention that there. Though, I'm unfamiliar with working in the CEF.

**Comment by bastimeyer** [comment] 2017-07-26 17:33
Chromium simply doesn't use mouse buttons 4+5 (mapped as the 8th and 16th bit). You can check it yourself: open Chromium's dev tools, set event breakpoints for all mouse button related DOM events (in the "Sources" tab) and try to use mouse button 4 or 5. It's unsupported, unfortunately.
The Chromium Extension API included in NW.js also doesn't allow listening to these buttons:
https://developer.chrome.com/extensions/input_ime#type-MouseButton
So neither DOM events, nor CE input events can be used. NW.js also doesn't provide any additional mouse API.

Regarding the Alt+arrow hotkeys, AFAIK, these are the only default hotkeys for navigating the browsing history, which is the reason why they were added here. I understand that it's an annoyance that you need both hands, but re-adding the backspace function that was deliberately removed by the Chromium devs (for good reasons) doesn't seem like a good idea to me.

**Comment by moznr** [comment] 2017-07-30 00:12
This is something that annoyed me too, but as a workaround I just use an autohotkey script. 

`#IfWinActive Streamlink Twitch GUI

XButton1::Send, !{Left}
XButton2::Send, !{Right}`

**Comment by bastimeyer** [comment] 2017-10-26 19:51
Closing this, since there's nothing which can be done here to add mouse 4+5 button actions...

**Comment by bastimeyer** [comment] 2018-04-18 18:44
Reopening the thread since this seems to be finally available in Chromium 67:
https://www.chromestatus.com/features/5088301178421248

Chromium 67 is still in the "dev" channel, which means that it is not included in any NW.js release yet. The next Chromium release channel shift is in one or two weeks.
https://www.chromestatus.com/features/schedule

The NW.js releases usually happen on the same day as the Chromium releases...
https://nwjs.io/blog/

**Comment by Dgc2002** [comment] 2018-04-18 19:16
Oh baby. Chrome has a habit of teasing me with 'next version' features but this is something else!  
  
Thanks for keeping this request in mind!

**Comment by bastimeyer** [comment] 2018-04-18 19:34
It's been requested many times before (#382, #242, #180, #85)... 
I was just browsing the new features of Chromium because I'm intending to upgrade to a more recent NW.js version in the next release, so yeah, ofc I'll reopen one of these threads.

This Chromium feature will finally benefit all NW.js-, Electron- or regular Chromium embedded framework applications like Spotify, etc. Just took them a few years :smile:

**Comment by bastimeyer** [comment] 2018-05-07 09:50
NW.js `0.31.0-beta.1` has been released today with Chromium 67.

You can build the app from the [`nwjs-0.31`](https://github.com/streamlink/streamlink-twitch-gui/tree/nwjs-0.31) branch and test the changes.
https://github.com/streamlink/streamlink-twitch-gui/blob/master/CONTRIBUTING.md#developing-and-building
The branch will be merged into `master` once NW.js 0.31 has been fully released.

**Closed** 2019-02-10 05:17 UTC
Labels: feature request
