### ISSUE TITLE
Missing streamlink-script.py on Windows

### ISSUE THREAD

**Issue by canadianhero** [streamlink/streamlink-twitch-gui#618] opened 2019-02-14 21:53 UTC
## Bug report

- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] This is a bug report and I have read the contribution guidelines.

### Environment details

**Operating system and version:**  
Windows 10, all updates except the October update

**Streamlink Twitch GUI version:**  
https://github.com/streamlink/streamlink-twitch-gui/releases/download/v1.6.0/streamlink-twitch-gui-v1.6.0-win64-installer.exe

**Streamlink version:**  
https://github.com/streamlink/streamlink/releases/download/1.0.0/streamlink-1.0.0.exe

**Configuration details:**  

### Description

i have tried to get this to work for about 2 hours last night, Feb 13 2019, i tried uninstalling and deleting all of the appdata to reset it, i have download both the 64bit and the 1.0.0 of the streamlink and the streamlink twitch gui and i did my best to follow the rules but i keep getting streamlink misconfiguration couldn't find pything script. i have no idea where to go. and i followed the wiki but none of it made sense to me. tried following youtubers but no one seems to get the same issue i do with this. oh also i just let them install where ever they want too

### Expected / Actual behavior

I expect to stream, i can't

### Reproduction steps

1. ... click on stream

### Log output

```
REPLACE THIS TEXT WITH THE LOG OUTPUT
```

**Comment by bastimeyer** [comment] 2019-02-14 22:02
That's caused by a recent packaging change in the Windows installer of Streamlink which is causing issues in the Twitch GUI. I'm still searching for a proper solution to this that's not a cheap workaround. It's not that simple, unfortunately.

**For now, you'll have to fix this yourself by choosing the `streamlink.exe` file from the installer's `bin` subdirectory as the intended `streamlink-script.py` and selecting the included `pythonw.exe` file (notice the `w`) from the `Python` subdirectory.**

More infos here:
https://github.com/streamlink/streamlink/issues/2287

Let me pin this thread to the top, so everyone on Windows can see it. Sorry for the inconveniences.

**Comment by canadianhero** [comment] 2019-02-14 22:06
thank you so much for the fast reply!! and ill try this out

**Comment by bastimeyer** [comment] 2019-02-21 13:43
Let me post a quick update on this matter:

I've submitted a patch with a new build feature to `pynsist`, the library Streamlink is using to build the Windows installer. This hasn't been reviewed (and merged) yet, so I'm still waiting for that to happen. If it gets merged, Streamlink will be able to build a secondary executable which the Twitch GUI can then use in a new resolver config and everything should continue to work OOTB again on Windows.

- [x] Submit a pull request to `pynsist` which makes it possible to build "noconsole" command launchers
- [ ] Pull request gets merged or similar feature gets implemented
- [ ] New `pynsist` release
- [ ] Submit a pull request to `streamlink` which uses this new `pynsist` "noconsole" feature and also adds a "GUI" ("noconsole") launcher to installs via `pip`, which works exactly the same
- [ ] Publish new streamlink release (either `1.0.1` or `1.1.0`)
- [ ] Add new "streamlink standalone" resolver config to the Twitch GUI, similar to the "livestreamer standalone" one
- [ ] Bump Streamlink version requirement in the Twitch GUI from `0.2.0` to the new version
- [ ] Publish a new Streamlink Twitch GUI release

**Comment by knasen88** [comment] 2019-03-20 20:21
Am I missing something here? There is NO such file/folder in my streamlink folder.

https://i.imgur.com/KM4WNOT.png

**Comment by bastimeyer** [comment] 2019-03-20 20:38
This is your **Streamlink Twitch GUI** folder and not your **Streamlink** folder

> Streamlink Twitch GUI
> A graphical user interface on top of the Streamlink command line interface.

https://github.com/streamlink/streamlink-twitch-gui#description
https://github.com/streamlink/streamlink-twitch-gui/wiki/Installation
https://github.com/streamlink/streamlink-twitch-gui/wiki/Streamlink-configuration

**Comment by knasen88** [comment] 2019-03-20 20:52
right.. me renaming it made me confused, thanks!

**Comment by bastimeyer** [comment] 2019-04-05 12:14
v1.7.0 has just been released:
https://github.com/streamlink/streamlink-twitch-gui/releases/latest

You will have to upgrade to the latest Streamlink release and manually choose the `Streamlink (Windows)` provider in the streaming settings menu if you've previously used Streamlink Twitch GUI. This provider is the new default on Windows and will be selected automatically on new installs (clean config folder).

I will keep this thread open for a while, though.

**Comment by bastimeyer** [comment] 2019-04-12 16:58
Closing, as it's been a week since 1.7.0 and everyone already had the chance to upgrade by now who could possibly run into this issue.

**Closed by bastimeyer** 2019-04-12 16:59 UTC
Labels: Windows, configuration, fixed, streamlink
