### ISSUE TITLE
stopped working

### ISSUE THREAD

**Issue by bluedagger** [streamlink/streamlink-twitch-gui#487] opened 2017-07-10 20:38 UTC
![zulxhuz 1](https://user-images.githubusercontent.com/30058010/28038849-8e089cf4-65c0-11e7-91ce-ea0e5fe1d680.png)
http://i.imgur.com/zulXHUz.png

**Comment by bastimeyer** [comment] 2017-07-11 07:46
A little bit more info would really be appreciated instead of just posting a screenshot of a generic NW.js error message. This makes it very difficult for me to work with these kind of "bug reports". The only reason why I can identify this as an issue related to Streamlink Twitch GUI is the v0.21.6 version of NW.js that's included in the screenshot, because it's currently being used here as well. This could also be interpreted a regular NW.js "bug report", but posted in the wrong issue tracker.

> Profile error occured

Please make sure that your Streamlink Twitch GUI installation, as well as your cache and config folders are not corrupted. The cache and config folders are located in the `%LOCALAPPDATA%` folder on Windows. You should try to delete them before re-downloading and re-installing the app. Please also make sure that your downloaded files are not corruped before re-installing. See the checksums file attached to the release page for a comparison.

**Comment by bastimeyer** [comment] 2017-07-12 17:28
Closing the thread, since it's a NW.js related issue with a corrupted user profile or application cache.
In a clean environment, the program works as intended.

**Closed by bastimeyer** 2017-07-12 17:28 UTC

**Comment by bluedagger** [comment] 2017-07-12 21:17
yeah it was my environment variables that wasnt set properly.
had to reset the path to the temp folder to an existing drive
