### ISSUE TITLE
"Streams" tab can present visual glitches on some environments

### ISSUE THREAD

**Issue by Porkepix** [streamlink/streamlink-twitch-gui#956] opened 2023-03-07 18:39 UTC
### Checklist

- [X] I understand that **Streamlink Twitch GUI** is just a launcher for **Streamlink**
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink-twitch-gui/blob/master/CONTRIBUTING.md)
- [X] [I have checked the list of open and recently closed issues](https://github.com/streamlink/streamlink-twitch-gui/issues?q=is%3Aissue+sort%3Aupdated-desc)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink-twitch-gui/commits/master)

### Streamlink Twitch GUI version

2.2.0

### Streamlink version

5.3.1

### Operating system, environment and configuration details

ArchLinux, Gnome and Wayland

### Description

The "Streams" tab can present very weird visual glitches around texts. Check for example second line, 3rd, 4th and 6th stream on top, or 3rd line, second to 4th streams at the bottom on the joined screenshot.
Note that these glitches move to different streams when I move my cursor and hover different thumbnails.

What's to add to this is that with two computers running a similar setup (Arch, Gnome and Wayland on both), only one of them experience those glitches, so the obvious reason that comes to mind is the different GPU (Intel Iris Xe), but Streamlink Twitch GUI is the absolute only software to present such glitches, no other software shows such glitches.

<details>
<summary>Screenshot</summary>

![Screenshot from 2023-03-01 00-11-45](https://user-images.githubusercontent.com/709500/223518358-91f72903-59a7-470f-8651-a4a2259728a2.png)

</details>

**Comment by bastimeyer** [comment] 2023-03-07 20:17
This has nothing to do with the "Streams" menu or anything else in the application code. It's a Chromium rendering issue on your system.

The NW.js version of the latest release `v2.2.0` is `0.68.1`, which is based on Chromium `105.0.5195.102` from September 2022.

> the obvious reason that comes to mind is the different GPU (Intel Iris Xe)

Well, there's your answer.

----

I will have a look at updating NW.js to `0.72.0` with Chromium `109.x` in the next release (which still supports Win7, so these users will have a last version of STG that's still supported there), but the chance that this will resolve any rendering issues for certain GPUs is rather slim.

Closing the thread, as it's an upstream issue with your particular system. You can try to force software rendering if the issue makes using the application too difficult for you.

- https://github.com/streamlink/streamlink-twitch-gui/wiki/Parameters#nwjs--chromium-parameters
- https://peter.sh/experiments/chromium-command-line-switches/#disable-gpu
- https://peter.sh/experiments/chromium-command-line-switches/#disable-gpu-rasterization
- https://wiki.archlinux.org/title/Chromium

**Closed by bastimeyer** 2023-03-07 20:17 UTC
Labels: os: Linux, platform issue, upstream

**Comment by Porkepix** [comment] 2023-03-07 20:19
If the issue would come from Chromium though, shouldn't Electron applications also be affected, for example?
Also, why in the case of Streamlink Twitch GUI, this tab is the only one ever presenting such glitches? None appeared anywhere else.

**Comment by bastimeyer** [comment] 2023-03-07 20:19
https://gitlab.freedesktop.org/mesa/mesa/-/issues/?search=chromium&sort=updated_desc&state=all&label_name%5B%5D=iris

**Comment by bastimeyer** [comment] 2023-03-07 20:23
> If the issue would come from Chromium though, shouldn't Electron applications also be affected, for example?

This depends on the Chromium build, which I don't have any control over here.

> why in the case of Streamlink Twitch GUI, this tab is the only one ever presenting such glitches? None appeared anywhere else.

This may be caused by the animation when loading the menu with lots of stream items. All these stream components include transparent backgrounds and other stuff, so there's a chance that your intel GPU drivers are bugging out here.

As said, this is nothing that can be fixed here, even if it's only an issue with the Chromium builds of NW.js.

**Comment by Porkepix** [comment] 2023-03-07 20:31
Yep, was expecting nothing was possible here, but it was worth a report for the record imho, and thanks for the pointers.
A couple of weeks ago when trying another compositor I also noticed the software to behave very weirdly in this tiling environment defaulting to more than 100% DPI scale, and I expect it to be the same: something that only falls upon the platform used (NW.js).
