### ISSUE TITLE
[macOS Mojave] Extreme freeze when opening app or stream (~1s)

### ISSUE THREAD

**Issue by adityakaulagi** [streamlink/streamlink-twitch-gui#717] opened 2020-04-26 09:35 UTC
## Bug report

- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] This is a bug report and I have read the contribution guidelines.

### Environment details

**Operating system and version:**  
macOS 10.14.6 

**Streamlink Twitch GUI version:**  
1.9.1

**Streamlink version:**  
1.3.1

**Configuration details:**  
Added `http-no-ssl-verify` to `.streamlinkrc`.

### Description

Streamlink freezes the entire OS GUI for 1-2s while starting up or opening stream. I cannot use any other program while these actions complete.

### Expected / Actual behavior

Using streamlink does not freeze the whole OS.

### Reproduction steps

1. Start Streamlink Twitch GUI
2. OS freezes for 1-2s

**Comment by bastimeyer** [comment] 2020-04-26 10:17
Duplicate of #688. 

As mentioned in that post, please provide a proper debug log there and post **enough details** regarding your used player and its config and see whether `--disable-gpu` helps when launching the Twitch GUI.

**Closed by bastimeyer** 2020-04-26 10:17 UTC
