### ISSUE TITLE
App vs HTML5 browser performance

### ISSUE THREAD

**Issue by ysolovyov** [streamlink/streamlink-twitch-gui#381] opened 2016-12-25 07:56 UTC
*Thanks for reporting an issue!*
*Please read the contribution guidelines first!*

*Feel free to use the following template. Be as detailed as possible.*
*Don't forget to remove this text before submitting.*

----

### Checklist

- [x] This is a bug report.
- [ ] Streamlink is working correctly on my system without using the Twitch GUI.
- [ ] I tried solving my issue by reading the project's wiki first.
- [ ] I used the search function to find already opened/closed issues or pull requests.

### Description

HTML5 browser version using much less CPU than streamlink-twitch-gui. Check attached files.

### Expected / Actual behavior

...

### Reproduction steps

1. Just run the app
2. ...
3. ...

### Environment details (operating system, etc.)

Macbook 12, mac os 10.2.2

### Comments, logs, screenshots, etc.

<img width="1152" alt="screen shot 2016-12-25 at 09 50 43" src="https://cloud.githubusercontent.com/assets/681814/21470229/f1af722a-ca87-11e6-8299-a7e5eb4c6ad5.png">
<img width="1152" alt="screen shot 2016-12-25 at 09 49 06" src="https://cloud.githubusercontent.com/assets/681814/21470230/f1df1994-ca87-11e6-87c8-5372d0954d40.png">

**Comment by bastimeyer** [comment] 2016-12-25 13:49
Could this be related?
nwjs/nw.js#5152

Does this only happen while watching streams (while having other GPU intensive processes running)?
Can this behavior be reproduced in Chromium 55?

**Comment by bastimeyer** [comment] 2016-12-28 22:14
Could you also please provide a better process list/graph?

```bash
ps -e -o pid,ppid,cpu,cputime,%cpu,comm | grep Streamlink
```

**Comment by ysolovyov** [comment] 2016-12-28 22:37
Ok, seems this is not Streamlink

`[yura@toy15 Downloads]$ ps -e -o pid,ppid,cpu,cputime,%cpu,comm | grep Streamlink
 6379     1   0   0:03.97   1.2 /Applications/Streamlink Twitch GUI.app/Contents/MacOS/nwjs
 6382     1   0   0:00.02   0.0 /Applications/Streamlink Twitch GUI.app/Contents/Versions/55.0.2883.75/nwjs Framework.framework/Helpers/crashpad_handler
 6383  6379   0   0:01.60   0.0 /Applications/Streamlink Twitch GUI.app/Contents/Versions/55.0.2883.75/nwjs Helper.app/Contents/MacOS/nwjs Helper
 6384  6379   0   0:08.05   0.0 /Applications/Streamlink Twitch GUI.app/Contents/Versions/55.0.2883.75/nwjs Helper.app/Contents/MacOS/nwjs Helper`

it is vlc, but why, i can't get

`top | grep VLC
6392  VLC              70.7 07:53.13 19    4   321    181M   2688K  0B     6388 6388 stuck `

tried mpv player, same 60-70% cpu usage... but iStatMenus continues showing that its Streamlink using that cpu percents.

**Comment by bastimeyer** [comment] 2016-12-28 22:45
Check your player's decoding and rendering settings. I can't help you here.

> iStatMenus

Maybe it's adding up all child processes, who knows. The `ps` command returns the correct values, though...

**Comment by bastimeyer** [comment] 2016-12-30 11:24
I'm closing this thread, since you've figured out that your high CPU usage was caused by VLC.

**Closed by bastimeyer** 2016-12-30 11:24 UTC
