### ISSUE TITLE
feature request http://www.publicdomaintube.com/

### ISSUE THREAD

**Issue by markosjal** [streamlink/streamlink-twitch-gui#582] opened 2018-06-20 19:28 UTC
*Thanks for reporting an issue!*
*Please read the contribution guidelines first! (see the link above)*

*Feel free to use the following template. Be as detailed as possible.*
*Please see the text preview to avoid unnecessary formatting errors.*
*Don't forget to remove this text before submitting.*

----

### Checklist

- [] This is a bug report.
- [x ] This is a feature request.
- [ ] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [ ] I tried solving my issue by reading the project's wiki first.
- [ ] I have read the contribution guidelines und used the search function to find already existing threads.

### Description

...

### Expected / Actual behavior

...

### Reproduction steps

1. ...
2. ...
3. ...

### Environment details

Operating system and version: ...
Streamlink Twitch GUI version: ...
Streamlink version: ...
Configuration details: ...

...

### Comments, logs, screenshots, etc.

Please asdd http://www.publicdomaintube.com/ if possible

**Comment by sadiablos** [comment] 2018-06-20 20:44
Duplicate of #192 / #309 / #415 ?
And read template before posting... 

> _Thanks for reporting an issue!
Please read the contribution guidelines first! (see the link above)
Feel free to use the following template. Be as detailed as possible.
Please see the text preview to avoid unnecessary formatting errors.
Don't forget to remove this text before submitting._

**Closed** 2018-06-21 10:07 UTC
