### ISSUE TITLE
Installer should create a folder in Start Menu

### ISSUE THREAD

**Issue by nyakze** [streamlink/streamlink-twitch-gui#484] opened 2017-07-05 15:44 UTC
### Description

Streamlink GUI installer doesn't automatically create Start Menu folder and/or shortcut

### Expected / Actual behavior

Streamlink GUI installer should automatically create Start Menu folder and/or shortcut, or present tick option to enable/disable it.

### Reproduction steps

1. Install Streamlink Twitch GUI
2. No Start Menu folder/shortcut appear

### Environment details (operating system, etc.)

Win7 x64 / Win10 x64

**Comment by bastimeyer** [comment] 2017-07-05 16:24
The Windows installer is [deliberately not creating any start menu entries](https://github.com/streamlink/streamlink-twitch-gui/blob/53523447d3378b2199a7efb15a00417f1f3deb5f/build/resources/installer/installer.nsi) (which also includes subfolders), because a special start menu shortcut has to be created in order to be able to show [toast notifications](https://github.com/streamlink/streamlink-twitch-gui/wiki/Desktop-notifications#toast-notifications-windows) on Windows 8 and 10. These shortcuts have to include a special application ID property and can't be created either with NSIS (the tool used for building the installer) or with any other tool included in Windows by default. This means that you have to write your own little program using the [necessary Windows API](https://msdn.microsoft.com/en-us/library/windows/desktop/hh802762(v=vs.85).aspx) for that, or you can simply use [SnoreToast](https://github.com/bastimeyer/snoretoast), which automatically creates these shortcuts when showing a notification.

So if the installer would also create start menu shortcuts, an additonal one would always be created by SnortToast when toast notifications are being shown, and I think that most users would dislike that.

**Comment by bastimeyer** [comment] 2017-07-12 17:35
Closing the thread since not creating start menu entries is intended behavior and can't be changed (for now).

**Closed by bastimeyer** 2017-07-12 17:35 UTC
Labels: packaging / updates, Windows

**Comment by i-cant-git** [comment] 2018-12-21 20:59
I don't understand, let's say, you can't put shortcuts in the first path because it requires admin privileges. But second path doesn't require admin privileges because it's a user folder.

1. `C:\ProgramData\Microsoft\Windows\Start Menu\Programs`
2. `C:\Users\icantgit\AppData\Roaming\Microsoft\Windows\Start Menu\Programs`

**Comment by bastimeyer** [comment] 2018-12-22 05:01
This has nothing to do with admin rights. See my comment above. It's about toast notifications, which require a special shortcut in the start menu. AFAIK, you can hide start menu items which you don't like, but I can't tell you how to do that.
