### ISSUE TITLE
Blurry font text

### ISSUE THREAD

**Issue by Frejoh466** [streamlink/streamlink-twitch-gui#943] opened 2022-12-21 09:07 UTC
### Checklist

- [X] I understand that **Streamlink Twitch GUI** is just a launcher for **Streamlink**
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink-twitch-gui/blob/master/CONTRIBUTING.md)
- [X] [I have checked the list of open and recently closed issues](https://github.com/streamlink/streamlink-twitch-gui/issues?q=is%3Aissue+sort%3Aupdated-desc)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink-twitch-gui/commits/master)

### Streamlink Twitch GUI version

2.2.0

### Streamlink version

5.1.0

### Operating system, environment and configuration details

Microsoft Windows [Version 10.0.19045.2251]

### Description

The font becomes blurry after a while, but becomes clear if I click around or hover over the text.
This seems to only occur when using scaling in windows (I use 125%), it was fine in 2.0. Changing "Change high DPI settings" in properties for the .exe does not work. Does not matter if it is dark or light version. Clear type is on. Not sure if it is the same problem as #72

![1](https://user-images.githubusercontent.com/10078405/208865089-6b55ebc3-96a8-49b6-a11a-df37e2e68cda.jpg)
![2](https://user-images.githubusercontent.com/10078405/208865023-1becda54-8f96-41a3-8438-d60277cb2d14.jpg)

**Comment by bastimeyer** [comment] 2022-12-21 16:18
This is not a blurry font issue. #72 is also completely unrelated and more than seven years old.

The entire application content gets rendered blurrily by NW.js/Chromium on your Windows machine. I don't use Windows, but according to Google search results, this is an issue with your system's screen DPI configuration which leads to Chromium rendering stuff incorrectly. It could also be caused by your system's graphics drivers (see #496).

Since this is related to NW.js/Chromium and not the application code itself, I'm going to close this. I can't help you with this and you'll have to figure this out on your own, sorry.

**Closed by bastimeyer** 2022-12-21 16:18 UTC

**Comment by Frejoh466** [comment] 2022-12-25 06:15
I did some more searching and found that ether Microsoft need to add support for Chromium, or Google need to add support for ClearType. Doesn't seems like there is a simple fix for this.

MacType does solve the problem, but it replace ClearType, so not the best solution. But I just live it here if someone else has this problem.
