### ISSUE TITLE
Stream fails to open when started from the UI

### ISSUE THREAD

**Issue by eNTi** [streamlink/streamlink-twitch-gui#423] opened 2017-03-20 11:52 UTC
### Checklist

- [x] This is a bug report.
- [x] Streamlink is working correctly on my system without using the Twitch GUI.
- [x] I tried solving my issue by reading the project's wiki first.
- [x] I used the search function to find already opened/closed issues or pull requests.

### Description

Streamlink is not relyaing the stream correctly? VLC window opens... and closes again fater 10s. No error message.

### Expected / Actual behavior

Stream should start playing.

### Reproduction steps

1. Select stream press play
2. Wait
3. Nothing happens

### Environment details (operating system, etc.)

Linux eNTi 4.9.13-1-MANJARO #1 SMP PREEMPT Sun Feb 26 13:27:28 UTC 2017 x86_64 GNU/Linux
streamlink-twitch-gui 1.2.0

### Comments, logs, screenshots, etc.

Where do I find logs or how do I enable debug mode or something along those lines?

**Comment by bastimeyer** [comment] 2017-03-20 15:39
Since the Twitch GUI is basically just a launcher (parameter generator) for Streamlink, it's very unlikely that stream viewing related issues are caused by it. Please make sure that Streamlink itself and your player are working correctly and that your connection is stable.

The only thing that the Twitch GUI is doing differently than when launching Streamlink from the shell is that it forces the [`--player-passthrough`](https://streamlink.github.io/cli.html#cmdoption-player-passthrough) parameter. See the [wiki](https://github.com/streamlink/streamlink-twitch-gui/wiki/Streamlink-configuration#stream-type), why.

If you want to debug the Streamlink output, you can add custom parameters in the settings menu.
https://streamlink.github.io/cli.html#cmdoption-l
https://streamlink.github.io/cli.html#cmdoption-verbose-player

**Comment by eNTi** [comment] 2017-03-20 16:27
If I c/p the link to streamlink on cli and add "best" at the end it works. If I try to start it from the UI it doesn't. I _think_ it probably has something to do with the quality string you are sending?

**Comment by eNTi** [comment] 2017-03-20 16:34
I just found a difference... if I start from the UI it tries to connect to **LOCAL IP:<some port>** and if I start streamlink from cli the player states: **fd;//0**. What gives?

**Comment by bastimeyer** [comment] 2017-03-20 16:37
No, the quality selection doesn't have anything to do with streams shutting down after X seconds.
You can see the quality definitions [here](https://github.com/streamlink/streamlink-twitch-gui/blob/v1.2.0/src/app/models/stream/qualities.js), but those can also be edited in the settings menu.

> If I c/p the link to streamlink on cli and add "best" at the end

I can't help you if you don't do what I have suggested.

> I just found a difference

See my previous post... Here are the links again which you should read first:
https://streamlink.github.io/cli.html#cmdoption-player-passthrough
https://github.com/streamlink/streamlink-twitch-gui/wiki/Streamlink-configuration#stream-type

**Comment by eNTi** [comment] 2017-03-20 16:42
I've read them and tried to play with the pass through type. Only rtpm seems to work with vlc? I suppose this is fine by me. Not sure it's still a bug though?

**Comment by bastimeyer** [comment] 2017-03-20 16:51
If it's a bug, then it's VLC related. Which VLC version are you using?

The Streamlink website has some player incompatibilities listed, but VLC not reading http streams is new to me.
https://streamlink.github.io/players.html

Can you confirm that this is 100% caused by the passthrough method?
```bash
streamlink --player /path/to/vlc --player-passthrough hls twitch.tv/CHANNEL best
streamlink --player /path/to/vlc --player-passthrough rtmp twitch.tv/CHANNEL best
```

**Comment by eNTi** [comment] 2017-03-20 17:27
`streamlink -l debug -v -p vlc --player-passthrough hls witch.tv/moonducktv best`
shows the following VLC error:
```
Your input can't be opened:
VLC is unable to open the MRL 'https://video-edge-c67d6c.fra02.hls.ttvnw.net/v0/CsUB-MkvVMhlLntaKjQIMllDu0b03U3BeCSV38Y8T5GJCz5Dmf7vM-nYGxq8-f-_BCWFVAflRLTd0rGcKTXNreSMi025PCdM_YGCPYYtEy5XHXl8KKKdgWO3FXD62tDbGQ9L7YR6x-34Xll_auM33_xd_3LTiw1Jymr61sBghOu6RORaGjeg6tE_dRHkyYuq5H7qorv1nd5bPW4ghc5OLEpxEdpeBLtI-fDVi9iVfIHkOmzeTOFpEPNsTQx7FR5NxqexuJUXVnsSEEYsaSfXSyDxnl9a9i9V0sQaDK-7_J3e40JbNBJueQ/index-live.m3u8'. Check the log for details.
```
while 
`streamlink -l debug -v -p vlc --player-passthrough rtmp twitch.tv/moonducktv best`
and
`streamlink -l debug -v -p vlc --player-passthrough http twitch.tv/moonducktv best`
both work.

If I start streamlink from cli vlc is showing "fd://0" again and not "my local ip:someport".

**Comment by bastimeyer** [comment] 2017-03-20 17:48
Oops, I didn't mean to post `hls`, I meant `http`. hls is again working differently.

> If I start streamlink from cli vlc is showing "fd://0" again and not "hxxp://mylocalip:someport".

Yes, because when using `--player-passthrough`, streamlink doesn't feed the video/audio data to your player via the stdin pipe, but instead creates a "relay server" from which the player will read the transformed stream from.

> http and rtmp both work.

So your issue is independent of the passthrough method. I would have been surprised if it actually was.

But again, as I've already said, if you think that the Twitch GUI is responsible for streams ending unexpectedly, go to the settings menu and add the `-l debug -v` custom streamlink parameters, so that you can see what is happening.

You can also run
```sh
ps -e -o cmd | grep python | grep streamlink
```
to see all the whole command line when a stream has been launched.

**Comment by eNTi** [comment] 2017-03-20 19:17
Ok... so i've added the debug settings and I'm getting a lot of errors. I wants me to install ALL of the optional plugins, even pulseaudio??? i guess, I'll have to compile it by myself and not use the aur git package...

**Comment by bastimeyer** [comment] 2017-03-20 19:24
Streamlink has finally been adopted to Arch's community repos a couple of days ago and the AUR package has been removed (along with the livestreamer package from the community repo). I don't know how this works in Manjaro, unfortunately.

If you want a custom streamlink installation, you can do this via python-pip. Just uninstall the old package first, install python-pip and run `sudo pip install streamlink`.

**Comment by eNTi** [comment] 2017-03-20 20:03
It says:
`install: missing destination file operand after 'streamlink'`

**Comment by bastimeyer** [comment] 2017-03-22 22:58
Did you manage to install streamlink via pip (or via the git repo)?

> so i've added the debug settings and I'm getting a lot of errors

Are you using the same python env and streamlink version in the Twitch GUI as when calling "streamlink" from your shell?

**Comment by eNTi** [comment] 2017-03-23 08:22
Yeah I managed to use pip. Had to use pacman instead of yaourt to install pip to use it? Nonetheless it always tries to connect to pulseaudio. I don't know how to compile it without pulseaudio support.

**Comment by bastimeyer** [comment] 2017-03-23 16:56
Well, I'm going to close this thread, since the issue you were reporting is clearly caused by your streamlink installation. If you think otherwise, you can reopen it once you've resolved your issues. If you have any streamlink related questions, you should go to the main streamlink repo.

**Closed by bastimeyer** 2017-03-23 16:56 UTC
Labels: streamlink
