### ISSUE TITLE
Error when launched a stream with Streamlink configuration

### ISSUE THREAD

**Issue by moige** [streamlink/streamlink-twitch-gui#383] opened 2016-12-28 21:17 UTC
### Checklist

- [x] This is a bug report.
- [x] Streamlink is working correctly on my system without using the Twitch GUI.
- [x] I tried solving my issue by reading the project's wiki first.
- [x] I used the search function to find already opened/closed issues or pull requests.

### Description

When I tried to launch a stream using Streamlink configuration, this error appears:
 `Traceback (most recent call last):
File "C:\Program Files\Twtich GUI\streamlink\bin\streamlink-script.py", line 11, in <module>
from streamlink_cli.main import main
File "C:\Program Files\Twtich GUI\streamlink\pkgs\streamlink_cli\main.py", line 17, in <module>
from streamlink.stream import StreamProcess
File "C:\Program Files\Twtich GUI\streamlink\pkgs\streamlink\stream\__init__.py", line 6, in <module>
from .hls import HLSStream
File "C:\Program Files\Twtich GUI\streamlink\pkgs\streamlink\stream\hls.py", line 4, in <module>
from Crypto.Cipher import AES
File "C:\Program Files\Twtich GUI\streamlink\pkgs\Crypto\Cipher\__init__.py", line 78, in <module>
from Crypto.Cipher._mode_ecb import _create_ecb_cipher
File "C:\Program Files\Twtich GUI\streamlink\pkgs\Crypto\Cipher\_mode_ecb.py", line 46, in <module>
"""
File "C:\Program Files\Twtich GUI\streamlink\pkgs\Crypto\Util\_raw_api.py", line 168, in load_pycryptodome_raw_lib
raise OSError("Cannot load native module '%s'" % name)
OSError: Cannot load native module 'Crypto.Cipher._raw_ecb'`

I tested with Livestreamer (Standalone) and run perfectly.
### Reproduction steps

1. Launch a Stream with Streamlink configuration

### Environment details (operating system, etc.)

Windows 7 Ultimate Service Pack 1, Python 3.6, Streamlink 0.2.0

### Comments, logs, screenshots, etc.

![ss](https://cloud.githubusercontent.com/assets/15069486/21531571/7c1aabb6-cd1f-11e6-94b8-090e48a69e52.png)
![ss](https://cloud.githubusercontent.com/assets/15069486/21531762/fa369130-cd20-11e6-80d3-035b2804a40f.png)

**Comment by bastimeyer** [comment] 2016-12-28 21:53
As you can read in the wiki, the selected python executable needs to be compatible with Streamlink. The one you've selected is not.

It looks like you're using the Streamlink installer on Windows. This already includes an embedded python environment with a working python executable, so simply choose this instead.

Btw, you have a spelling error in the folder name. 😛 

I'm closing this thread, since it's a user misconfiguration and not a bug...

**Closed by bastimeyer** 2016-12-28 21:53 UTC

**Comment by moige** [comment] 2016-12-28 22:15
Only mention "Python3" and the version of my Python are 3.6. Need to be more specific... Well, thanks.

**Comment by bastimeyer** [comment] 2016-12-28 22:21
Well, it's an upstream issue and unrelated to this project.
See streamlink/streamlink#323

**Comment by moige** [comment] 2016-12-28 22:42
I understand that, but the documentation need to be more specific and constantly in updated, especially if you use third party projects... My humble opinion. Tanks so much and good work with this project :)
