### ISSUE TITLE
Twitch GUI automatically closes live streams

### ISSUE THREAD

**Issue by Nepturian** [streamlink/streamlink-twitch-gui#469] opened 2017-06-02 22:14 UTC
### Checklist

- [x] This is a bug report.
- [ ] Streamlink is working correctly on my system without using the Twitch GUI.
- [ ] I tried solving my issue by reading the project's wiki first.
- [ ] I used the search function to find already opened/closed issues or pull requests.

### Description

So for some time now after the updates with streamlink, the player closes it self by the Twitch GUI.
Many times the stream closes to the GUI, can be launched again.
Or it will make the GUI unresponsive, need to force quit the program.
Also tapping the tray icon doesn't always make the GUI appear. 

### Expected / Actual behavior

Playing live streams, closes the MPC-HC player to the GUI like it's a fault with the authentication with external viewing.

### Reproduction steps

1. Launch a stream
2. After 2 hours, 5 hours the problem might appear.
3. 

### Environment details (operating system, etc.)

Windows 10 PRO, 7700K, ROG IX Formula, 64GB Ram

### Comments, logs, screenshots, etc.

These crash reports are the only ones I have on the PC.
The reports seems not to generate when force closing the app.

**Comment by Nepturian** [comment] 2017-06-02 22:17
The zip files can not be added..... no support for the file..

**Comment by Nepturian** [comment] 2017-06-03 02:08
Same thing happens after the new update, a little over three overs and the media player just closes automatically with no warning....

**Comment by bastimeyer** [comment] 2017-06-03 19:48
Please check if Streamlink and your player are both working fine when launching streams from the command line.

Player windows will only be closed by Streamlink either when the user ends the streamlink child process on their own (via the Twitch GUI) or when the stream ends, which can happen if the broadcaster interrupts their stream. There's currently no mechnism in the Twitch GUI that distinguishes between these situations, because Streamlink behaves the same in both.

Regarding the unresponsiveness of the Twitch GUI after a while, could you please check the memory consumption? Maybe there's a memory leak here... Unfortunately, the crash reports you've linked are not useful here and are meant for the NW.js devs. If it's okay, I'm going to remove the link, since I don't like external links with binary stuff.

**Comment by Nepturian** [comment] 2017-06-03 20:34
The media player auto closes like it's been given orders to by Twitch GUI.
There is no issues on the streamer or twitch.
Using both browser and media player, and browser still continues to play the stream.
If there is a memory leak it's the program, because I haven't updated or changed anything after the non streamlink one. Reinstalling 1.3.1 again with Streamlink 0.6.0+efa57cb.
If the the program still crashes I will go back to before the streamlink version.

Well fine then, removing the dmp files... If this site cant upload the freaking dump files in zip.. why bother uploading anything.

**Comment by Nepturian** [comment] 2017-06-04 00:33
![streamlink twitch gui auto stops](https://cloud.githubusercontent.com/assets/29153523/26757933/f2fc66f0-48cd-11e7-85f1-4bb7ea37fa6a.png)
So did reinstall... a few hours into the stream the MPCHC auto pauses and if the ticker ¨close when ended¨ is enabled it closes the player completely.... WHY is this happening?????????

**Comment by bastimeyer** [comment] 2017-06-04 04:44
Please have in mind that Streamlink Twitch GUI is just a browser and launcher (parameter generator) for Streamlink or Livestreamer.

Anything regarding streaming, opening/closing the player and feeding data to it is done by [Streamlink](https://github.com/streamlink/streamlink) and unrelated to the Twitch GUI. If you're experiencing issues of any kind related to Streamlink, you should try to debug these issues by launching streams from the [command line](https://streamlink.github.io/cli.html), so that you can be sure the Twitch GUI is not the cause. If you want to know the Streamlink parameters used by the Twitch GUI when launching a stream, you can use the [`--l debug`](https://github.com/streamlink/streamlink-twitch-gui/wiki/Parameters#--loglevel) parameter.

**Comment by Nepturian** [comment] 2017-06-04 20:43
I will try the command line.. if it's still an issue. I might try the really old versions where I know it worked before the rebrand.
This is just annoying and stupid problem.
Still have K-Lite codec like always so there is nothing new from when the GUI worked flawlessly to now.

**Comment by Nepturian** [comment] 2017-11-22 23:06
Any fixes for this??
When using VLC or MPC-HC the stream stops for no reason...
Programs aren't the issue, seems like the stream has no connection.
Need to exit VLC, and relaunch the stream. May take 5 minutes or 1 hour until I have to do it again.
Using HLS and Streamlink provider.

Streamlink GUI v1.4.1
Streamlink 0.8.1+a803926
NW.js v0.26.6

**Comment by bastimeyer** [comment] 2017-11-23 06:45
As I've already said, your issues are entirely unrelated to the Twitch GUI. It's even unrelated to Streamlink if you're using the HLS passthrough player input method, since it's just forwarding the retrieved stream URL to the player as opposed to the other methods where Streamlink is reading and buffering the stream data. The Twitch GUI is just a parameter generator and launcher for the Streamlink application, which itself is starting the player processes, so the Twitch GUI has no control over this. I've told you to debug this from the command line, but you still haven't done this. You should also make sure that your system is configured properly, because it doesn't look like it, especially with the other nvidia drivers related issue you've opened in July.
I'm closing this thread now, since there's nothing which I can do for you here. If you're convinced that this is caused by a bug in the source code of Streamlink, please open a new issue on the Streamlink issue tracker.

**Closed by bastimeyer** 2017-11-23 06:45 UTC
Labels: platform issue, Windows

**Comment by Nepturian** [comment] 2017-11-23 06:53
I have tried to use the command line ¨streamlink --player "C:\Program Files\VideoLAN\VLC\vlc.exe" twitch.tv/------ 720p60¨
But still happens from time to time.
Probably have to live with this, wasn't happening before the revamp of Twitch GUI.

**Comment by bastimeyer** [comment] 2017-11-23 07:03
> wasn't happening before the revamp of Twitch GUI.

That must have been a coincidence. The application has just been renamed in this release. Nothing major had changed. Streamlink had been added as the primary streaming provider a few months before that.

> streamlink --player "C:\Program Files\VideoLAN\VLC\vlc.exe" twitch.tv/------ 720p60

This command doesn't include the `--player-passthrough hls` parameter which you said you were using in the Twitch GUI.
If you're using the passthrough method, all what streamlink is doing is retrieving the stream URL and forwarding it to the player. This is the best method of detecting a broken player, since Streamlink doesn't do anything in this case. It's the same as running
```bash
streamlink --stream-url twitch.tv/CHANNEL QUALITY
```
and using the returned URL as input. You can try this out by launching VLC with this URL as the first parameter, or by starting VLC regularly and manually open the URL from its GUI.
