### ISSUE TITLE
Streaming does not start throwing an unclear error. When there is a symbol " / " " | " in the title

### ISSUE THREAD

**Issue by daqar** [streamlink/streamlink-twitch-gui#783] opened 2021-03-07 16:54 UTC
## Bug report

+- [ ] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
+- [ ] This is a bug report and I have read the contribution guidelines.

### Environment details

**Operating system and version:**  

Win7sp1

Windows version
streamlink-portable-2.0.0-py3.6.5-win32 +
streamlink-twitch-gui-v1.11.0-win32

### Description

This bug has been around since version 1.3.1.
Unfortunately, it has not been fixed.

But I noticed that it happens with streamers who have in the title " / " and/or " | ".

On other streamers, which do not have it in the title all works.

### Reproduction steps

It looks like this
https://dl.dropboxusercontent.com/s/6dqsbe54viurtzz/2021-03-07_17-53-41.mp4

I think it's a mistake not streamlink.

**Comment by bastimeyer** [comment] 2021-03-07 17:01
Not a Streamlink Twitch GUI issue.

> streamlink-portable

- https://github.com/beardypig/streamlink-portable/issues/19
- https://gitter.im/streamlink/streamlink-twitch-gui?at=6017e1714f7d1b68e5230f8b

----

Don't use the `.bat` file and instead choose the `Streamlink (Python)` streaming provider and select the `pythonw.exe` as python executable and `streamlink-script.py` as streamlink entry script.

https://github.com/streamlink/streamlink-twitch-gui/wiki/Streamlink-configuration#selecting-a-streaming-provider

**Comment by daqar** [comment] 2021-03-08 10:42
@bastimeyer Thank you very much,
I need to create bug reports on their pages ?

https://github.com/streamlink/streamlink or the one that builds the portable version?

**Comment by bastimeyer** [comment] 2021-03-08 10:48
I've already linked the bug report which I've opened myself a month ago on the beardypig/streamlink-portable repo.

The issue is caused by incorrect variable expansion in the wrapper launch script. I don't know Windows batch scripting, so I can't submit a pull request to fix it. If it's similar to BASH, then replacing `%*` with `"%*"` should fix the issue.

Closing the thread here, since it's not a Streamlink Twitch GUI issue.

**Closed by bastimeyer** 2021-03-08 10:48 UTC
Labels: os: Windows, provider: streamlink-portable, upstream

**Comment by daqar** [comment] 2021-03-10 13:26
I find how to fix this problem :dancers: :D

**In short**, we should disable stream title sending to the player (and streamlink). This checkbox is in the GUI options.
The problem is in the parameter "--input-title-format"

1. we need the original streamlink-portable.
2. streamlink.bat does not need to be edited, because any change in it prevents us from running anything)
3. Settings -> Panel "Player" -> row "Player window title". Uncheck, checkbox.
4. Apply settings

Done!

how to fix the error in the video format, and what it looks like before and after the error/disable option.
https://dl.dropboxusercontent.com/s/kpcfporlmp4tg60/2021-03-10_14-59-15.mp4

In case you're wondering, I realized that all the other parameters, including the title, are sent by options in streamlink.bat and these options go here %*.
This is where the error occurs.
For the future: there should not be any special characters in the startup parameters.

**Comment by bastimeyer** [comment] 2021-03-10 13:33
No, I have already told you what to do to fix the issue properly:
https://github.com/streamlink/streamlink-twitch-gui/issues/783#issuecomment-792311331

> Don't use the `.bat` file and instead choose the `Streamlink (Python)` streaming provider and select the `pythonw.exe` as python executable and `streamlink-script.py` as streamlink entry script.

Then you don't need to disable custom player titles, as the issue lies in the streamlink.bat file provided by beardypig/streamlink-portable. The `Streamlink (Python)` streaming provider executes Streamlink directly via `pythonw.exe` instead of using a wrapper script/executable (aka. the bat file). Launching Streamlink via the wrapper script/executable is not supported, as you can read in the wiki which I've also already linked.

**Comment by daqar** [comment] 2021-03-10 21:34
> No, I have already told you what to do to fix the issue properly:
> [#783 (comment)](https://github.com/streamlink/streamlink-twitch-gui/issues/783#issuecomment-792311331)

@bastimeyer
I know I read, and took note, but a long time ago (I think since version 1.4.*) launch directly through python script does not work. In my situation (with portable revs etc).

![image](https://i.vgy.me/Ouxu0Z.png)

And I'm too lazy to figure out the second time, where and what paths need to change and what Python to download (probably this version is not suitable), etc. I did it in version 1.4, and could not solve anything with this, spending several days to find a solution to the problem.

It's easier for me to uncheck it and use at least somehow the working version, albeit with crutches.

But anyway, thanks for your help. :-* :+1:
