### ISSUE TITLE
macOS 15.1 on trying to open: The application “Finder” does not have permission to open “(null).”

### ISSUE THREAD

**Issue by dimitarvp** [streamlink/streamlink-twitch-gui#1027] opened 2024-10-29 11:12 UTC
### Checklist

- [x] I understand that **Streamlink Twitch GUI** is just a launcher for **Streamlink**
- [x] [I have read the contribution guidelines](https://github.com/streamlink/streamlink-twitch-gui/blob/master/CONTRIBUTING.md)
- [x] [I have checked the list of open and recently closed issues](https://github.com/streamlink/streamlink-twitch-gui/issues?q=is%3Aissue+sort%3Aupdated-desc)
- [x] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink-twitch-gui/commits/master)

### Streamlink Twitch GUI version

v2.5.2

### Streamlink version

6.11.0

### Operating system, environment and configuration details

macOS 15.1, Intel Mac

### Description

Just upgraded to macOS 15.1 and tried to start the app. I got two identical windows stack on top of each other and I am posting a screenshot after I put them side by side. Both say the same thing:

> The application “Finder” does not have permission to open “(null).”

I have opened the app contents and I actually can't find the binary that is the app itself. Maybe Apple quarantined it and removed it? No idea.

The app is installed through homebrew. I have reinstalled it to no effect, same error appears.

I also tried uninstalling it with homebrew and just unpacking the app given in the GitHub releases page -- same error again.

![Image](https://github.com/user-attachments/assets/e243b17d-126c-4fec-8277-7725f198e3e9)

### Debug log

Inapplicable, can't start the app.

**Comment by bastimeyer** [comment] 2024-10-29 11:43
That's nothing I can do about here and also nothing I am willing to investigate myself, as I'm not an Apple user. I'm not going to spend a couple of hours updating my macOS VMs and testing this.

According to Google, this is a bug in the recent macOS version. Lots of users are having the same issue with other applications which were not installed from the Apple app store. Just search for that same error message and you'll find various other posts about this particular issue.

Check your user/app permissions. Otherwise, check Apple's support forums.
https://docs.brew.sh/FAQ#why-cant-i-open-a-mac-app-from-an-unidentified-developer

Since this is not an issue with Streamlink Twitch GUI itself (or NW.js), I'm going to close this.

**Comment by dimitarvp** [comment] 2024-10-31 12:33
Forgot to say. Simply right-clicking on the app and doing Show Package Contents and then going inside Contents -> MacOS and opening `nwjs` makes the app open successfully. It also produces a sticky Terminal.app window but for now I can live with it.

**Comment by dimitarvp** [comment] 2024-10-31 17:24
Just tried the workaround by removing / commenting out the section you pointed me at. The app started just fine.

Thank you. Waiting on next release when that won't be necessary. In the meantime you unblocked me.

Any explanation why this seemingly innocuous section made so much trouble?

**Comment by bastimeyer** [comment] 2024-10-31 17:29
Reopening for visibility until I've published a new release. I'll focus on Streamlink 7.0.0 first though, which will probably happen tomorrow.

In the mean time, simply update the `Info.plist`, just like I mentioned, or run the `nwjs` executable from within the `Streamlink Twitch GUI.app/Contents/MacOS` directory.

----

> you unblocked me

???
Nobody was ever blocked here. There's also nothing in the GH orga's audit log in regards to recent moderations. Closing an issue does not mean blocking.

> why this seemingly innocuous section made so much trouble?

This section in the app manifest was intended for updating the user's `PATH` environment variable years ago on older macOS versions, so the Streamlink executable could be found automatically without users having to select the path manually, depending on how Streamlink and Streamlink Twitch GUI were installed.

Apparently, this is not supported anymore on the recent macOS version or it requires special permissions. Either way, it's outdated and therefore can simply be removed.

**Comment by dimitarvp** [comment] 2024-10-31 18:31
lol 😆 No, I meant I was annoyed that I have to start the app in an convoluted way, and you unblocked me in the sense of being able to open it normally. Sorry for the confusion.

RE: `PATH`, I see, thank you.

**Comment by bastimeyer** [comment] 2024-11-04 17:09
> I'll focus on Streamlink 7.0.0 first

Streamlink 7.0.0 has been published now.

However, there's a build issue here which needs to be resolved first. The patch release will probably have to wait until tomorrow, because it's annoying to fix and will take a bit of time. I didn't notice the build issue after I had already pushed the tag (deleted again).

https://github.com/streamlink/streamlink-twitch-gui/actions/runs/11656626804/job/32453083095

**Comment by bastimeyer** [comment] 2024-11-04 19:29
https://github.com/streamlink/streamlink-twitch-gui/releases/latest

**Closed by bastimeyer** 2024-11-04 19:29 UTC
Labels: os: macOS, packaging / updates

**Comment by dimitarvp** [comment] 2024-11-10 23:21
Sorry to come back to this, I haven't restarted the app in a while and had to reboot my Mac so this just came up:

Basically macOS says that it could not verify that the app is free of malware. Can't open it at all. Only suggests to move it to trash. :(

Even the workaround to show package contents and right-click `nwjs` is not working anymore.

**Comment by bastimeyer** [comment] 2024-11-11 20:09
This is not related to this issue at all. it's simply the "unverified developer" issue, because the app isn't signed.

Once you see the "Move to trash" dialog, ignore it, go to your system settings, privacy and security, scroll down and allow "Streamlink Twitch GUI" to be run.

**Comment by dimitarvp** [comment] 2024-11-11 20:21
Been several days, managed to forget. You are right of course. Thank you.

**Comment by ryanknutson** [comment] 2025-04-11 04:38
The fix to remove LSEnvironment also works with SuperSlicer :)

Just delete the following from /Applications/SuperSlicer.app/Contents/Info.plist:
```
  <key>LSEnvironment</key>
  <dict>
    <key>ASAN_OPTIONS</key>
    <string>detect_container_overflow=0</string>
  </dict>
```
