### ISSUE TITLE
Graphical artifacts in search bar

### ISSUE THREAD

**Issue by bytegeist** [streamlink/streamlink-twitch-gui#412] opened 2017-02-19 14:22 UTC
### Checklist

- [x] This is a bug report.
- [x] Streamlink is working correctly on my system without using the Twitch GUI.
- [x] I tried solving my issue by reading the project's wiki first.
- [x] I used the search function to find already opened/closed issues or pull requests.

### Description

Graphical artifacts are visible in the search bar shortly after starting the program in the form of irregular grey horizontal lines (see screenshot).

### Expected / Actual behavior

Clean search bar.

### Reproduction steps

Start the program normally.

### Environment details (operating system, etc.)

Windows 7 (64 bit), Geforce GTX 970 (driver version: 378.66), Twitch GUI version: 1.1.1

### Comments, logs, screenshots, etc.

![image](https://cloud.githubusercontent.com/assets/3391322/23103183/3b092410-f6b7-11e6-89f9-e1c79cc0613f.png)

Could be related to anti-aliasing or other graphical post processing? 

Default options weren't changed.

**Comment by bastimeyer** [comment] 2017-02-19 14:48
This issue is caused by NW.js 0.19.x on Windows and has been fixed in #357 by upgrading to NW.js 0.20.0. You can try building the application off the master branch if you want. Or just wait for the next release.

**Comment by bytegeist** [comment] 2017-02-19 16:59
Alright, thanks for the response.

**Comment by bytegeist** [comment] 2017-02-19 17:01
Maybe I should leave it open in case someone else has the same issue. You can close it if you like.

**Closed** 2017-02-19 17:28 UTC
