### ISSUE TITLE
Location and size not saved when maximized

### ISSUE THREAD

**Issue by DOFandersolsen** [streamlink/streamlink-twitch-gui#324] opened 2016-10-02 17:11 UTC
Hi there!
### Description

If you move the Livestreamer Twitch GUI (LTG) around on your screen or from monitor to another monitor, and then close it, the current size and position will be remembered when LTG is launched next time.

However, if you change the window to being maximized, the size and location are not remembered.
### Expected / Actual behavior

I expected the window to be started maximized and on the screen it was last maximized on, when I close LTG while being maximized.

LTG instead opens in a windowed-mode in the last position I saved it as a window and not maximized.
### Reproduction steps
1.  Open LTG and resize it and change the position to anything but maximized
2. Close and reopen LTG, the window will have the position and size you closed it as
3. Maximize LTG and close the program.
4. Start the program and it will start with the size and location from point 2.
### Environment details (operating system, etc.)

W10 x64
LTG: 0.15.2

**Comment by bastimeyer** [comment] 2016-10-02 17:40
Hi!

This is intended behavior. The maximized state is not being remembered, because for some reason, it is not that simple to implement in NWjs. For example, on OSX, NWjs triggers several move and resize events for an unknown time span before reaching the maximized state, which is super annoying. And on Windows, the application window gets moved outside of the viewport when maximizing it. I'm pretty sure that the location also varies from Windows version to Windows version and/or used desktop theme. This is just one of the reasons why I have not implemented this (yet).

I'll see if I can implement this feature once #275 (big NWjs upgrade) has been merged.

**Closed** 2017-05-18 03:02 UTC
Labels: feature request
