### ISSUE TITLE
Consider adding “recently started” to sort channels in a category

### ISSUE THREAD

**Issue by lindosaa11** [streamlink/streamlink-twitch-gui#907] opened 2022-09-04 19:09 UTC
### Checklist

- [X] I understand that **Streamlink Twitch GUI** is just a launcher for **Streamlink**
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink-twitch-gui/blob/master/CONTRIBUTING.md)
- [X] [I have checked the list of open and recently closed issues](https://github.com/streamlink/streamlink-twitch-gui/issues?q=is%3Aissue+sort%3Aupdated-desc)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink-twitch-gui/commits/master)

### Description

unfortunately, there is no sorting option for channels inside a category. currently, it is sorted by viewers (high to low), and there is no way to change this. I thought this project gives the user the power to choose what's the best for them, not indulging Twitch's vision of promoting big streamers to be bigger. hope you consider it. 

thank you so much for your time and effort you put in making this.

**Comment by bastimeyer** [comment] 2022-09-04 19:13
> unfortunately, there is no sorting option for channels

Indeed, because Twitch doesn't support it.
https://dev.twitch.tv/docs/api/reference#get-followed-streams
https://dev.twitch.tv/docs/api/reference#get-streams

Duplicate of #898

**Closed by bastimeyer** 2022-09-04 19:13 UTC
