### ISSUE TITLE
Logs gets filled by a gl error message

### ISSUE THREAD

**Issue by Porkepix** [streamlink/streamlink-twitch-gui#655] opened 2019-08-05 17:09 UTC
## Bug report

- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] This is a bug report and I have read the contribution guidelines.

### Environment details

**Operating system and version:**  
ArchLinux, rolling release up-to-date (latest stable of everything)

**Streamlink Twitch GUI version:**  
1.7.1

**Streamlink version:**  
1.1.1

**Configuration details:**  
Running under a Gnome Wayland session if it may matters.

### Description

No visible bug, but journald gets flooded with the following lines:
```
Aug 05 17:22:33 T470-clement streamlink-twitch-gui.desktop[808]: [1726:1726:0805/172233.288659:ERROR:gl_surface_presentation_helper.cc(237)] GetVSyncParametersIfAvailable() failed!
```
Logs are filled with these lines, several per minutes while streamlink-twitch-gui is running.

### Expected / Actual behavior

Don't get filled with logs

### Reproduction steps
Just run streamlink-twitch-gui.

**Comment by bastimeyer** [comment] 2019-08-05 18:03
This looks like an upstream issue in the older Chromium versions:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=901831
which according to this thread on the debian bugtracker was fixed in one of the recent versions (`74.0.3729.108`):
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=901831#93

Streamlink Twitch GUI `1.7.1` uses NW.js [`0.37.4`](https://nwjs.io/blog/v0.37.4/) which itself is on the Chromium `73` branch.

Since NW.js apps like Streamlink Twitch GUI support the regular Chromium parameters, you can try and use `--use-gl=osmesa`, which should make the log message go away, but will cause other issues like the lack of proper GPU acceleration. At least that's what's said in the bug report, I haven't tested it myself.

----

I currently have an NW.js upgrade branch ([`nwjs-40`](https://github.com/streamlink/streamlink-twitch-gui/tree/nwjs-40)) pushed to the repo, which uses the latest NW.js / Chromium versions ([`0.40.0`](https://nwjs.io/blog/v0.40.0/) / `76.x`). I can't merge it though, because there are some breaking bugs caused by that version bump which still need to get fixed.

You can however try it and see if it makes the log messages go away. You could also build the app off the master branch and change the used NW.js version on your own here:
https://github.com/streamlink/streamlink-twitch-gui/blob/1a2715b81eac1d10c024960f1a50b9c56c11574d/src/config/main.json#L4
Maybe a simple bump to [`0.38.0`](https://nwjs.io/blog/v0.38.0/) (Chromium 74) is enough.

Build instructions can be found here:
https://github.com/streamlink/streamlink-twitch-gui/blob/1a2715b81eac1d10c024960f1a50b9c56c11574d/CONTRIBUTING.md#developing-and-building

I'll check out NW.js `0.38.0` tomorrow, since I'm about to release `1.8.0` anyway. If it doesn't cause breaking issues, then it'll be used in that release.

**Comment by bastimeyer** [comment] 2019-08-07 10:00
You can test the `nwjs-40` branch if you want. The other breaking issue I was talking about has been solved, so you can try this latest NW.js / Chromium version and see if this fixes your issue.

In case you prefer building a package instead of manually building the app, you can use the [`streamlink-twitch-gui-git`](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=streamlink-twitch-gui-git) AUR package and replace the `source` field in the PKGBUILD with this:
```sh
source=(${_pkgname}::"git+https://github.com/streamlink/${_pkgname}.git#branch=nwjs-40")
```

**Comment by Porkepix** [comment] 2019-08-07 10:13
Sadly, issue's still here.
The only difference is that it does now have a count at the end of the line:
```
Aug 07 12:12:28 T470-clement streamlink-twitch-gui.desktop[808]: [25561:25561:0807/121228.497135:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 18 times!
```

**Comment by bastimeyer** [comment] 2019-08-07 10:22
Unfortunately, there's nothing else which I can do here other than using the latest NW.js version.

If the issue is still there, then please check if it also exists in vanilla Chromium (with a clean profile) and report it there.

https://bugs.chromium.org/p/chromium/issues/list?q=GetVSyncParametersIfAvailable&can=1
https://bugs.chromium.org/p/chromium/issues/detail?id=879929

**Comment by Porkepix** [comment] 2019-08-07 10:26
I'll try to let it run, but I think the issue does react to something as these lines seems to come as blocks of 10-20 in a short amount of time, and then nothing.

**Comment by bastimeyer** [comment] 2019-08-07 10:32
https://github.com/nwjs/chromium.src/blame/c835be56537a6edb305ae7adcd1b4199d8375745/ui/gl/gl_surface_presentation_helper.cc#L256-L262

**Comment by bastimeyer** [comment] 2019-08-07 13:34
Does `--log-level=3` help? (Chromium parameter)
https://github.com/nwjs/chromium.src/blob/nw40-log/content/public/common/content_switches.cc#L564-L566

**Comment by Porkepix** [comment] 2019-08-07 13:41
Sorry for not coming back with an answer quickly; I actually got the lines in the log pretty easily and quickly by just doing nothing and yeah your previous comment explain why I didn't got more after 20:

```
Aug 07 12:26:29 T470-clement chromium.desktop[808]: [26148:26148:0807/122629.228303:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 19 times!
```
(Out of topic, but strangely it seems to always keep PID 808 in journald, which is gnome-shell's PID)

As for reporting it, it's still pretty unclear to me where would that go, as the issue you pointed was marked as resolved and I don't have clear understanding of the issue. This, plus chromium's bug tracker doesn't seem to be very privacy-friendly regarding emails.

**Comment by bastimeyer** [comment] 2019-08-07 14:14
The issue on the Debian bugtracker which I have posted (which was the best Google result after searching for the error message) was marked as resolved, because Chromium marked [this issue thread](https://bugs.chromium.org/p/chromium/issues/detail?id=879929) as fixed and released a new stable version. But as you can see [in the diff](https://chromium-review.googlesource.com/c/chromium/src/+/1477918), this "fix" only suppresses the excessive logging (the part I've already linked). If you think that the log suppression is not enough, then comment on that issue thread.

That's all I can do here.

**Comment by Porkepix** [comment] 2019-08-07 14:17
Well, I believe silencing an error message is never a good idea, however I don't understand what's the matter here, so it's kinda hard to tell anything about it.
Although, if I understand correctly streamtlink-twitch-gui should at the very least get the silencing in the upcoming release?

**Comment by bastimeyer** [comment] 2019-08-07 14:21
Yes, I've merged it into master a few minutes ago and deleted the nwjs-40 branch.
I'll publish 1.8.0 tomorrow, I guess.

**Comment by bastimeyer** [comment] 2019-08-11 19:15
I'm closing this one here, as the log spamming should have been fixed in the recent upgrade.

**Closed by bastimeyer** 2019-08-11 19:15 UTC
Labels: Linux, platform issue
