### ISSUE TITLE
OS X Sierra 10.12.4 - VLC + HTTP stream does not open

### ISSUE THREAD

**Issue by amanb014** [streamlink/streamlink-twitch-gui#445] opened 2017-04-24 04:00 UTC
### Checklist

- [x] This is a bug report.
- [x] Streamlink is working correctly on my system without using the Twitch GUI.
- [x] I tried solving my issue by reading the project's wiki first.
- [x] I used the search function to find already opened/closed issues or pull requests.

### Description

I am currently on Mac OS X Sierra 10.12.4, and streamlink is working on command line, but the GUI version seems to be giving me an error code 1 with the following log attached here. I am really confused as to what the problem is. I have tried giving the GUI explicit path to my streamlink (/usr/local/bin/streamlink) in the GUI and it still isn't working. 

Does anyone have any suggestions?

### Environment details
- VLC 2.2.4
- streamlink 0.5.0
- Streamlink Twitch GUI Version 1.2.1 (1.2.1)
- OSX Sierra 10.12.4

### Failed Streamlink GUI Log:

```
Found matching plugin twitch for URL twitch.tv/petesgameroom
Attempting to authenticate using OAuth token
Successfully logged in as MyUserName
Available streams: audio, mobile (worst), low, medium, high, source (best)
Starting player: /Applications/VLC.app/Contents/MacOS/VLC
Traceback (most recent call last):
File "/usr/local/bin/streamlink", line 9, in <module>
load_entry_point('streamlink==0.5.0', 'console_scripts', 'streamlink')()
File "/Library/Python/2.7/site-packages/streamlink-0.5.0-py2.7.egg/streamlink_cli/main.py", line 999, in main
handle_url()
File "/Library/Python/2.7/site-packages/streamlink-0.5.0-py2.7.egg/streamlink_cli/main.py", line 499, in handle_url
handle_stream(plugin, streams, stream_name)
File "/Library/Python/2.7/site-packages/streamlink-0.5.0-py2.7.egg/streamlink_cli/main.py", line 377, in handle_stream
return output_stream_http(plugin, streams)
File "/Library/Python/2.7/site-packages/streamlink-0.5.0-py2.7.egg/streamlink_cli/main.py", line 192, in output_stream_http
server.close()
File "/Library/Python/2.7/site-packages/streamlink-0.5.0-py2.7.egg/streamlink_cli/utils/http_server.py", line 116, in close
self.socket.shutdown(2)
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
return getattr(self._sock,name)(*args)
socket.error: [Errno 57] Socket is not connected
```

### Successful CLI log:
```
Amans-MBP:~ amanbhimani$ streamlink twitch.tv/PetesGameRoom high
[cli][info] Found matching plugin twitch for URL twitch.tv/PetesGameRoom
[cli][info] Available streams: audio, mobile (worst), low, medium, high, source (best)
[cli][info] Opening stream: high (hls)
[cli][info] Starting player: /Applications/VLC.app/Contents/MacOS/VLC
[cli][info] Player closed
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

**Comment by bastimeyer** [comment] 2017-04-24 05:03
How did you install streamlink? Such errors where streamlink is working from the shell and not in the Twitch GUI are usually occurring when you or the GUI have selected a wrong python executable to interpret the streamlink python script. The GUI app tries to read the shebang of Streamlink's entry script first (`where streamlink`), which is exactly the same what's being done in the cli when simply executing `streamlink`. There are a few fallback methods to that, but since mac apps don't have access to the system's `PATH` env var, it needs to use static fallback paths for resolving the python exec and script. Please use the search function on the issue tracker. There are similar threads with solutions to fix this. The configuration guide in the wiki has also some more information. 
Btw, there's a fix coming for homebrew installations of Streamlink, but I haven't had time yet to merge the changes and publish a new release.

**Comment by amanb014** [comment] 2017-04-24 16:53
I used the installation guide on github to install streamlink with easy_install:
`easy_install -U streamlink`

I've tried this now:
`cat $(which streamlink) | head -n 1`
returns 
`/usr/bin/python`

and
`which python`
returns exactly the same thing. 
So GUI and CLI are using the same python executable.. But I've explicitly set the python path in the GUI to /usr/bin/python and it makes no difference.

Is this what you mean by static fallback paths?

**Comment by amanb014** [comment] 2017-04-24 17:11
I'll close this issue now. It seems to be a problem with VLC processing what streamlink/GUI gives it in http. I installed mpv and the stream started right up.

Thanks for the help!

**Comment by bastimeyer** [comment] 2017-04-24 17:20
Can you try VLC again with http as stream type in the GUI and add the `-v -l debug` custom streamlink params? (requires advanced settings)
I'd like to know the log output of both streamlink and VLC. Thanks

If this is an unfixable issue, there should be a note added to the wiki, I think.

**Comment by amanb014** [comment] 2017-04-24 17:29
Attached the log here.. 

VLC seems to work fine with rtmp but not with http or hls (at least the VLC version that I have). Probably worth mentioning that the GUI isn't working with VLC on http; however, this is only from 1 OS X perspective.. But seems like the comment I linked earlier was also on OS X 12.x.

[vlc_http_streamlink_log.txt](https://github.com/streamlink/streamlink-twitch-gui/files/952580/vlc_http_streamlink_log.txt)

**Comment by bastimeyer** [comment] 2017-04-24 17:57
```
[000000010a776618] filesystem access error: cannot open file /Applications/Streamlink Twitch GUI.app/Contents/Resources/app.nw/http://127.0.0.1:51933/ (No such file or directory)
```
Why is it appending the URL of Streamlink's progressive http streaming proxy server (the http passthrough method) to the dirname of the NW.js executable path? What is going on? This must be a VLC or Streamlink bug, because the http url is treated as a relative path.

Can you tell me the params Streamlink Twitch GUI is using to invoke the streamlink child process? To do this, start the GUI with the `-l debug` param and get the log from `stdout` or from the file located in the system's temp dir (`open $(echo "${TMPDIR}/streamlink-twitch-gui")`). There may already be error logs with the used params. Please be aware that the logs might contain your twitch oauth token.

**Comment by amanb014** [comment] 2017-04-24 19:08
Hmm wow, that is really weird. I'll try and see if I can figure it out as well if I have some time to go through your code while dealing with finals! But here's the params it's using: 

`Spawning streaming provider process`
`{`
`    "exec": "/usr/bin/python",`
`    "params": [`
`        "/usr/local/bin/streamlink",`
`        "--http-header",`
`        "Client-ID=phiay4sq36lfv9zu7cbqwz2ndnesfd8",`
`        "--no-version-check",`
`        "--twitch-disable-hosting",`
`        "--player",`
`        "/Applications/VLC.app/Contents/MacOS/VLC",`
`        "--player-args",`
`        "--play-and-exit --input-title-format \"COSMOS - Cosmos - The COSMOS marathon will start April 24 at 12PM Pacific!\" {filename}",`
`        "--player-passthrough",`
`        "http",`
`        "--player-continuous-http",`
`        "--twitch-oauth-token",`
`        "xxxxxxxxxxxxxxxxx",`
`        "--hls-live-edge",`
`        "3",`
`        "--hls-segment-threads",`
`        "1",`
`        "--retry-open",`
`        "1",`
`        "--retry-streams",`
`        "1"`
`    ]`
`}`

**Comment by bastimeyer** [comment] 2017-04-24 20:14
Well, as you can see, the correct params are being used. But maybe you're able to reproduce this from the CLI with the given parameters. The `--player-passthrough http` param should actually be enough, but I wanted to be sure that there's nothing else set.
Btw, you can use \`\`\` in markdown for multi-line log/code.

**Comment by amanb014** [comment] 2017-04-24 20:20
Hmm, it's working on CLI with `--player-passthrough http` Here's the debug log.. I guess it must be something in the GUI that is considering the http URL as a relative path..

Thanks for the ``` tip!

```
$ streamlink twitch.tv/cosmos 720p --player-passthrough http -l debug
[cli][info] Found matching plugin twitch for URL twitch.tv/cosmos
[plugin.twitch][debug] Getting live HLS streams for cosmos
[cli][info] Available streams: audio_only, 160p (worst), 360p, 480p, 720p, 1080p (best)
[cli][info] Opening stream: 720p (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 2938 to queue
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Adding segment 2939 to queue
[stream.hls][debug] Adding segment 2940 to queue
[stream.hls][debug] Download of segment 2938 complete
[cli][info] Starting player: /Applications/VLC.app/Contents/MacOS/VLC
[stream.hls][debug] Download of segment 2939 complete
[cli][debug] Writing stream to output
[stream.hls][debug] Download of segment 2940 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 2941 to queue
[stream.hls][debug] Adding segment 2942 to queue
[stream.hls][debug] Download of segment 2941 complete
[cli][info] Player closed
[stream.hls][debug] Closing worker thread
[stream.hls][debug] Closing writer thread
[stream.hls][debug] Download of segment 2942 complete
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

**Comment by bastimeyer** [comment] 2017-11-19 07:03
The next release will include different and much clearer options for choosing the type of Streamlink/Player connection. Stdin will be used by default instead of the local http server option, which should fix this issue.

Closing the thread, but feel free to reopen, if there are any further issues. The next release will be published today, but if you want to test it right now, check out the master branch.

**Closed by bastimeyer** 2017-11-19 07:03 UTC
Labels: bug, MacOS, streamlink
