### ISSUE TITLE
Subs edit/cancel buttons disfunct

### ISSUE THREAD

**Issue by pquerner** [streamlink/streamlink-twitch-gui#651] opened 2019-07-06 13:46 UTC
## Bug report

- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] This is a bug report and I have read the contribution guidelines.

### Environment details

**Operating system and version:**  
Windows 10

**Streamlink Twitch GUI version:**  
Streamlink 1.7.1

**Streamlink version:**  
Not needed.

### Description

Clicking on the button to edit or cancel a sub from the subcriptions menue will result in this url: https://www.twitch.tv/products/undefined/ticket/edit

As you can see the name "undefined" is used instead of the twitch channel name. 

### Expected / Actual behavior

Correct twitch channel name should be used.

### Reproduction steps

1. Have a sub to a channel
2. Click cancel/edit button from subscription menu
3. Check redirect (open browser tab)

**Comment by bastimeyer** [comment] 2019-07-09 06:46
Thanks for the report, this will be fixed later.

That bug was caused by
- https://github.com/streamlink/streamlink-twitch-gui/commit/69f41958468812b3aa135ea0ebae2fa1e8babb95#diff-eadb4462b378f4cead747083c9dc186cL25
- https://github.com/streamlink/streamlink-twitch-gui/commit/69f41958468812b3aa135ea0ebae2fa1e8babb95#diff-eadb4462b378f4cead747083c9dc186cL72

when I moved the subscription duration logic from the component into the model and didn't add the remaining tests for the component.

**Closed** 2019-07-16 20:31 UTC
Labels: bug
