### ISSUE TITLE
Streamlink delay

### ISSUE THREAD

**Issue by Larsenay** [streamlink/streamlink-twitch-gui#532] opened 2018-01-19 21:00 UTC
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] I tried solving my issue by reading the project's wiki first.
- [x] I have read the contribution guidelines und used the search function to find already existing threads.

### Description
Ever since I got a new computer, all streams watched with Streamlink through the Streamlink Twitch GUI has a 3 second delay compared to the Twitch website instead of being 5 seconds ahead.

### Expected / Actual behavior
Lower delay than Twitch Website

### Reproduction steps

1. I copied all files from my old computer
2. Reinstalled the entire program
3. Looked through everything in the wiki and other issues

### Environment details

Operating system and version: Windows 10
Streamlink Twitch GUI version: 1.4.1
Streamlink version: 0.9.0
Configuration details: Using VLC, tried with and without the file-caching=5000. hls-segment-threads=10 and hds-segment-threads=10.

**Comment by skulblakka** [comment] 2018-01-19 21:43
Did you try changing the ```--hls-live-edge``` parameter? In the GUI you can find it under Settings->Streaming. 

Also does this increased delay only happen when using the GUI or also if you use streamlink directly?

**Comment by bastimeyer** [comment] 2018-01-20 11:55
@Larsenay 
Remember that Streamlink Twitch GUI is just a launcher for Streamlink. If you're experiencing streaming delay issues, then you need to configure Streamlink properly.

As @skulblakka has already said, Streamlink's `--hls-live-edge` parameter is responsible for the delay. What this parameter does is setting the amount of HLS segments (stream chunks of 2 seconds on Twitch) which get cached before the data is being fed to the player. This works in conjunction with the `--hls-segment-threads` parameter. I recently explained it in https://github.com/streamlink/streamlink-twitch-gui/issues/526#issuecomment-355760079

Also, please be aware that setting an addition player cache is an unnecessary layer of caching if you prefer having the shortest delay possible.

I'll leave this thread open for a while for you to respond, but if you think the issue is solved, please close it.

**Comment by skulblakka** [comment] 2018-01-20 19:41
I actually noticed the increased delay myself today. Some quick testing makes me think the issue was introduced with merging https://github.com/streamlink/streamlink/pull/1303 a few weeks ago. It also seems to be resolved with https://github.com/streamlink/streamlink/pull/1424.

Either way I noticed this with and without the GUI, meaning if the issue persists you should create an issue over in the streamlink issue tracker.

**Comment by bastimeyer** [comment] 2018-04-23 08:32
Closing, thanks for the help, @skulblakka

**Closed by bastimeyer** 2018-04-23 08:32 UTC
Labels: configuration, streamlink
