### ISSUE TITLE
Streamlink twitch gui + livestreamer "Invalid version check output"

### ISSUE THREAD

**Issue by AngryPenguinPL** [streamlink/streamlink-twitch-gui#524] opened 2018-01-02 18:40 UTC
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] I tried solving my issue by reading the project's wiki first.
- [x] I have read the contribution guidelines und used the search function to find already existing threads.

### Description

Hi.
Just trying streamlink twitch gui with livestreamer and I can't watch any streams.
First I use livestreamer because in my linux distro still not exist streamlink yet. I use Linux Mageia 6x64 and in repo I have only python-livestreamer-1.12.2-3.mga6.noarch.rpm and python3-livestreamer-1.12.2-3.mga6.noarch.rpm

So I after installed livestreamer 1.12.2-3 Im able to watch streams from command line but when Im download streamlink twitch gui I can't.
Trying chose livestreamer in options but still have issue when trying watch stream inside streamlink twitch gui: 

[error][StreamingService]
Error: Invalid version check output

I must manually located livestreamer because app not find it automatic and gives me error: 
[error][StreamingService]
ProviderError: Couldn't find python script
Executables were not found

So i located it as:
/usr/bin/python3
/usr/bin/python3-livestreamer

and this gives me only "Error: Invalid version check output".
Anyone know how to fix this? :D

### Environment details

Operating system and version: Linux Mageia 6 x64
Streamlink Twitch GUI version: 1.4.1
Streamlink version: ... Livestreamer 1.12.2

**Comment by bastimeyer** [comment] 2018-01-02 19:09
> Error: Invalid version check output

Does your package modify the output of Livestreamer's `--version` parameter by any chance?
This regexp needs to match in order to succeed:
https://github.com/streamlink/streamlink-twitch-gui/blob/v1.4.1/src/config/streaming.json#L20

What is the output of `python3-livestreamer --version`?

> So i located it as:
> /usr/bin/python3
> /usr/bin/python3-livestreamer

Streamlink Twitch GUI only has the generic "python" and "livestreamer" names in its fallback list. It's nearly impossible to get it right on all Linux distros at the same time, that's why you have to set explicit paths (or executable names that get resolved by the Twitch GUI).
https://github.com/streamlink/streamlink-twitch-gui/blob/v1.4.1/src/config/streaming.json#L72-L110

> First I use livestreamer because in my linux distro still not exist streamlink yet.

You can install Streamlink via `python-pip`. You should do this instead of using Livestreamer, even if it's not packaged (yet) for your distro. Maybe you should also inform the creator of the package, since Livestreamer is a dead project.
https://streamlink.github.io/install.html#source-code

**Comment by AngryPenguinPL** [comment] 2018-01-02 19:55
Output from --version

```
 [x@localhost ~]$ /usr/bin/python3-livestreamer --version
python3-livestreamer 1.12.2
```

**Comment by bastimeyer** [comment] 2018-01-02 20:25
Well, the issue is that Livestreamer has been packaged differently in your distro and is using a different python script name, `python3-livestreamer` instead of just `livestreamer`.

The returned version string always includes the name of the init script. This is also the case in Streamlink and it hasn't been changed since Livestreamer:
https://github.com/streamlink/streamlink/blame/0.9.0/src/streamlink_cli/argparser.py#L202

That's why the regexp of the Twitch GUI doesn't match, but as I've said, it's impossible to know how Streamlink or Livestreamer have been packaged on each OS and Linux distro. Checking and matching the version string is the only *reliable* thing that can be done here in order to validate the setup of Streamlink or Livestreamer on the user's system.

Let me fix the regexp for you real quick. I'm going to fix the tests later, since I want to rewrite them anyway...

Once this has been pushed to master, you can build the app by following the instructions in the README.md or CONTRIBUTING.md files.

**Closed** 2018-01-02 20:34 UTC
Labels: Linux, livestreamer

**Comment by AngryPenguinPL** [comment] 2018-01-05 20:15
Build today and works fine on this path 
/usr/bin/python3
/usr/bin/python3-livestreamer

Thanks :)
