### ISSUE TITLE
Option to choose between new / legacy chat

### ISSUE THREAD

**Issue by mickaelftw** [streamlink/streamlink-twitch-gui#554] opened 2018-04-06 23:39 UTC
### Checklist

- [ ] This is a bug report.
- [x] This is a feature request.
- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] I tried solving my issue by reading the project's wiki first.
- [x] I have read the contribution guidelines und used the search function to find already existing threads.

Hi,

Any chance to add an option to choose between new chat / legacy chat ?
Legacy chat is way better for the moment, since FFZ is  not completly working with the new chat.

Thank's

**Comment by bastimeyer** [comment] 2018-04-07 07:42
The chat URL had to be changed because bits which were not working correctly. See #551 and #536...

As I said here earlier (https://github.com/streamlink/streamlink-twitch-gui/pull/536#issuecomment-379369010), any issues caused by browser extensions need to be fixed by the developers of these extensions themselves. The current chat URL is the one which is being used by the Twitch website in the chat popout mode, so it's nothing really unusual.

As an alternative to the web browser, you could try using Chatty, which supports all of the popular custom emoticons and also has lots of other features. Streamlink Twitch GUI already has chat profiles for Chatty and Chatty standalone (on Windows).

However, regarding your question of implementing a URL selection, I originally thought about adding this as well, but then decided against it, because I didn't know there were any issues using the popout URL. But since I'm seeing a couple of people already asking for it, I guess this can be added to circumvent these issues.

**Closed** 2018-04-07 07:48 UTC
Labels: chat, feature request
