### ISSUE TITLE
Annoying to change quality presets

### ISSUE THREAD

**Issue by undeference** [streamlink/streamlink-twitch-gui#654] opened 2019-07-21 21:16 UTC
## Bug report

- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] This is a bug report and I have read the contribution guidelines.

### Environment details

**Operating system and version:**  Fedora release 30 (Thirty)

**Streamlink Twitch GUI version:**  1.7.1

**Streamlink version:**  1.1.1

**Configuration details:**  

### Description

When I start typing in a quality preset field, a "Please confirm" box immediately pops up. If I dismiss it, it will come right back as soon as I type some more. I have discovered that the field I am editing does not lose focus, so I can still edit it.

Clicking "cancel" makes it go away (temporarily).
Clicking "apply" or "discard" takes me to a random page, sometimes top games, sometimes top streams, my live streams, occasionally something resulting in a 410 Gone.

### Expected / Actual behavior

Do not block what I am typing. Only prompt me if I am trying to leave the settings without saving first.

### Reproduction steps

1. ...
2. ...
3. ...

### Log output

```
REPLACE THIS TEXT WITH THE LOG OUTPUT
```

### Additional comments, screenshots, etc.
![wtf](https://user-images.githubusercontent.com/3173583/61597185-e18e4980-ac15-11e9-9940-47cc3791991a.png)

**Comment by bastimeyer** [comment] 2019-07-21 21:20
Duplicate of #647. The issue has already been fixed on the master branch.
I'll publish a new release this week.

**Closed by bastimeyer** 2019-07-21 21:20 UTC
