### ISSUE TITLE
Stream launch failure

### ISSUE THREAD

**Issue by GenesisFR** [streamlink/streamlink-twitch-gui#637] opened 2019-04-26 16:47 UTC
## Bug report

- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] This is a bug report and I have read the contribution guidelines.

### Environment details

**Operating system and version:** Windows 10 x64 1809

**Streamlink Twitch GUI version:** 1.7.1

**Streamlink version:** 1.1

**Configuration details:** English language

### Description

There's a missing translation in the quality drop-down menu when opening a stream. I can't tell what's the missing translation as the string is cut out.

### Expected / Actual behavior

It should say something like "Quality" or not be displayed at all.

### Reproduction steps

I can't reproduce it as I was randomly browsing streams. Tried to open the same streams again, multiple streams at the same time or cancelling them. What's weird is that the window in the attached screenshot doesn't have any information about a stream.

### Log output

```
REPLACE THIS TEXT WITH THE LOG OUTPUT
```

### Additional comments, screenshots, etc.

When upgrading from portable 1.7.0, I drag and dropped the content of streamlink-twitch-gui-v1.7.1-win64.zip over my Twitch GUI directory and replaced all files.

![image](https://user-images.githubusercontent.com/3614449/56822853-58d35d80-6820-11e9-8b2d-d7d4057614d3.png)

**Comment by bastimeyer** [comment] 2019-04-27 02:39
The issue is not a missing translation, but rather an error while trying to initialize the stream-launch sequence which is not covered by the regular error flow. You're only seeing the missing translation text because the drop-down needs the quality selection from the active stream record in order to show the correct text, and this data doesn't exist for some reason, same as the other stuff like the channel name, stream title, etc.

Could you please see if an error got logged in the log files or if it gets logged to `stderr` while the app is running?
On Windows, the log dir is here: `%TMPDIR%\streamlink-twitch-gui\logs`
https://github.com/streamlink/streamlink-twitch-gui/wiki/Parameters

> I can't reproduce it as I was randomly browsing streams.

Could you please be a bit more specific what exactly you were doing since the application start? Which channels were you trying to watch? Do you have custom settings set for the channels you're trying to watch?

**Comment by GenesisFR** [comment] 2019-04-27 07:03
Well, if it's not a translation issue then we can close this as it's pretty much a one-time issue which I can't reproduce. I've been using Twitch GUI for more than a year and this has never happened before.

I just checked and don't have any log, just a cache folder.

As I said, I was randomly browsing streams. Opened Twitch GUI, typed "Max Payne" in the search bar, clicked on Max Payne, opened a stream, clicked on Previous then Max Payne 2, opened and closed the 2 streams you can see on the screenshot then maybe reopened one of them. Really not sure about these steps though.

**Comment by bastimeyer** [comment] 2019-04-27 08:18
Let's not close this thread. I think I know what the issue is, but I don't know what caused it. Without a log, this is a bit difficult, unfortunately.

Like I've mentioned, it looks like the active stream record wasn't set when the streaming dialog was opened. This makes be believe that there was an error regarding loading custom channel settings or a malformed Twitch API reponse while loading the channel data. If I don't manage to find and fix this issue, it will be resolved enventually when I'm going to rewrite the entire streaming logic (which I already wanted to a long time ago).

**Comment by GenesisFR** [comment] 2019-04-27 10:05
I'm not using custom channel settings.

I suppose there's no way of setting logging verbosity without using the launch parameter? Haven't found anything in the GUI. I set it to debug for now and can see the logs in my temp folder. I'll send you the log if the issue ever happens again.

By the way, there's no environment variable named "%TMPDIR%" by default on Windows, just "%TEMP%" and "%TMP%".

**Comment by bastimeyer** [comment] 2019-04-27 11:19
> I suppose there's no way of setting logging verbosity without using the launch parameter?

No. That's because the settings get loaded way too late during the app initialization.

I don't think debug messages will be of use here. I'm surprised though that the error got swallowed and not logged. Maybe there's something else which I am missing here. Luckily it's a very rare bug, so I am not too worried right now.

> there's no environment variable named "%TMPDIR%"

Thanks, that's of course true. I just mindlessly copied it from the wiki, which is now fixed (I've also fixed several other things on that page).

**Comment by GenesisFR** [comment] 2019-07-25 07:46
I've had the issue happen again tonight on the same version. Clicked on a live channel but it was hosting another channel. Streamlink Twitch GUI doesn't get the stream info but the hosted channel gets opened in VLC.

![image](https://user-images.githubusercontent.com/3614449/61855375-f1b05e00-ae8d-11e9-8bf8-ac129e147af9.png)
![image](https://user-images.githubusercontent.com/3614449/61855382-f5dc7b80-ae8d-11e9-81c6-f9dbbd966cc4.png)

The only thing appearing in the log is this:

> [2019-07-25T07:43:14.932Z][error][StreamingService]
> Error: anthony_kongphan is hosting grimmmz

**Comment by bastimeyer** [comment] 2019-08-03 04:35
I'm now also running into this issue after fixing a few bugs/issues for the next release and bumping NW.js to 0.40.0 (latest version) in preparation for that.

The issue here is caused by a silly EmberData implementation when unloading a model/record and trying to create a new one later on (closing a stream and re-opening it again in this case).
https://github.com/streamlink/streamlink-twitch-gui/blob/v1.7.1/src/app/services/streaming/service.js#L82-L103
Usually, the `hasRecordForId` should guard against creating duplicate records, but it doesn't seem to be doing it here.

I've experienced this EmberData bug in the past, and also created a test case for this and posted a Gist on EmberData's issue tracker:
https://gist.github.com/bastimeyer/ecb84112ba24082dfa58fdd3596ef978#file-foo-test-js

What I don't understand is why this is only happening to me when I use NW.js 0.40.0 instead of 0.37.4 (currently used version).

**Comment by bastimeyer** [comment] 2019-08-03 04:36
After this bug has been fixed, I will add proper error logging.

**Comment by bastimeyer** [comment] 2019-08-07 09:51
I've pushed the fix to the `nwjs-40` branch. The issue will be closed once it gets merged into master. I still have to check and see whether the NW.js bump has caused any issues on other platforms before I can merge it. Error logging improvements are also added to that branch.

**Closed** 2019-08-07 13:39 UTC
Labels: bug
