### ISSUE TITLE
Streamlink Twitch GUI doesn´t open VLC "Command line options couldn´t be loaed"

### ISSUE THREAD

**Issue by KatMan1221** [streamlink/streamlink-twitch-gui#692] opened 2019-11-30 23:49 UTC
Using Win64

Installed Streamlink Twitch GUI 1.9.0

Installed Streamlink 1.3.0

Opened Streamlink Twitch GUI and selected options -> streaming -> Streamlink (Windows) and put in the direct path to "streamlinkw.exe"

Tried to open a Twitch stream, window pops up, "starting stream"

Then this happens:
https://prnt.sc/q4g3hs

This window closes after about 0.5seconds and Steamlink Twitch GUI says Stream closed and asks me if I want to restart.

What I am doing wrong? Sorry no idea about coding or else. 

Thanks in advance

**Comment by bastimeyer** [comment] 2019-12-01 03:44
Streamlink Twitch GUI doesn't open any video players. It's Streamlink that does this. And when the player process terminates after it has been "successfully" started, then Streamlink interprets this as a regular user action of closing the stream.

Which player settings are you using? Are you using the VLC player preset? This preset automatically applies certain player parameters.

According to your screenshot, you are using VLC version 1.1.6 which is almost 10 years old now:
videolan/vlc@af742c72f339e015db77e2447cf233bf776ff1be (had to find the changelog commit in the VLC repository because the release date was nowhere to be found else)

Please upgrade to a more recent VLC version or disable all player parameters in the player settings menu which your old VLC version doesn't support.

**Comment by KatMan1221** [comment] 2019-12-01 13:36
Thanks for the quick reply.

After updating VLC it does open the stream.

Nevertheless the stream within VLC runs now at 1 fps and completely crashes my computer. Although it doesnt use a lot of RAM or CPU...before Streamlink Twich GUI worked perfectly smooth...

How can I identify the problem now?

**Comment by bastimeyer** [comment] 2019-12-01 14:49
> 1 fps

Check VLC's decoding/rendering settings (or try using a different player like MPV or MPC-HC for example) and make sure that your problem isn't caused by something else on your system. Also make sure that your system is up-to-date.

You can also try running Streamlink from the command line shell with the [`--verbose-player`](https://streamlink.github.io/cli.html#cmdoption-verbose-player) parameter to see if your player is logging error/warning messages.

```sh
streamlink --verbose-player --player "C:\path\to\player.exe" twitch.tv/CHANNEL best
```

> before Streamlink Twich GUI worked perfectly smooth

Streamlink Twitch GUI has nothing to do with video rendering. It's a launcher for Streamlink which itself has also nothing to do with the video output. If the Twitch GUI starts becoming unresponsive while rendering a video, then it's probably because your GPU is struggling to accelerate both at the same time.

**Comment by KatMan1221** [comment] 2019-12-02 01:36
If I am using MPC, MPC opens and says "file not found"...

It´s annoying.

Streamlink worked perfect with old VLC. No lagging, everything smooth. So I dont get it why I do have this problems now...

I dont understand what you mean by running streamlink from the command line?

**Comment by bastimeyer** [comment] 2019-12-02 07:26
> I dont understand what you mean by running streamlink from the command line?

> **Streamlink Twitch GUI**
> A graphical user interface on top of the Streamlink command line interface.

https://github.com/streamlink/streamlink-twitch-gui#description

> **Streamlink**
> Command-line utility that extracts streams from various services and pipes them into a video player of choice.

https://streamlink.github.io/cli.html

----

> Streamlink worked perfect with old VLC.

You are having issues with **VLC** and not **Streamlink** or **Streamlink Twitch GUI**. I've already told you what to do, but you have to resolve this on your own as it's nothing which I can help you with, especially if you don't provide any useful informations at all.

> MPC opens and says "file not found"

Then you probably have set invalid player-input or player-preset settings in the Twitch GUI. Or you're using an old player version once again that doesn't support reading from `stdin` (added in MPC [`~6 years ago`](https://trac.mpc-hc.org/ticket/3107)).

https://github.com/streamlink/streamlink-twitch-gui/wiki/Streamlink-configuration#player-input
https://github.com/streamlink/streamlink-twitch-gui/wiki/Player-configuration

----

Since the initial issue/question has been solved, I'm tempted to close this thread, but if you manage to provide some informations like an error/debug log from Streamlink's `--verbose-player` parameter or any other useful information, maybe I or someone else can you help you with your performance issue.

**Comment by KatMan1221** [comment] 2019-12-02 14:01
I am sorry, didn´t want to offend you. It is just annoying to have a running system and suddenly next day it isn´t working anymore.

I am using player-preset settings.

But it does look like I solved the problem:

I had lagging with streams that used 780p/60 oder 1080p/60
With streams that use 780p or 1080p I didnt have the lags.

So I googled and found a VLC helping page that fixed VLC 4k plays:
It said "Disable GPU Acceleration" in VLC preferences. And it did work. :)

**Closed** 2019-12-02 14:38 UTC
Labels: Windows, player, unrelated
