### ISSUE TITLE
Music category seems to be somehow limited to one page

### ISSUE THREAD

**Issue by Porkepix** [streamlink/streamlink-twitch-gui#801] opened 2021-05-28 16:54 UTC
## Bug report

- [X] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [X] This is a bug report and I have read the contribution guidelines.

### Environment details

**Operating system and version:**  
Any OS

**Streamlink Twitch GUI version:**  
1.11.0

**Streamlink version:**  
2.1.1

### Description

It's several times I notice this, when going in the Music category, it seems to always be limited to the first page of results and doesn't offer to load more. Other categories might suffer the same issue, but the other one I usually looks at doesn't have this issue, so I don't know what makes the Music one so special.

### Expected / Actual behavior

We should be able to see all the results in the Music category

### Reproduction steps

Just select the Music category in the "Games" tab (I guess more and more this tab should be renamed rather than just refer to games. But a list of games aren't really categories…)

**Comment by bastimeyer** [comment] 2021-05-29 11:10
Duplicate of #744

> when going in the Music category

There is no difference between different categories.

> it seems to always be limited to the first page of results and doesn't offer to load more.

Then the Twitch API has returned an invalid response and it is missing stream records which are necessary for the infinite scroll mechanism to work correctly.

**Closed by bastimeyer** 2021-05-29 11:10 UTC
