### ISSUE TITLE
Invisible window on Windows 10

### ISSUE THREAD

**Issue by Sophon** [streamlink/streamlink-twitch-gui#604] opened 2018-11-02 17:09 UTC
The window is simply not visible on Windows 10. I tried shortcuts of Win + arrow keys. The window isn't resizable either.

### Checklist

- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] I tried solving my issue by reading the project's wiki first.
- [ ] This is not a bug report or feature request and I have read the contribution guides.

### Environment details

**Operating system and version:**   Windows 10

**Streamlink Twitch GUI version:**  Don't know, window invisible.

**Streamlink version:**  newest

**Configuration details:**  

### Description

The window is simply not visible on Windows 10. I tried shortcuts of Win + arrow keys. The window isn't resizable either. This issue occurs only when the laptop screen is the only screen.

If I Shift + rightclick the icon on taskbar and select resize, the cursor moves to left edge of the screen. If I hover my cursor on the taskbar's preview, there's an empty silhouette in the middle of the screen.

### Expected / Actual behavior

For the window to show.

**Comment by bastimeyer** [comment] 2018-11-02 18:38
> This issue occurs only when the laptop screen is the only screen

Did you perhaps move the window out of the desktop's viewport? The GUI should perform a check initially whether it has been moved out of the available screen space, but that may have failed.

If you start the GUI for the first time, it'll position itself at the center of the primary screen. You can force this position again by using the `--reset-window` parameter:
https://github.com/streamlink/streamlink-twitch-gui/wiki/Parameters#--reset-window

> there's an empty silhouette in the middle of the screen

This could mean that your system wasn't able to initialize the app. Is there an error log available? See the `%TMPDIR%/streamlink-twitch-gui/logs` directory.

Other than that, you could try to delete the app's config dir located in `%LOCALAPPDATA%/streamlink-twitch-gui` and also try to reinstall it.

**Comment by Kexerval** [comment] 2018-11-18 05:53
@Sophon Since there are multiple releases of Windows 10, could you tell us what build of Windows 10 this issue is occurring on? You can type `winver` at a command prompt to find out what build you are using. This would help in trying to reproduce the bug.

**Comment by bastimeyer** [comment] 2018-11-26 13:33
Closing, since there hasn't been a response in almost 4 weeks regarding the requested error log.

**Closed by bastimeyer** 2018-11-26 13:33 UTC
Labels: Windows, unconfirmed
