### ISSUE TITLE
Close stream doesn't remove from list

### ISSUE THREAD

**Issue by atward** [streamlink/streamlink-twitch-gui#467] opened 2017-06-02 04:33 UTC
### Description

"Close stream" button on "You're watching" page doesn't remove stream from list if user closed from player. User instead has to select "open dialog" and remove stream from there.

### Expected / Actual behavior

Close stream button should always close stream and remove it from the list.

### Reproduction steps

1. Launch any stream
2. Esc dialog
3. Close player
4. Navigate to You're watching
5. Stream still in list, click "close stream"

### Environment details (operating system, etc.)

Tested on windows, using mpc.
Prevent single instance mode: selected
Allow the player to get closed: selected

### Comments, logs, screenshots, etc.

Issue presented in v1.3.0 and still present in v1.3.1.

**Comment by bastimeyer** [comment] 2017-06-02 08:21
I'm unable to reproduce this.

Which OS are you using, what's your player and which streaming provider are you using in which version (Streamlink or Livestreamer)?

**Comment by atward** [comment] 2017-06-02 15:52
```
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

>streamlink --version
streamlink-script.py 0.6.0
```
```
MPC-HC (64-bit)
---------------

Build information:
    Version:            1.7.11 (b989276ec)
    Compiler:           MSVC v19.00.24215.01
    Build date:         Mar  6 2017 15:02:31

LAV Filters:
    LAV Splitter:       0.69.0.0
    LAV Video:          0.69.0.0
    LAV Audio:          0.69.0.0
    FFmpeg compiler:    MinGW-w64 GCC 6.3.0

Operating system:
    Name:               Windows NT 10.0 (build 14393)
    Version:            10.0 (64-bit)

```

**Comment by bastimeyer** [comment] 2017-06-04 04:53
> Might be compat issue with mpc-hc64?

This is very unlikely.

Streams will only be listed in the watching menu as long as the Streamlink or Livestreamer child process is running or if a stream has ended and the stream dialog is still opened, asking for a restart. This hasn't been the case in the `1.3.0` release though, but was changed by ef4873303d1d29079d4793121f5c1bab7934a389 in `1.3.1`.

Are you really sure that you're using the latest version and not the older one by accicent?

**Comment by atward** [comment] 2017-06-05 09:00
Definitely on 1.3.1. Did some testing for each of the close buttons at various points in the user flow. There's 3, each with different tooltips, only one doesn't work.

works:
[q] close stream
[esc] close

doesn't work:
close stream

Not great at node/js, but I brought them back to (in order):
https://github.com/streamlink/streamlink-twitch-gui/blob/489e5584e6377a9f59744ead72fbf54bd4a92fdb/src/templates/components/modal/ModalStreamingComponent.hbs#L49
https://github.com/streamlink/streamlink-twitch-gui/blob/489e5584e6377a9f59744ead72fbf54bd4a92fdb/src/templates/components/modal/ModalStreamingComponent.hbs#L116

https://github.com/streamlink/streamlink-twitch-gui/blob/698d53b38d2c2a3d2fec02d815df559447d236e8/src/templates/Watching.hbs#L9

action seems different

**Comment by bastimeyer** [comment] 2017-06-05 10:13
> action seems different

What you've linked are two different EmberJS-HTMLBars templates of a component and a route, referencing either the component's action or the action of the route's controller, which both have different names. Both are calling kill() on the stream record eventually and when a stream gets killed (either via the GUI or by closing the player), it gets removed from the data store (the watching list) if
1. its dialog is not open and there was no streamlink / livestreamer / player error
2. its dialog is open and the user has enabled auto-closing dialogs
3. its dialog is open, the user has disabled auto-closing dialogs and the user closes the dialog afterwards or the dialog gets replaced

Closing the dialog and then closing the player should already remove the stream record from the store, unless there was an error, as described in the first point on that list. This is why this bug report is already not reproducible for me, because the stream should be removed by closing the player. If a stream is not running anymore, the "close stream" button on the watching route does indeed nothing, but this situation should not be happening. The only logic error I can see here is if there was an error and the user doesn't want to open the dialog to see the error message and wants to close it directly from the watching list instead.

**Comment by atward** [comment] 2017-06-06 05:49
> The only logic error I can see here is if there was an error and the user doesn't want to open the dialog to see the error message and wants to close it directly from the watching list instead.

this. this is the reported issue

> Expected / Actual behavior
> 
> Close stream button should always close stream and remove it from the list.

**Comment by oakenhold** [comment] 2017-07-01 04:30
### Description

Stream is not removed from "You're watching" after closing the video player.
Clicking the "Close stream" button does not remove the stream either.
Clicking the "Open dialog" button returns error messages (provided below), and clicking the "Close" button removes the stream from "You're watching".

This issue only occurred after upgrading to streamlink 0.7.0.

### Expected / Actual behavior

Stream should automatically be removed from "You're watching" once the video player is closed.
Clicking the "Close stream" button in "You're watching" should also close the stream.

### Reproduction steps

1. Open any stream
2. Close stream by closing the video player
3. Navigate to You're watching
4. Stream still in list

### Environment details (operating system, etc.)

- Windows 10 Pro 64-bit
- Streamlink 0.7.0
- Streamlink Twitch GUI 1.3.1
- VLC 2.2.6 64-bit

### Comments, logs, screenshots, etc.

```
Found matching plugin twitch for URL twitch.tv/rhykker
Attempting to authenticate using OAuth token
Successfully logged in as Oakenhold
Available streams: audio_only, 160p (worst), 360p, 480p, 720p, 1080p (best)
Starting player: D:\Program Files\VideoLAN\VLC\vlc.exe
Got HTTP request from VLC/2.2.6 LibVLC/2.2.6
Opening stream: 1080p (hls)
error: Error when writing to output: [WinError 10053] An established connection was aborted by the software in your host machine, exiting
Stream ended
Closing currently open stream...
D:\Program Files (x86)\Streamlink\pkgs\urllib3\connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
InsecureRequestWarning)
D:\Program Files (x86)\Streamlink\pkgs\urllib3\connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
InsecureRequestWarning)
D:\Program Files (x86)\Streamlink\pkgs\urllib3\connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
InsecureRequestWarning)
D:\Program Files (x86)\Streamlink\pkgs\urllib3\connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
InsecureRequestWarning)
```

**Comment by omperus** [comment] 2017-07-09 13:58
Same here, VLC 2.2.6 64bits

**Comment by fishscene** [comment] 2017-07-13 01:32
Confirming this error. 

OS: Windows 10 (OS Build 15063.483)
Streamlink Version: "streamlink-script.py 0.6.0"
Streamlink Twitch GUI Version: 1.3.1
Media Player: mpv.exe (https://mpv.io/)

The problem appears to have started around the 1.3.1 release of Streamlink GUI. Closing the media player (MPV) does not close out the stream automatically. Manually closing the stream doesn't appear to do anything, and the purple up-arrow (sub menu) must be access to close or re-open the stream.


![2017-07-12 18_19_47-streamlink twitch gui](https://user-images.githubusercontent.com/1910351/28146532-800c095e-672f-11e7-9b71-752de8a21e50.png)
![2017-07-12 18_21_31-streamlink twitch gui](https://user-images.githubusercontent.com/1910351/28146531-80078dde-672f-11e7-9b20-8f3c97ec1a4d.png)

**Comment by skulblakka** [comment] 2017-07-17 09:23
If you take a look at the dialog box after you closed the player, you will notice that streamlink did not exit correctly and instead threw an error. That the dialog stays open in a case like this is the intended behavior (so the user can see what went wrong). This looks more like a streamlink issue to me (maybe related to https://github.com/streamlink/streamlink/issues/916 )

**Comment by fishscene** [comment] 2017-07-18 03:48
I tried to re-install streamlink, but apparently, I may have manually installed it somehow and didn't use the python pip method on Windows 10.
The issue is now resolved for me, here's what I did:

If you are on Windows:
1) Close Streamlink Twitch GUI
2) Download and install Python if you don't have it already: [Python](https://www.python.org/downloads/release/python-362) I downloaded: 
> Windows x86-64 executable installer
3) Open "cmd" as an administrator and run: `pip install streamlink`
4) Open Streamlink Twitch GUI and report back if the issue isn't fixed.

**Comment by bastimeyer** [comment] 2017-07-18 05:05
The `error: Error when writing to output: [WinError: 10053] An established connection was aborted by the software in your host machine, exiting` error message sounds like a Streamlink issue on Windows to me, where it doesn't correctly stop the internal http server when the process gets killed via SIGTERM.
https://github.com/streamlink/streamlink/blob/0.7.0/src/streamlink_cli/main.py#L1034-L1050
https://github.com/streamlink/streamlink/blob/0.7.0/src/streamlink_cli/main.py#L129-L146

Are you able to reproduce this specific error message from the shell by using the `--http-passthrough=http` Streamlink parameter and then sending a SIGINT signal after some time (Ctrl+C)?

However, this belongs to the Streamlink issue tracker and not here. Please open a new thread with some debug information if possible, thanks.

And as I've already said in my previous comment, I am aware of this issue, where streams are not being removed by the close button on the watching list if the stream resulted in an error.

**Comment by moznr** [comment] 2017-07-30 01:07
If you're on Windows just use Streamlink v0.50. I had the same problem on 0.70 & 0.60 and reverting back to 0.50 helped.

**Comment by Porkepix** [comment] 2017-09-11 12:53
Reproduced a similar issue with OS X version, at least when the stream automatically closes itself when the diffusion is ended.
I use the option that closes the pop-out once the stream opens, but when the stream ends, player close and stream stays in the playing stream list with the above-mentionned issues: close button does nothing to remove it from the list. And I think it should anyway disappear from the list by itself.

**Comment by velit** [comment] 2017-09-16 08:01
Updating to streamlink v0.8.1 fixed this issue for me.

**Comment by atward** [comment] 2017-09-16 08:49
Tested using fresh choco installs of:

* streamlink 0.8.1
* streamlink-twitch-gui 1.3.1

Initial reported behavior unchanged.

**Comment by bastimeyer** [comment] 2017-11-08 00:00
Could someone affected by this issue please confirm that streamlink/streamlink#1315 has fixed it?
Streamlink has to be installed manually until the next nightly installer gets built (the 2017-11-08 one).
`pip install git+https://github.com/streamlink/streamlink.git`

Thanks!

**Comment by omperus** [comment] 2017-11-15 03:43
@bastimeyer yes its fixed, thanks a lot.

**Comment by atward** [comment] 2017-11-23 04:21
@bastimeyer appears to be fixed in streamlink 0.9.0.

Behaviour has changed to accurately detect the crash/close of the player and the "You're watching" page is cleaned up automatically as expected. This has removed the need for this behaviour change/bug.

**Comment by Porkepix** [comment] 2017-11-24 10:24
I actually just experienced this again on version 1.4.1 and with streamlink 0.9 on macOS.
This was done with mpv as player and with streams that just timed out after they ended/
If player is manually closed it disappear from the list and therefore can't be tested.
If player (mpv) is still playing the stream and user go to the "You're watching list", then hitting the close button does close the stream, but don't get it removed from the list.

I didn't tried other players to know whether it does change anything or not on the way streamlink and the GUI are informed of the end of the stream.
I guess this should be reopened then @bastimeyer ?
@atward What was your platform?

**Comment by atward** [comment] 2017-11-24 10:26
I'll leave it up for @bastimeyer to determine if this should be reopened.
@Porkepix see https://github.com/streamlink/streamlink-twitch-gui/issues/467#issuecomment-305829597 for platform details.

**Comment by Porkepix** [comment] 2017-11-24 10:27
Yeah, different OS and different player then, many things that can change for the timeout.
The main problem comes from the fact it's not removed from the list I think though.

**Comment by bastimeyer** [comment] 2017-11-24 10:38
The stream only doesn't get removed from the watching list if there was an error logged by Streamlink. This is the right behavior, because the user should be informed of that error, but the way it is displayed right now is not optimal needs to be improved.
The only real bug there is, is the close button in the watching menu that doesn't remove the stream and the popup needs to be opened instead. This needs to get fixed once the stream popup gets reworked, which I intend to do soon.

Let me reopen the thread again, so we don't get unnecessary duplicates.

**Comment by Porkepix** [comment] 2017-11-24 10:43
Well, wouldn't the user expect to not find the stream in the list anymore if it timed out because of a naturel end?
This is a topic for another bug, but maybe it could have an option to automatically try to relaunch ended streams for x seconds/minutes in case of a technical problem causing an unwished end, and after this timer remove it from the list? (This option could be activated by default).

I mean, finding here in the list streams I watched several days ago because they just ended back when I watched then doesn't look like something correct from a user perspective.

Sorry if this is too much offtopic. But I can open another issue if you think it should.

**Comment by bastimeyer** [comment] 2017-11-24 10:48
There is already an opened issue regarding streaming queues and automatic restarts. This is currently not supported and needs to get implemented first.
Again, I'll figure out a way of making Streamlink errors (timeouts or real errors) work better in conjunction with the Twitch GUI.

**Closed** 2018-07-14 06:54 UTC
Labels: bug
