### ISSUE TITLE
HLS + MPC-HC = Failed to render the file.

### ISSUE THREAD

**Issue by Bullet25fxbx** [streamlink/streamlink-twitch-gui#351] opened 2016-12-06 00:03 UTC
----

When opening a stream with the "HLS" setting and Media Player Classic - Home Cinema the video does not load with MPC prompting "Failed to render the file."
This works fine if the stream setting is set to "HTTP".

HLS setting works faster for me to load streams and this worked fine with the last release of Livestreamer-twitch-gui.

...

Streamlink Twitch GUI v1.0.0
Streamlink v0.1.0
Windows 10 Pro
Media Player Classic - Home Cinema v 1.7.8.162 (installed via CCCP)

...

I'll post logs if somebody explains where to find them.

...

**Comment by bastimeyer** [comment] 2016-12-06 04:22
This is not a bug of Streamlink Twitch GUI or Streamlink.

The GUI currently does not check if the selected streaming protocol is supported by the player (preset) you have selected. You have to make sure yourself that your player is able to read and work with it.

Besides that, HLS should work fine with MPC-HC, it does at least on my Windows VMs I have tested it with. There is this thread in their bug tracker, so maybe you're using an older version:
https://trac.mpc-hc.org/ticket/4001?cversion=0&cnum_hist=2

Selecting HLS as `--player-passthrough` method should generally be avoided, as it is just there for *compatibility* reasons and works completely differently than HTTP or RTMP. When using HLS, Streamlink's internal streaming proxyserver will basically be bypassed and Twitch's hls playlist url will just be forwarded to the player which will then have to do all data fetching and buffering instead. The player also can't be closed from within the GUI because of Streamlink's logic of this passthrough method. There is a section in the [wiki](https://github.com/streamlink/streamlink-twitch-gui/wiki/Streamlink-configuration#stream-type) talking about this. It could be improved, though.

**Comment by Bullet25fxbx** [comment] 2016-12-06 20:52
Okay. I just found it weird that the same interaction worked the day before with Livestreamer-twitch-gui and Liverstreamer.

**Comment by bastimeyer** [comment] 2016-12-06 21:19
Are you using a custom Livestreamer config?

You can always try this by running streamlink/livestreamer on their own (the GUI is just a tool for generating the parameter list):
`streamlink --player-passthrough hls --player "path/to/mpc-hc.exe" twitch.tv/CHANNEL best`

**Comment by Bullet25fxbx** [comment] 2016-12-06 22:40
No custom configs, clean installs.

It does appears to be an issue with streamlink and not the gui.
Here is a video showing it works with livestreamer and not streamlink
https://www.youtube.com/watch?v=bPIWZepxn9A

**Comment by bastimeyer** [comment] 2016-12-06 22:54
Just to be sure, can you please run the command I've posted above, so the GUI can be completely ignored?
If this behavor persists, you should open a bug on the streamlink repo.
Thanks!

**Comment by Bullet25fxbx** [comment] 2016-12-06 23:12
Oh yes sorry, Same result with the command. Failed to render the file.

**Comment by bastimeyer** [comment] 2016-12-07 10:10
I'll close this here, since you've opened streamlink/streamlink#263.
Please provide some infos in the linked thread, eg. the log output of the command I have posted.

**Closed by bastimeyer** 2016-12-07 10:10 UTC
