### ISSUE TITLE
Keep waiting for stream to come back after it ended.

### ISSUE THREAD

**Issue by mobbdeep1234** [streamlink/streamlink-twitch-gui#639] opened 2019-04-30 23:26 UTC
I need streamlink to wait for and infinitely try to reconnect to a stream which has ended, but expected to come back. If the stream closed for a second, it should be resumed where it ended, so the recording of the stream would not be distorted. Please support all protocols when adding this feature.

**Comment by bastimeyer** [comment] 2019-05-01 06:03
Wrong repo...
https://github.com/streamlink/streamlink

Also a duplicate of https://github.com/streamlink/streamlink/issues/2227

**Closed by bastimeyer** 2019-05-01 06:03 UTC
