### ISSUE TITLE
Chatty Not Opening Automatically

### ISSUE THREAD

**Issue by Icarus77** [streamlink/streamlink-twitch-gui#576] opened 2018-06-13 23:45 UTC
### Description

Chatty will not open with the stream after selecting one despite it being enabled in options. This happens on the latest version for both my desktop and laptop, but when I used an outdated version (I believe 1.4.2), it functioned properly. I can still open it manually using the right-click "Open Chat" option.

### Expected / Actual behavior

Chatty opens alongside the stream window.

### Reproduction steps

1. Opening any stream

### Environment details

Operating system and version: Windows 7 & Windows 10
Streamlink Twitch GUI version: 1.5.0
Streamlink version: 0.13.0
Configuration details: Streamlink with VLC and Chatty

**Comment by bastimeyer** [comment] 2018-06-14 07:14
I can't reproduce and confirm this.
Do you have a custom channel setting that prevents the chat from launching? Or do you have the context menu option enabled that prevents the chat from being launched when starting a stream via the context menu? Can you share a few more config details please?

**Comment by Icarus77** [comment] 2018-06-14 23:57
I don't have any custom channel settings in Chatty or Streamlink GUI. I simply had the basic Chatty configuration, and it opens perfectly fine when I manually right click from context menu, just doesn't on open on its own. This happened when I updated to latest Streamlink, GUI, and Chatty on both my desktop and laptop.
http://puu.sh/AFsJI/1c917a1a08.png
http://puu.sh/AFsRd/a739e8b998.png

**Comment by bastimeyer** [comment] 2018-06-15 05:20
Could you please start the GUI with the `--loglevel debug` parameter and check the log files in `%TMPDIR%\streamlink-twitch-gui`? What I'm interested in is the `Preparing to launch stream` line and its debug values.

Unfortunately, chat launch errors are not being logged in `1.5.0` (I just added this in d9a97c6f9ab3582ecf188c34a09cffb93e53447d), so I'd appreciate it, if you could build and run the latest version from the master branch. Instructions can be found here:
https://github.com/streamlink/streamlink-twitch-gui/blob/master/CONTRIBUTING.md#developing-and-building

**Comment by Icarus77** [comment] 2018-06-16 00:40
I have the log for 1.5.0, but I don't really have the time or know-how to go about learning to build the beta version.

**Comment by Zulunia** [comment] 2018-07-18 03:19
I was having this issue too, I went through the instructions to build and run the latest commit and Chatty opened no problem. I was hoping to get a debug log for you but apparently the issue seems to be fixed along the way since the 1.5.0 and whats up here now. (For me anyway, tried to attach the build but wont let me do one above 10mb)

About Screen
https://imgur.com/oodM8AH

**Comment by bastimeyer** [comment] 2018-08-09 16:50
Thanks for testing this, @Zulunia.

I'm going to close this. If the issue persists, please reopen it or open a new thread.

**Closed by bastimeyer** 2018-08-09 16:50 UTC
Labels: more info required

**Comment by thoma5nator** [comment] 2018-08-29 07:55
This might happen if the Java version in Streamlink's Java Executable path is a custom path is for an older version and you've updated Java. Chatty will not open on stream startup and the button will shake to deny you access.
