### ISSUE TITLE
Non illuminated channel search HUD is annoying

### ISSUE THREAD

**Issue by TheGloriousArgonaut** [streamlink/streamlink-twitch-gui#543] opened 2018-03-02 20:56 UTC
*Thanks for reporting an issue!*
*Please read the contribution guidelines first! (see the link above)*

*Feel free to use the following template. Be as detailed as possible.*
*Please see the text preview to avoid unnecessary formatting errors.*
*Don't forget to remove this text before submitting.*

----

### Checklist

- [x] This is a bug report.
- [x] This is a feature request.
- [ ] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [ ] I tried solving my issue by reading the project's wiki first.
- [x] I have read the contribution guidelines and used the search function to find already existing threads.

### Description
Under the Browse > Streams section all of the channels appear dim until I mouse over them.
...
This is annoying, the previous "livestreamer Twitch GUI" had ALL channels brightly illuminated so you can clearly see the previews and game title.

### Expected / Actual behavior
Fully illuminated channels for easy browsing.
...
Dimly lit streams which can only be fully seen upon mouse over, making channel browsing slow and troublesome.

### Reproduction steps

1. ... Look at the channels and notice they are hard to see / read.
2. ...
3. ...

### Environment details

Operating system and version: ... 8.1 windows x64
Streamlink Twitch GUI version: ... 1.4.1 windows x64
Streamlink version: ... 0.10.0
Configuration details: ... dark mode for GUI

...

### Comments, logs, screenshots, etc.

screen shot for reference.

![image](https://user-images.githubusercontent.com/12703229/36921403-1f760116-1e19-11e8-91c7-fa8c50eafcb1.png)

**Comment by bastimeyer** [comment] 2018-03-02 20:59
Duplicate of #534 which has already been fixed on the master branch
https://github.com/streamlink/streamlink-twitch-gui/issues/534#issuecomment-363628048

**Closed** 2018-03-02 21:02 UTC
Labels: duplicate
