### ISSUE TITLE
Error Message Invalid selector

### ISSUE THREAD

**Issue by undeference** [streamlink/streamlink-twitch-gui#888] opened 2022-05-18 10:30 UTC
### Checklist

- [X] I understand that **Streamlink Twitch GUI** is just a launcher for **Streamlink**
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink-twitch-gui/blob/master/CONTRIBUTING.md)
- [X] [I have checked the list of open and recently closed issues](https://github.com/streamlink/streamlink-twitch-gui/issues?q=is%3Aissue+sort%3Aupdated-desc)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink-twitch-gui/commits/master)

### Streamlink Twitch GUI version

v2.0.0

### Streamlink version

streamlink 4.0.1

### Operating system, environment and configuration details

Fedora release 35 (Thirty Five) kernel 5.17.7-200.fc35.x86_64

### Description

Often, when I start streamlink-twitch-gui, I get an "Invalid selector" error and the program is useless until I quit and restart it.
![Screenshot at 2022-05-18 13-24-11](https://user-images.githubusercontent.com/3173583/169017836-57e8bb49-9264-4636-a369-eb10e3348e17.png)

### Debug log

```text
[msk@miranda streamlink-twitch-gui]$ ./streamlink-twitch-gui --loglevel debug
[13399:13399:0518/132523.761093:ERROR:sandbox_linux.cc(380)] InitializeSandbox() called with multiple threads in process gpu-process.
[debug][Application]
Parameters
{
    "_": [],
    "tray": false,
    "hide": false,
    "hidden": false,
    "max": false,
    "maximize": false,
    "maximized": false,
    "min": false,
    "minimize": false,
    "minimized": false,
    "reset-window": false,
    "versioncheck": true,
    "version-check": true,
    "logfile": true,
    "loglevel": "debug",
    "l": "debug",
    "launch": "",
    "goto": ""
}
[13403:13422:0518/132526.417638:ERROR:cert_verify_proc_builtin.cc(600)] No net_fetcher for performing AIA chasing.
[13399:13399:0518/132526.903606:ERROR:shared_context_state.cc(75)] Skia shader compilation error
------------------------

Errors:
link failed but did not provide an info log
[13399:13399:0518/132527.099527:ERROR:shared_context_state.cc(75)] Skia shader compilation error
------------------------

Errors:
link failed but did not provide an info log
[13399:13399:0518/132527.105711:ERROR:shared_context_state.cc(75)] Skia shader compilation error
------------------------

Errors:
link failed but did not provide an info log
[13399:13399:0518/132527.202026:ERROR:shared_context_state.cc(75)] Skia shader compilation error
------------------------

Errors:
link failed but did not provide an info log
[13399:13399:0518/132527.212205:ERROR:shared_context_state.cc(75)] Skia shader compilation error
------------------------

Errors:
link failed but did not provide an info log
[13399:13399:0518/132527.215014:ERROR:shared_context_state.cc(75)] Skia shader compilation error
------------------------

Errors:
link failed but did not provide an info log
[error][ErrorRoute]
Error: Invalid selector
{
    "name": "user.followedStreams",
    "params": {}
}
[13399:13399:0518/132527.219782:ERROR:shared_context_state.cc(75)] Skia shader compilation error
------------------------

Errors:
link failed but did not provide an info log
[error][Application]
Ember error: Error: Invalid selector
[13399:13399:0518/132527.222790:ERROR:shared_context_state.cc(75)] Skia shader compilation error
------------------------

Errors:
link failed but did not provide an info log
[13399:13399:0518/132527.263911:ERROR:shared_context_state.cc(75)] Skia shader compilation error
------------------------

Errors:
link failed but did not provide an info log
[13399:13399:0518/132527.407535:ERROR:shared_context_state.cc(75)] Skia shader compilation error
------------------------

Errors:
link failed but did not provide an info log
[13399:13399:0518/132527.517286:ERROR:shared_context_state.cc(75)] Skia shader compilation error
------------------------

Errors:
link failed but did not provide an info log
[13270:13385:0518/132529.864625:ERROR:chrome_browser_main_extra_parts_metrics.cc(227)] START: ReportBluetoothAvailability(). If you don't see the END: message, this is crbug.com/1216328.
[13270:13385:0518/132529.864996:ERROR:chrome_browser_main_extra_parts_metrics.cc(230)] END: ReportBluetoothAvailability()
[error][ErrorRoute]
Error: Invalid selector
{
    "name": "user.followedChannels",
    "params": {}
}
[error][ErrorRoute]
Error: Invalid selector
{
    "name": "games.index",
    "params": {}
}
[error][ErrorRoute]
Error: Invalid selector
{
    "name": "streams",
    "params": {}
}
```

**Comment by bastimeyer** [comment] 2022-05-18 10:41
> v2.0.0

Duplicate of #868 
Fixed by d900ccb28cb1483c93c90174212821d408bb14a7

Please try running the latest version from the master branch.

There will be a new release soon. I didn't have the time over the past couple of days to thoroughly test an NW.js bump to the latest version which I wanted to do before the next release. This always needs to be tested for each OS, which takes a bit of time, because reverting that can't easily be done afterwards.

**Closed by bastimeyer** 2022-05-18 10:41 UTC
