### ISSUE TITLE
Filter specific games from the Top Games/Top Channels view

### ISSUE THREAD

**Issue by flatluigi** [streamlink/streamlink-twitch-gui#364] opened 2016-12-10 17:34 UTC
There's quite a few popular games on Twitch that I don't really have any interest in watching, mainly Dota and League. It'd be very useful to have an option to filter out specific games like those to make browsing for something to watch through the Top Games/Top Channels view much easier.

**Comment by bastimeyer** [comment] 2016-12-10 18:04
Duplicate of #193

**Closed by bastimeyer** 2016-12-10 18:04 UTC
