### ISSUE TITLE
400 Client Error: Bad Request

### ISSUE THREAD

**Issue by iPickedScout** [streamlink/streamlink-twitch-gui#310] opened 2016-09-14 21:42 UTC
Whenever I attempt to open I stream, it keeps sending the message:
 "Unable to open URL: https://api.twitch.tv/api/channels/<insert streamer here>/access_token.json (400 Client Error: Bad Request)"
It was happening before the 0.14.2 update as well, so it isn't caused by that. I didn't see any other issues for this, so I don't know if it is just on my end.

**Comment by bastimeyer** [comment] 2016-09-14 22:14
This is a Livestreamer related issue: chrippa/livestreamer#1456

Twitch is finally making the planned changes live that all API requests need to have a client-id included by the requesting application. See https://api.twitch.tv/api/channels/access_token.json in your browser. I upgraded the GUI a couple of weeks ago, so that it includes the ID even while not being logged in.

I'm not getting this error yet, but you can read [here](https://discuss.dev.twitch.tv/t/client-id-requirement-faqs/6108/41) that they are testing it, so maybe not globally accross their network. Livestreamer doesn't include the client-id, so that's why you're seeing this error.

I don't know though if this issue will be resolved soon. Livestreamer is not being actively maintained anymore, but there are people who are trying to organize a fork. #289

**Comment by bastimeyer** [comment] 2016-09-14 22:42
The issue can be fixed by using a Twitch OAuth token, which means that **you have to be logged in to your Twitch account in the GUI** as long as there is no Livestreamer upgrade.

This also means that I need to require an active login-session in the GUI for being able to launch streams and also add an error message for this. I might upload a new release because of this...

Funny coincidence for feature request #308...

**Comment by jspraul** [comment] 2016-09-15 18:22
Client-ID might be enough right now?

https://github.com/chrippa/livestreamer/issues/1478#issuecomment-247242827

**Comment by bastimeyer** [comment] 2016-09-15 18:36
Yes, this seems to be the better solution, thanks!
I didn't notice that the [`--http-header`](http://docs.livestreamer.io/cli.html#cmdoption--http-header) parameter was available, because I just quickly looked at the code of Livestreamer's [twitch plugin](https://github.com/chrippa/livestreamer/blob/ab80dbd6560f6f9835865b2fc9f9c6015aee5658/src/livestreamer/plugins/twitch.py#L168)...

The auth restriction can be removed again. I'm going to release `v0.15.1` once I have fixed the Windows tray icon regression #312.

**Comment by bastimeyer** [comment] 2016-09-15 19:34
https://github.com/bastimeyer/livestreamer-twitch-gui/releases/tag/v0.15.1

**Comment by BrandonDenton** [comment] 2016-10-05 22:23
I have registered my app with my Twitch account and received a client ID. Where exactly in a Python "requests" library request would I include this client ID? Would it be another argument to requests.get()?

**Comment by bastimeyer** [comment] 2016-10-05 23:01
@BrandonDenton 
Wrong repo...

**Comment by bastimeyer** [comment] 2017-10-26 20:18
I think this can be closed now after a year of Livestreamer being broken in its default configuration. I don't expect many people to run into this issue anymore.

To the people still using Livestreamer: please switch to [Streamlink](https://github.com/streamlink/streamlink).
Thanks...

**Closed by bastimeyer** 2017-10-26 20:18 UTC
Labels: livestreamer, Twitch API
